= Deprecated or removed Expansions.

There are a number of expansions in v3 which have been either
deprecated or removed in v4.  The following text explains why these
functions were removed, and what functionality has replaced them.

== %expr(...)

This expansion has been removed.  Instead, just use `%{ ... }`.

[source,unlang]
----
reply.Reply-Message := "The result of 1 + 2 = %{1 + 2}"
----

== %integer(...)

This expansion has been removed.  Instead, just use `%{(integer) ...}` with math inside of the brackets.

[source,unlang]
----
reply.Reply-Message := "Value of Service-Type is %{(integer) Service-Type}"
----

== +%pack(%{Attribute-Name}%{Attribute-Name}...)+

This expansion has been removed.  Just convert the strings to octets, and concatenate them via `+`.

.Example
[source,unlang]
----
reply.Class := (octets) Framed-IP-Address + (octets) NAS-IP-Address.
----

== %string(...)

This expansion has been removed.  Instead, just use `%{(string) ...}` with an expression inside of the brackets.

[source,unlang]
----
reply.Reply-Message := "The printable version of Class is %{(string) Class}"
----

== %strlen( ... )

This expansion is deprecated and has been be removed.  Just use `%length(...)` instead.

// Copyright (C) 2023 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
