
= Proxy Configuration

The `proxy.conf` file is not used in version 4. The functionality in
the old proxy.conf has moved.

For detailed information on upgrading, see:
xref:howto:upgrade/index.adoc[index]

== home_server sections

The `home_server` definitions are now just RADIUS modules.

See
xref:reference:raddb/mods-available/radius.adoc[mods-available/radius].
You can create a module for each home server. The configuration is
very similar.

You can also send packets to dynamic home servers, without updating
the configuration or adding new modules!. See the
`%proxy.sendto.ipaddr()` function in `mods-enabled/radius`.

== home_server_pool sections

The `home_server_pool` sections are now just virtual modules.  See
xref:reference:raddb/mods-available/home_server_pool.adoc[mods-available/home_server_pool]
for an example.

See the `load-balance`, `redundant`, and `redundant-load-balance`
keywords. Since a `home_server` is now just a RADIUS module, there is
no need to have a separate configuration for load-balanced pools of
home servers!

The `load-balance` and `redundant-load-balance` keywords now also take
an optional parameter which can be used to do keyed load balancing.

The `instantiate` section is also gone from v4. Instead, you can just
create a "virtual" module, by putting a `load-balance` section as a
file directly in the `mods-enabled/` directory.

i.e. instead of using this in `proxy.conf`:

You can instead use this in `mods-enabled/foo`:

== Realms

There is "realm" configuration section. The `realms` module has also
been removed.

@todo - this should really be addressed before a v4 release.

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
