include::../img/header.adoc[]

== The case Statement

.Syntax
[source,unlang]
----
case [ <match> ] {
    [ statements ]
}
----

The `case` statement is used to match data inside of a
link:switch.adoc[switch] statement.  The `case` statement cannot be used
outside of a link:switch.adoc[switch] statement.

The `<match>` text can be omitted, which means that the `case`
statement is the "default" and will match input that is not
matched by another `case` statement inside of the same
link:switch.adoc[switch].

The `<match>` text can be an attribute reference such as `&User-Name`,
or it can be a link:../raddb/syntax/data_string.adoc[string].  If the match
text is a dynamically expanded string, then the match is performed on
the output of the string expansion.

[WARNING]
It is _strongly_ recommended to use static text for the `<match>` text.
Matching dynamically expanded strings, host names, or external
programs can degrade performance enormously.

.Example
[source,unlang]
----
switch &User-Name {
    case "bob" {
        reject
    }

    case {
        ok
    }
}
----

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
include::../img/footer.adoc[]
