
== Data Types

Unlang supports a number of data types. These data types can be used
in conditional expressions or when assigning a value to an attribute.

The interpreter is flexible when parsing data types.  For example, a
particular attribute may be of data type `ipaddr` for IPv4 address.
The interpreter will accept the following strings as valid IPv4 addresses:

`192.168.0.2`:: link:string_unquoted.adoc[Unquoted text], interpreted as the data type

`'192.168.0.2'`:: link:string_single.adoc[Single-quoted string], interpreted as the data type.
+
The single-quoted string form is most useful when the data type
contains special characters that may otherwise confuse the parser.

`"192.168.0.2"`:: link:string_double.adoc[Double-quoted string].
+
The contents of the string are dynamically expanded as described
above.  The resulting output is then interpreted as the given data
type.

`{backtick}/bin/echo 192.168.0.2{backtick}`:: link:string_backticks.adoc[backtick-quoted string].
Run a script, and interpret the result as the data type.

Similar processing rules are applied when parsing assignments and
comparisons, for all attributes and data types.

=== Basic Data Types

The following data types are "basic" data types.  They are fixed-size,
and encapsulate simple concepts such as "integer" or "IP address".

These data types can be used in `unlang`, as they contain simple
values which can be compared, or assigned to one attribute.

.Basic Data Types
[options="header"]
[cols="15%,85%"]
|=====
| Data Type     | Description
| bool		| boolean
| date		| calendar date
| ethernet	| Ethernet address
| float32	| 32-bit floating point number
| float64	| 64-bit floating point number
| ifid		| interface ID
| int8		| 8-bit signed integer
| int16		| 16-bit signed integer
| int32		| 32-bit signed integer
| int64		| 64-bit signed integer
| ipaddr        | IPv4 address
| ipv6addr      | IPv6 address
| octets        | raw binary, printed as hex strings
| string        | printable strings
| time_delta	| difference between two calendar dates
| uint8		| 8-bit unsigned integer
| uint16	| 16-bit unsigned integer
| uint32	| 32-bit unsigned integer
| uint64	| 64-bit unsigned integer
|=====

=== Structural Data Types

The following data types are "structural", in that they form
parent-child relationships between attributes.  These data types can
only be used in the dictionaries.  These data types cannot be used in
`unlang`.

.Structural Data Types
[options="header"]
[cols="15%,85%"]
|=====
| Data Type     | Description
| struct	| structure which contains fixed-width fields
| tlv		| type-length-value which contains other attributes
| vsa		| Encapsulation of vendor-specific attributes
|=====

=== Protocol-Specific Data Types

The following data types are used only in certain protocols.  These
attributes can generally be used only in the dictionaries.  They
cannot generally be used in `unlang`.

.Protocol Specific Data Types
[options="header"]
[cols="15%,15%,70%"]
|=====
| Data Type     | Protocol | Description
| abinary       | RADIUS   | Ascend binary filters
| extended      | RADIUS   | attributes which "extend" the number space
| ipv4prefix    | RADIUS   | IPv4 network with address and prefix length
| ipv6prefix    | RADIUS   | IPv6 network with address and prefix length
|=====


// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
