include::../img/header.adoc[]

== The group Statement

[source,unlang]
----
group {
    [ statements ]
}
----

The `group` statement collects a series of statements into a list.
The default processing sections of the server (`recv Access-Request`,
`send Accounting-Response %{Acct-Status-Type}`, etc.) are also `group` statements.  Those sections are
given different name for management reasons, but they behave
internally exactly like a `group`.

When a `group` statement is processed, all of the statements inside of
the `group` are executed in sequence.  The `group` statement is not
normally used, as the statements within it can just be placed inside of the
enclosing section.  However, the `group` statement is included in the
`unlang` syntax for completeness.

The contents of a `group` subsection can be any `unlang` statement.

*Examples:*

[source,unlang]
----
group {
    sql
    ldap
    file
    if (updated) {
    ...
    }
}
----

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
include::../img/footer.adoc[]
