include::../img/header.adoc[]

== Keywords in Unlang

The following tables list the keywords used in `Unlang`.  These keywords
implement the "flow control" of the policies.

=== Flow Control Keywords

The _flow control_ keywords allow _if / then / else_ checks, simple
looping, etc.

.Flow Control
[options="header"]
|=====
| Keyword | Description
| link:break.adoc[break]     | Exit early from a `foreach` loop.
| link:case.adoc[case]       | Match inside of a `switch`.
| link:else.adoc[else]       | Do something when an `if` does not match.
| link:elsif.adoc[elsif]     | Check for condition when a previous `if` does not match.
| link:foreach.adoc[foreach] | Loop over a list of attributes.
| link:if.adoc[if]           | Check for a condition, and execute a sub-policy if it matches.
| link:return.adoc[return]   | Immediately stop processing a section.
| link:switch.adoc[switch]   | Check for multiple values.
|=====

=== Attribute Editing Keywords

The _attribute editing_ keywords allow policies to add, delete, and
modify attributes in any list or packet.

.Attribute Editing
[options="header"]
|=====
| Keyword | Description
| link:map.adoc[map]         | Map database fields to server attributes.
| link:update.adoc[update]   | Edit a list of attributes.
|=====

=== Grouping Keywords

The _grouping_ keywords allow policies to be organized into groups,
including load-balancing.

.Grouping
[options="header"]
|=====
| Keyword | Description
| link:group.adoc[group]               | Group a series of statements.
| link:load-balance.adoc[load-balance] | Define a load balancing group without fail-over.
| link:redundant.adoc[redundant]       | Define a redundant group with fail-over.
| link:redundant-load-balance.adoc[redundant-load-balance] | Define a redundant group with fail-over and load balancing.
|=====

=== Parent-Child Keywords

The _parent-child_ keywords allow for creation of parent-child
relationships between requests.

For example, it is possible to create a child request, edit its
attributes, and then proxy that packet to an external destination.
This process must be specified manually, unlike in version 3, the
child was created automatically when the `proxy` list was used.

The benefit of these new keywords is that it is now possible to
control when child requests are created.  It is also possible to
control whether or not the parent waits for the child to finish, or
operates independently of the child.  It is also finally possible to
have multiple child requests via the `parallel` keyword.

These new keywords can unfortunately make some simple configurations
more complex than they would have been in version 3.  The trade-off is
that many complex configurations now become trivial, where they were
impossible to create before.

.Parent-Child
[options="header"]
|=====
| Keyword | Description
| link:detach.adoc[detach]         | Detach a child from a parent
| link:parallel.adoc[parallel]     | Create multiple parallel child requests
| link:subrequest.adoc[subrequest] | Create a child request
|=====

=== Module Keywords

The _module_ keywords refer pre-packaged libraries that implement
specific functionality, such as connecting to SQL, LDAP, etc.  The
name used here is not the literal string `module`.  Instead, it is the
name of a pre-packaged module such as `sql`, or `ldap`, or `eap`.

The documentation below describes how to reference modules.  That is,
how to use `sql`, etc. in the policies.  Please see the
link:../raddb/mods-available/[module configuration] and the
link:../howto/modules/[module howto] pages for information on
configuring and using the modules.

.Modules
[options="header"]
|=====
| Keyword | Description
| link:module.adoc[module]               | Execute a named module, e.g., `sql`.
| link:module_method.adoc[module.method] | Execute a particular method of a named module, e.g., `pap.authorize`
| link:module_builtin.adoc[reject]       | Built-in modules, e.g., `reject`, or `ok`, etc.
|=====

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
include::../img/footer.adoc[]
