include::../img/header.adoc[]

== The module Statement

.Syntax
[source,unlang]
----
module
----

The `module` statement is a reference to the named module.  Common
module names include `pap`, `chap`, `files`, `eap`, and `sql`.  The `modules` subsection of `radiusd.conf` contains all of the valid
modules.

When processing reaches a named module, the pre-compiled module is
called. The module may succeed or fail and will return a status code
to the `unlang` interpreter detailing success or failure.

.Example
[source,unlang]
----
chap
sql
----

== Module Return Codes

When a module is called, it returns one of the following codes to
the interpreter; the meaning of each code is detailed to the right of
the source, below:

.Module Return Codes

[options="header"]
|==================================================
|Name |Meaning
|reject |the module rejected the request
|fail |the module failed
|ok |the module succeeded
|handled |the module has handled the request itself
|invalid |the configuration was invalid
|userlock |the user was locked out
|notfound |information was not found
|noop |the module did nothing
|updated |the module updated the request
|==================================================

These return codes can be used in a subsequent conditional
expression (see the processing section for a more detailed description),
thus allowing policies to perform different actions based on the
behaviour of the modules.

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
include::../img/footer.adoc[]
