include::../img/header.adoc[]

== The redundant-load-balance Statement

[source,unlang]
----
redundant-load-balance [ <key> ] {
    [ statements ]
}
----

The `redundant-load-balance` section operates as a combination of the
link:redundant.adoc[redundant] and link:load-balance[load-balance]
sections.

When the `<key>` field is omitted, the module is chosen randomly, in a
"load balanced" manner.

When the `<key>` field is present, it is expanded (if necessary), and
the resulting value is hashed.  The hash is then used to pick a
particular module.  This "keyed" load-balance can be used to
deterministically shard requests across multiple modules.

If that module succeeds, then the server stops processing the
section. If, however, the module fails, then the next module in the
list is chosen (wrapping around to the top).  This process continues
until either one module succeeds or all of the modules have failed.

All of the modules in the list should be the same type (e.g., `ldap`
or `sql`). All of the modules in the list should behave identically,
otherwise different requests will be processed through different modules
and will give different results.

.Example
[source,unlang]
----
redundant-load-balance &User-Name {
    sql1
    sql2
    sql3
}
----

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
include::../img/footer.adoc[]
