= Double Quoted Strings

.Syntax
`"string"`

A double-quoted string allows escape sequences and link:xlat.adoc[dynamic
expansions]. As with link:string_single.asoc[single-quoted strings], text
within double quotes can include spaces.

NOTE: Most values retrieved from external datastores will be treated implicitly
as double-quoted strings.

== Escape sequences

Escape sequences allow the inclusion of characters that may be difficult to
represent in datastores, or the FreeRADIUS configuration files.

.Escape sequences and their descriptions
[options="header", cols="15%,85%"]
|=====
| Escape sequence     | Character represented
| `\\`                | Literal backslash (0x5c)
| `\r`                | Carriage return (0x0d)
| `\n`                | Line feed (0x0a)
| `\t`                | Horizontal tab (0x09)
| `\"`                | Double quote (0x22)
| `\x<hex><hex>`      | A byte whose numerical value is given by `<hex><hex>` interpreted as a hexadecimal number.
| `\x<oct><oct><oct>` | A byte whose numerical value is given by `<oct><oct><oct>` interpreted as an octal number.
|=====

.Examples

`"hello"` +
`"foo bar"' +
`"foo\"bar\""` +
`"this is a long string"` +
`"attribute\tvalue\nusername\t%{User-Name}\nreply-message\t%{reply:Reply-Message}"`
`"The result of 'SELECT * FROM foo WHERE 1' is: %{sql:SELECT * FROM foo WHERE 1}"`

// Copyright (C) 2019 Arran Cudbard-Bell <a.cudbardb@freeradius.org>
// Copyright (C) 2019 The FreeRADIUS project.  Licenced under CC-by-NC 4.0.
