include::../img/header.adoc[]

== The switch Statement

.Syntax
[source,unlang]
----
switch <expansion> {
    case <match-1> {
        [ statements-1 ]
    }
    case <match-2> {
        [ statements-2 ]
    }
    case {
        [ statements-3 ]
    }
}
----

A `switch` statement causes the server to evaluate _expansion_, which
can be an link:cond_attr.adoc[&Attribute-Name] or
link:cond_data.adoc[data].  The result is compared against _match-1_
and _match-2_ to find a match. If no string matches, then the server
looks for the default link:case.adoc[case] statement, which has no
associated match.

The matching is done via equality.  The `switch` statement is mostly
syntactic sugar and is used to simplify the visual form of the
configuration.  It is mostly equivalent to the following use of
link:if.adoc[if] statements:

.Nearly equivalent syntax
[source,unlang]
----
if (<expansion> == <match-1>) {
    [ statements-1 ]
}
elsif (<expansion> == <match-2>) {
    [ statements-2 ]
}
else {
    [ statements-3 ]
}
----

The only difference between the two forms is that for a `switch`
statement, the _expansion_ is evaluated only once.  For the equivalent
link:if.adoc[if] statement, the _expansion_ is evaluated again for every
link:if.adoc[if].

If a matching link:case.adoc[case] is found, the statements within that
link:case.adoc[case] are evaluated. If no matching link:case[case] is
found, the "default" link:case.adoc[case] is evaluated. This default is the
link:case.adoc[case] with no _match_ text.  If there is no default
link:case.adoc[case], then the `switch` statement does nothing.

The _match_ text for the link:case.adoc[case] statement can be an
link:cond_attr.adoc[&Attribute-Name] or link:cond_data[data].

No statement other than link:case.adoc[case] can appear in a `switch`
statement, and the link:case.adoc[case] statement cannot appear outside of a
`switch` statement.

.Example
[source,unlang]
----
switch &User-Name {
    case "bob" {
        reject
    }

    case {
        ok
    }
}
----

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
include::../img/footer.adoc[]
