include::../img/header.adoc[]

== Pre-defined Expansions

In addition to storing attribute references, the server has a number
of pre-defined references, as follows:

## - `%{base64:<string>}`

Encode a string using Base64.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "Caipirinha"
}
update reply {
  &Reply-Message := "The base64 of %{control:Tmp-String-0} is %{base64:%{control:Tmp-String-0}}"
}
```

- output

```unlang
The base64 of foo is Q2FpcGlyaW5oYQ==
```

## - `%{base64decode:<string>}`

Decode a string previously encoded using Base64.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "Q2FpcGlyaW5oYQ=="
}
update reply {
  &Reply-Message := "The base64decode of %{control:Tmp-String-0} is %{base64decode:%{control:Tmp-String-0}}"
}
```

- output

```unlang
The base64decode of Q2FpcGlyaW5oYQ== is Caipirinha
```

## - `%{bin:<string>}`

Convert string to binary.

.Return: _octal_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "10"
}
update reply {
  &Reply-Message := "The %{control:Tmp-String-0} in binary is %{bin:%{control:Tmp-String-0}}"
}
```

- output

```unlang
The 10 in binary is \020
```

## - `%{config:<key>}`

Refers to a variable in the configuration file. See the documentation
on configuration file references.

.Return: _string_

Example

- unlang

```unlang
"Server installed in %{config:prefix}"
"Module rlm_exec.shell_escape = %{config:modules.exec.shell_escape}"
```

- output

```unlang
Server installed in /opt/freeradius
Module rlm_exec.shell_escape = yes
```

## - `%{client:<key>}`

Refers to a variable that was defined in the client section for the
current client. See the sections `client { ... }` in `clients.conf`.

.Return: _string_

Example

- unlang

```unlang
"The client ipaddr is %{client:ipaddr}"
```

- output

```unlang
The client ipaddr is 192.168.5.9
```

## - `%{concat:<delim> <&ref:[idx]>}`

Used to join two or more attributes.

.Return: _string_

Example

- unlang

```unlang
update {
  &control:Tmp-String-0 := "aaa"
  &control:Tmp-String-0 += "bb"
  &control:Tmp-String-0 += "c"
}

update reply {
  &Reply-Message += "%{concat:, %{control:Tmp-String-0[*]}}"
  &Reply-Message += "%{concat:,%{control:Tmp-String-0[*]}}"
}
```

- output

```unlang
aaa, bb, c
aaa,bb,c
```

## - `%{debug:<level>}`

Dynamically change the debug level to something high, recording the old level.

.Return: _string_

Example

- unlang

```unlang
recv Access-Request {
  if (&request:User-Name == "bob") {
    "%{debug:4}"
  } else {
    "%{debug:0}"
  }
  ...
}
```

- output (_extra informations only for that condition_)

```unlang
...
(0)  recv Access-Request {
(0)    if (&request:User-Name == "bob") {
(0)      EXPAND %{debug:4}
(0)        --> 2
(0)    } # if (&request:User-Name == "bob") (...)
(0)    filter_username {
(0)      if (&State) {
(0)        ...
(0)      }
...
```

## - `%{debug_attr:<list:[index]>}`

Print to debug output all instances of current attribute, or all attributes in a list.
expands to a zero-length string.

.Return: _string_

Example

- unlang

```unlang
recv Access-Request {
  if (&request:User-Name == "bob") {
    "%{debug_attr:request:[*]}"
  }
  ...
}
```

- output

```unlang
...
(0)  recv Access-Request {
(0)    if (&request:User-Name == "bob") {
(0)      Attributes matching "request:[*]"
(0)        &request:User-Name = bob
(0)        &request:User-Password = hello
(0)        &request:NAS-IP-Address = 127.0.1.1
(0)        &request:NAS-Port = 1
(0)        &request:Message-Authenticator = 0x9210ee447a9f4c522f5300eb8fc15e14
(0)      EXPAND %{debug_attr:request:[*]}
(0)    } # if (&request:User-Name == "bob") (...)
...
```

## - `%{explode:<&ref> <delim>}`

Split an attribute into multiple new attributes based on a delimiter.

.Return: _the number of total new attributes_.

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "bob.toba@domain.com"
}
"%{explode:&control:Tmp-String-0 @}"
update reply {
  &Reply-Message := "Welcome %{control:Tmp-String-0[0]}"
}
```

- output

```unlang
Welcome bob.toba
```

## - `%{hex:<string>}`

Convert to hex.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "12345"
}
update reply {
  &Reply-Message := "The value of %{control:Tmp-String-0} in hex is %{hex:%{control:Tmp-String-0}}"
}
```

- output

```unlang
The value of 12345 in hex is 3132333435
```

## - `%{integer:<&ref>}`

Print the value of the attribute an integer. In normal operation,
`integer` attributes are printed using the name given by a `VALUE`
statement in a dictionary. Similarly, date attributes are printed as
dates, i.e., "January 1 2010".

This operator applies only to attributes which can be converted to an
integer.  It has no effect on other attribute types and cannot be used
with module references. It is most commonly used to perform
calculations on dates, where the dates are treated as integers.

For example, if a request contains `Service-Type = Login-User`, the
expansion of `%{integer:&Service-Type}` will yield `1`, which is the
value associated with the `Login-User` name. Using
`%{integer:&Event-Timestamp}` will return the event timestamp as an
unsigned 32-bit decimal number.

.Return: _integer_

Example

- unlang

```unlang
update {
  &control:Service-Type := Login-User
}
update reply {
  &Reply-Message := "The value of Framed-User is %{integer:&control:Service-Type}"
}
```

- output

```unlang
The value of Framed-User is 1
```

## - `%{length:<string>}`

The string length operator returns the number of characters in the
given string as a decimal number. It can be used with attribute or
module references. If the string has no value, then the length evaluates
to zero.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "Caipirinha"
}
update reply {
  &Reply-Message := "The lenght of %{control:Tmp-String-0} is %{length:&control:Tmp-String-0}"
}
```

- output

```unlang
  The lenght of Caipirinha is 10
```

## - `%{md5:<string>}` +

Dynamically expands the string and performs an MD5 hash on it. The
result is octal digits.

.Return: _octal_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "Caipirinha"
}
update reply {
  &Reply-Message := "md5 of %{control:Tmp-String-0} is octal=%{md5:%{control:Tmp-String-0}}"
  &Reply-Message := "md5 of %{control:Tmp-String-0} is hex=%{hex:%{md5:%{control:Tmp-String-0}}}"
}
```

- output

```unlang
md5 of Caipirinha is octal=\024\204\013md||\230\243\3472\3703\330n\251
md5 of Caipirinha is hex=14840b6d647c7c98a3e732f833d86ea9
```

## - `%{nexttime:<time>}`

Calculate number of seconds until next n hour(`s`), day(`s`), week(`s`), year(`s`).

.Return: _string_

Example: if it were 16:18, `%{nexttime:1h}` would expand to `2520`.

- unlang

```unlang
update reply {
  &Reply-Message := "You should wait for %{nexttime:1h}s"
}
```

- output

```unlang
You should wait for 2520s
```

## - `%{lpad:<&ref> <val> <char>}`

Left-pad a string.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "123"
}
update reply {
  &Reply-Message := "Maximum should be %{lpad:&control:Tmp-String-0 11 0}"
}
```

- output

```unlang
Maximum should be 00000000123
```

## - `%{rpad:<&ref> <val> <char>}`

Right-pad a string.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "123"
}
update reply {
  &Reply-Message := "Maximum should be %{rpad:&control:Tmp-String-0 11 0}"
}
```

- output

```unlang
Maximum should be 12300000000
```

## - `%{hmacmd5:<shared_key> <string>}`

Generate `HMAC-MD5` of string.

.Return: _octal_

Example

- unlang

```unlang
update {
  &control:Tmp-String-0 := "mykey"
  &control:Tmp-String-1 := "Caipirinha"
}
update {
  &control:Tmp-Octets-0 := "%{hmacmd5:%{control:Tmp-String-0} %{control:Tmp-String-1}}"
}

update reply {
  &Reply-Message := "The HMAC-MD5 of %{control:Tmp-String-1} in octets is %{control:Tmp-Octets-0}"
  &Reply-Message += "The HMAC-MD5 of %{control:Tmp-String-1} in hex is %{hex:control:Tmp-Octets-0}"
}
```

- output

```unlang
The HMAC-MD5 of Caipirinha in octets is \317}\264@K\216\371\035\304\367\202,c\376\341\203
The HMAC-MD5 of Caipirinha in hex is 636f6e74726f6c3a546d702d4f63746574732d30
```

## - `%{hmacsha1:<shared_key> <string>}`

Generate `HMAC-SHA1` of string.

.Return: _octal_

Example

- unlang

```unlang
update {
  &control:Tmp-String-0 := "mykey"
  &control:Tmp-String-1 := "Caipirinha"
}
update {
  &control:Tmp-Octets-0 := "%{hmacsha1:%{control:Tmp-String-0} %{control:Tmp-String-1}}"
}

update reply {
  &Reply-Message := "The HMAC-SHA1 of %{control:Tmp-String-1} in octets is %{control:Tmp-Octets-0}"
  &Reply-Message += "The HMAC-SHA1 of %{control:Tmp-String-1} in hex is %{hex:control:Tmp-Octets-0}"
}
```

- output

```unlang
The HMAC-SHA1 of Caipirinha in octets is \311\007\212\234j\355\207\035\225\256\372ʙ>R\"\341\351O)
The HMAC-SHA1 of Caipirinha in hex is 636f6e74726f6c3a546d702d4f63746574732d30
```

## - `%{pairs:<&list:[*]>}`

Serialize attributes as comma-delimited string.

.Return: _string_

Example

- unlang

```unlang
update {
  &control:Tmp-String-0 := "This is a string"
  &control:Tmp-String-0 += "This is another one"
}

update reply {
  &Reply-Message := "Serialize output: %{pairs:&control:[*]}"
}
```

- output

```unlang
Serialize output: Tmp-String-0 = \"This is a string\"Tmp-String-0 = \"This is another one\"
```

## - `%{rand:<number>}`

Get random number from `0` to `n-1`.

.Return: _string_

Example

- unlang

```unlang
update reply {
  &Reply-Message := "The random number is %{rand:512}"
}
```

- output

```unlang
The random number is 347
```

## - `%{randstr:<character_classes>}`

Get random string built from character classes.

.Return: _string_

Example

- unlang

```unlang
update reply {
  &Reply-Message := "The random string output is %{randstr:aaaaaaaa}"
}
```

- output

```unlang
The random string output is 4Uq0gPyG
```

## - `%{regex:<capture_group>}`

Return named subcapture value from previous regex.

If a regular expression match has previously been performed, then the
special variable `%{0}` will contain a copy of the matched portion of
the input string.
The variables `%{1}` through `%{32}` will contain the substring matches,
starting from the left-most capture group, onwards.
If there are more than `32` capture groups, the additional results will
not be accessible.
If the server is built with `libpcre` or `libpcre2`, the results of named
capture groups are available using the `%{regex:capture group}`
expansion. They will also be accessible using the variables described
above.
Every time a regular expression is evaluated, whether it matches or not,
the capture group values will be cleared.

.Return: _string_.

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "user@example.com"
}

if (&control:Tmp-String-0 =~ /^(?<login>(.*))@(?<domain>(.*))$/) {
  update reply {
    &Reply-Message := "The %{control:Tmp-String-0} { login=%{regex:login}, domain=%{regex:domain} }"
  }
}
```

- output

```unlang
The user@example.com { login=user, domain=example.com }
```

## - `%{strlen:<string>}`

Length of given string.

.Return: _integer_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "Caipirinha"
}
update reply {
  &Reply-Message := "The lenght of %{control:Tmp-String-0} is %{strlen:&control:Tmp-String-0}"
}
```

- output

```unlang
The lenght of Caipirinha is 21
```

## - `%{tag:<attribute:<tag>>}`

Tag of an attribute reference.

.Return: _string_

Example

- unlang

```unlang
update request {
  &Tunnel-Server-Endpoint   := '192.0.1.1'
  &Tunnel-Server-Endpoint:1 := '192.0.5.2'
  &Tunnel-Server-Endpoint:1 += '192.0.3.8'
  &Tunnel-Server-Endpoint:2 := '192.0.2.1'
  &Tunnel-Server-Endpoint:2 += '192.0.3.4'
}

update reply {
  &Reply-Message := "The tag 1 of Tunnel-Server-Endpoint is %{request:Tunnel-Server-Endpoint:1[0]}"
}
```

- output

```unlang
The tag 1 of Tunnel-Server-Endpoint is 192.0.5.2
```

## - `%{tolower:<string>}`

Dynamically expands the string and returns the lowercase version of
it. This definition is only available in version 2.1.10 and later.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "CAIPIRINHA"
}
update reply {
  &Reply-Message := "tolower of %{control:Tmp-String-0} is %{tolower:%{control:Tmp-String-0}}"
}
```

- output

```unlang
tolower of CAIPIRINHA is caipirinha
```
## - `%{toupper:<string>}`

Dynamically expands the string and returns the uppercase version of
it. This definition is only available in version 2.1.10 and later.

.Return: _string_

Example

- unlang

```unlang
update control {
  &Tmp-String-0 := "caipirinha"
}
update reply {
  &Reply-Message := "toupper of %{control:Tmp-String-0} is %{toupper:%{control:Tmp-String-0}}"
}
```

- output

```unlang
toupper of caipirinha is CAIPIRINHA
```

## - `%{urlquote:<string>}`

Quote URL special characters.

.Return: _string_.

Example

- unlang

```unlang
update {
  &control:Tmp-String-0 := "http://example.org/"
}
update reply {
  &Reply-Message += "The urlquote of %{control:Tmp-String-0} is %{urlquote:%{control:Tmp-String-0}}"
}
```

- output

```
The urlquote of http://example.org/ is http%3A%2F%2Fexample.org%2F
```

## - `%{urlunquote:<string>}`

Unquote URL special characters.

.Return: _string_.

Example

- unlang

```unlang
update {
  &control:Tmp-String-0 := "http%%3A%%2F%%2Fexample.org%%2F" # Attention for the double %.
}
update reply {
  &Reply-Message += "The urlunquote of %{control:Tmp-String-0} is %{urlunquote:%{control:Tmp-String-0}}"
}
```

- output

```
The urlunquote of http%3A%2F%2Fexample.org%2F is http://example.org/
```

== Encryption functions

## `OpenSSL >= 1.0.0`

Should support at least:

  - `%{md2:<string>}`
  - `%{md4:<string>}`
  - `%{md5:<string>}`
  - `%{sha1:<string>}`
  - `%{sha224:<string>}`
  - `%{sha256:<string>}`
  - `%{sha384:<string>}`
  - `%{sha512:<string>}`

## `OpenSSL >= 1.1.1`

Also supports the `sha3` and `blake` family of digest functions.

  - `%{blake2s_256:<string>}`
  - `%{blake2b_512:<string>}`
  - `%{sha2_224:<string>}`
  - `%{sha2_256:<string>}`
  - `%{sha2_384:<string>}`
  - `%{sha2_512:<string>}`
  - `%{sha3_224:<string>}`
  - `%{sha3_256:<string>}`
  - `%{sha3_384:<string>}`
  - `%{sha3_512:<string>}`

## Example

.Return: _octal_

- unlang

```unlang
update {
  &control:Tmp-String-0 := "Caipirinha"
}
update reply {
  &Reply-Message := "The md5 of %{control:Tmp-String-0} in octal is %{md5:%{control:Tmp-String-0}}"
  &Reply-Message += "The md5 of %{control:Tmp-String-0} in hex is %{hex:%{md5:%{control:Tmp-String-0}}}"
}
```

- output

```unlang
The md5 of Caipirinha in octal is \024\204\013md||\230\243\3472\3703\330n\251
The md5 of Caipirinha in hex is 14840b6d647c7c98a3e732f833d86ea9
```

== Miscellaneous

## - `%{0}`

Refers to the string that was last used to match a regular expression. The variables `%{1}` through `%{8}` refer to the matched substring in the regular expression.

## - `%{Packet-Type}`

The packet type (`Access-Request`, etc.)

## - `%{Packet-SRC-IP-Address}`, `%{Packet-SRC-IPv6-Address}`

The source IPv4 or IPv6 address of the packet. See also the expansions
`%{client:ipaddr}` and `%{client:ipv6addr}`. The two expansions
should be identical, unless `%{client:ipaddr}` contains a DNS hostname.

## - `%{Packet-DST-IP-Address}`, `%{Packet-DST-IPv6-Address}`

The destination IPv4 or IPv6 address of the packet. See also the
expansions `%{listen:ipaddr}` and `%{listen:ipv6addr}`. If the socket
is listening on a "wildcard" address, then these two expansions will be
different, as follows: the `%{listen:ipaddr}` will be the wildcard
address and `%{Packet-DST-IP-Address}` will be the unicast address to
which the packet was sent.

## - `%{Packet-SRC-Port}`, `%{Packet-DST-Port}`

The source/destination ports associated with the packet.

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
include::../img/footer.adoc[]
