package cest

import (
	"fmt"
	"io"
	"path"
)

// WriteReport renders the console report for one analyzed run.
func WriteReport(w io.Writer, dr *DirResult, patterns []string, cats []Category, topn int) {
	res := dr.Res
	fmt.Fprintln(w, "===================================================")
	fmt.Fprintf(w, "Directory: %s\n", dr.Label)
	fmt.Fprintf(w, "Main file: %s\n", dr.Main)
	fmt.Fprintf(w, "total CEst: %d\n", res.Total)
	fmt.Fprintln(w, "---------------------------------------------------")
	for i, pat := range patterns {
		fmt.Fprintf(w, "%-26s CEst: %d  (%.4f%%)\n", pat, res.PatSums[i], Pct(res.PatSums[i], res.Total))
	}
	fmt.Fprintln(w)

	for i, pat := range patterns {
		fmt.Fprintf(w, "--- Top %d functions matching '%s' ---\n", topn, pat)
		top := dr.TopData[i]
		if len(top) == 0 {
			fmt.Fprintln(w, "  (no matching functions)")
		} else {
			for _, fn := range top {
				fmt.Fprintf(w, "%-36s %11d  %6.2f%%\n", fn.Name, fn.Cost, Pct(fn.Cost, res.Total))
			}
		}
		fmt.Fprintln(w)
	}

	fmt.Fprintln(w, "--- Where the cost goes (categories) ---")
	for i, cat := range cats {
		fmt.Fprintf(w, "%-24s %11d  %6.2f%%\n", cat.Label, res.CatSums[i], Pct(res.CatSums[i], res.Total))
	}
	fmt.Fprintln(w)
}

// WriteComparison renders the comparison footer for two or more runs,
// using the first run as baseline.
func WriteComparison(w io.Writer, dirs []*DirResult, patterns []string) {
	base := dirs[0].Res.Total
	fmt.Fprintln(w, "===================================================")
	fmt.Fprintf(w, "COMPARISON  (baseline = dir 0: %s)\n", path.Base(dirs[0].Label))
	fmt.Fprintln(w, "===================================================")
	for j, dr := range dirs {
		fmt.Fprintf(w, "[dir %d] %s\n", j, dr.Label)
		t := dr.Res.Total
		if j == 0 {
			fmt.Fprintf(w, "  %-14s %18d %12s\n", "total CEst", t, "-")
		} else {
			fmt.Fprintf(w, "  %-14s %18d %+11.2f%%\n", "total CEst", t, Pct(t-base, base))
		}
		for p, pat := range patterns {
			v, bv := dr.Res.PatSums[p], dirs[0].Res.PatSums[p]
			if j == 0 || bv == 0 {
				fmt.Fprintf(w, "  %-14s %18d %12s\n", pat, v, "-")
			} else {
				fmt.Fprintf(w, "  %-14s %18d %+11.2f%%\n", pat, v, Pct(v-bv, bv))
			}
		}
		fmt.Fprintln(w)
	}
}

// WriteMarkdown renders the full Markdown report for one or more runs.
func WriteMarkdown(w io.Writer, dirs []*DirResult, patterns []string, cats []Category, topn int) {
	line := func(format string, a ...any) {
		fmt.Fprintf(w, format+"\n", a...)
	}

	line("# Callgrind CEst Profiling Assessment")
	line("")
	line("_Generated by cest-analyzer. Tables are computed from callgrind.out.* files_")
	line("")
	line("## Headline Results")
	line("")
	if len(dirs) >= 2 {
		delta := Pct(dirs[1].Res.Total-dirs[0].Res.Total, dirs[0].Res.Total)
		line("- Baseline (dir 0): `%s` — total CEst %d", dirs[0].Main, dirs[0].Res.Total)
		line("- Compared (dir 1): `%s` — total CEst %d (%.1f%% vs baseline)", dirs[1].Main, dirs[1].Res.Total, delta)
		line("")
	}
	line("<!-- TODO: short explanation. Example: On a matched, sustained")
	line("workload, the dir-1 build runs ~X%% cheaper in total, but its")
	line("<pattern> self-cost is higher/lower. -->")
	line("")

	// Per-pattern table
	line("## Per-Pattern Self CEst")
	line("")
	line("```")
	header := fmt.Sprintf("%-26s", "Pattern")
	for k := range dirs {
		header += fmt.Sprintf(" %18s %8s", fmt.Sprintf("dir%d CEst", k), fmt.Sprintf("dir%d %%", k))
	}
	line("%s", header)
	for i, pat := range patterns {
		row := fmt.Sprintf("%-26s", pat)
		for _, dr := range dirs {
			v := dr.Res.PatSums[i]
			row += fmt.Sprintf(" %18d %7.2f%%", v, Pct(v, dr.Res.Total))
		}
		line("%s", row)
	}
	line("```")
	line("")

	// Category breakdown
	line("## Where the Cost Goes (whole-program categories)")
	line("")
	for k, dr := range dirs {
		line("**dir %d — %s** (`%s`)", k, dr.Label, dr.Main)
		line("")
		line("```")
		line("Category                  Self CEst   Self %%")
		line("------------------------  ----------  ------")
		for i, cat := range cats {
			line("%-24s %11d  %6.2f%%", cat.Label, dr.Res.CatSums[i], Pct(dr.Res.CatSums[i], dr.Res.Total))
		}
		line("```")
		line("")
	}

	// Top-N per pattern
	line("## Top %d Functions per Pattern", topn)
	line("")
	for i, pat := range patterns {
		line("### Pattern: `%s`", pat)
		line("")
		for k, dr := range dirs {
			line("**dir %d** (`%s`, total %d)", k, dr.Main, dr.Res.Total)
			line("")
			line("```")
			line("Function                              Self CEst   Self %%")
			line("------------------------------------  -----------  ------")
			if len(dr.TopData[i]) == 0 {
				line("  (none)")
			} else {
				for _, fn := range dr.TopData[i] {
					line("%-36s %11d  %6.2f%%", fn.Name, fn.Cost, Pct(fn.Cost, dr.Res.Total))
				}
			}
			line("```")
			line("")
		}
	}

	line("## Methodology")
	line("")
	line("CEst = Ir + 10*(L1 misses) + 100*(LL misses) + 10*(branch mispredicts).")
	line("Self-cost only (QCachegrind \"Self\" column); inclusive cost not computed.")
	line("Parser handles inclusive call-cost lines, event compression, and the")
	line("shared fn=/cfn= symbol table; run totals match QCachegrind exactly.")
	line("Category definitions are editable in DefaultCategories in internal/cest/cest.go.")
}
