[[unlang-conditions]]
Unlang Conditions
-----------------

*Goal:* Explore uses of conditions in the policy language

*Time:* 10-20 minutes

*File:*  

- `etc/raddb/policy.d/*`

*`man` page:* unlang

*documentation page(s):*

- xref:unlang:condition/index.adoc[Conditions]
- xref:unlang:update.adoc[The Update Statement]

The functionality of some modules can be replicated or augmented
using the policy language.

There are many reasons why you may want to change exactly how a module
works, but the most common are to implement additional business logic
or deal with failures in a specific way.

The `suffix` module is used to split an incoming `User-Name` value into
its components and setup the request for proxying.

Create a policy "suffix" that splits an incoming `User-Name` into two
components on the "@" separator.

The first component should be written to the `&request:Stripped-User-Name`
attribute and the second component should be written to the
`&control:Proxy-To-Realm` attribute.

Use `bob@realm1.sh` and `bob@realm2.sh` to test your new policy to ensure
it works as expected.

[[unlang-conditions-questions]]
Questions
~~~~~~~~~

1.  What is one feature of the regular expression operator which make
    it particularly powerful in unlang?
2.  Why might you want to re-implement functionality offered by modules
    in unlang?
3.  What is the advantage of using `return` to exit the section early?
