= Single Letter Expansions

The following are single letter expansions.  These expansions do not
use the typical `%{...}` format.  Instead, they are short-cuts for
simple, common cases.

== Miscellaneous

`%%`::

Returns `%`.


`%n`::

Returns the requesrt number.


== Current Time

`%c`::

The current Unix epoch time in seconds. This is an unsigned decimal number.
It should be used with time-based calculations.

`%C`::

The microsecond component of the current epoch time. This is an unsigned
decimal number. It should be used with time-based calculations.


== Request Time

`%l`::

The Unix timestamp of when the request was received. This is an unsigned
decimal number. It should be used with time-based calculations.

`%Y`::

Four-digit year when the request was received.

`%m`::

Numeric month when the request was received.

`%d`::

Numeric day of the month when the request was received.

`%H`::

Hour of the day when the request was received.

`%G`::

Minute component of the time when the request was received.

`%e`::

Second component of the time when the request was received.

`%M`::

Microsecond component of the time when the request was received.

`%D`::

Request date in the format `YYYYMMDD`.

`%S`::

Request timestamp in SQL format, `YYYY-mmm-ddd HH:MM:SS`.

`%t`::

Request timestamp in _ctime_ format, `Www Mmm dd HH:MM:SS YYYY`.

`%T`::

Request timestamp in ISO format, `YYYY-mm-ddTHH:MM:SS.000`.


// Copyright (C) 2020 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
