.TH ACCT_USERS 5 "05 August 2000"
.SH NAME
acct_users \- RADIUS users file for accounting requests.
.SH DESCRIPTION
The \fIacct_users\fP file resides in the radius database directory,
by default \fI/etc/raddb\fP.  It contains a series of configuration
directives which are used by the server to decide how to log
accounting messages.

The format of this file is identical to that of the 'users' file,
except that it controls the response to accounting requests, not
authentication requests.

.SH FILES
.I /etc/raddb/acct_users
.SH "SEE ALSO"
.BR radclient (1),
.BR radiusd (8),
.BR dictionary (5),
.BR users (5),

.SH AUTHOR
The FreeRADIUS team.
