.TH ACCT_USERS 5 "05 August 2000" "" "FreeRADIUS user accounting file"
.SH NAME
acct_users \- user accounting file for the FreeRADIUS server
.SH DESCRIPTION
The \fBacct_users\fP file resides in the radius database directory, by
default \fB/etc/raddb\fP.  It contains a series of configuration
directives which are used by the \fIfiles\fP module to decide how to
log accounting messages.

The format of this file is identical to that of the \fBusers\fP file,
except that it controls the response to accounting requests, not
authentication requests.

.SH FILES
/etc/raddb/acct_users
.SH "SEE ALSO"
.BR radclient (1),
.BR radiusd (8),
.BR dictionary (5),
.BR users (5)

.SH AUTHOR
Alan DeKok <aland@ox.org>
