.TH CLIENTS 5 "22 August 2002"
.SH NAME
clients \- FreeRADIUS configuration file.
.SH DESCRIPTION
This configuration file is no longer used by the server, and will not
be read by the server. See the "scripts/clients.pl" program for a way
to migrate this file to the new format.
.SH "SEE ALSO"
.BR clients.conf (5)
