.TH NASLIST 5 "12 August 2005"
.SH NAME
naslist \- RADIUS naslist file
.SH DESCRIPTION
naslist \- FreeRADIUS configuration file.
.SH DESCRIPTION
This configuration file is no longer used by the server, and will not
be read by the server. See the "scripts/clients.pl" program for a way
to migrate this file to the new format.
.SH "SEE ALSO"
.BR clients.conf (5)
