.TH radiusd.conf 5 "02 May 2000"
.SH NAME
radiusd.conf \- FreeRADIUS Daemon configuration file
.SH DESCRIPTION
The \fIradiusd.conf\fP file resides in the radius database directory,
by default \fI/etc/raddb\fP.  It defines the global configuration for
the FreeRADIUS server.

At present, the internal format of this file is documented only in the
comments of the distribution version of the file.


.PP
.SH FILES
.I /etc/raddb/radiusd.conf
.SH "SEE ALSO"
.BR radiusd (8) ,
.BR clients (5)
