.TH radiusd.conf 5 "02 May 2000"
.SH NAME
radiusd.conf \- FreeRADIUS Daemon configuration file
.SH DESCRIPTION
The \fIradiusd.conf\fP file resides in the radius database directory,
by default \fI/etc/raddb\fP.  It defines the global configuration for
the FreeRADIUS server.

.SH "FILE FORMAT"
The file consists of sections and attribute-value pairs.  A section
begins with a section name, followed by an open bracket \fI{\fP.  The
section may contain other sections, or attribute-value pairs.  The
section ends with a close bracket \fI}\fP.  Attribute-value pairs are
of the form 'name = value'.

The file is line-based.  That is, each newline-terminated line
represents either a comment, a section name, or a attribute-value
pair.

Any line beginning with a hash (#) is deemed to be a comment, and is
ignored.  Lines containing only whitespace are also ignored.

Variables may reference each other, so long as they have previously
been defined.  The standard shell reference format \fI${name}\fP
is used.

The exact configuration directives are too numerous to list here, so
this manual page documents only the file format.  Please read the
sample configuration file distributed with the server for comments
describing each configuration directive.

.SH EXAMPLES
.PP
.DS
	foo = bar

.DE
Sets variable \fIfoo\fP to value \fIbar\fP.

.DS
	blogs = ${foo}

.DE
Sets variable \fIblogs\fP to the value of variable \fIfoo\fP.

.DS
	my_section {
.br
		baz = bud
.br
	}

.DE
Defines a section named \fImy_section\fP, containing variable
\fIbaz\fP.

.PP
.SH FILES
.I /etc/raddb/radiusd.conf
.SH "SEE ALSO"
.BR radiusd (8) ,
.BR clients (5)

.SH AUTHOR
The FreeRADIUS team.
