.TH rlm_attr_rewrite 5 "3 February 2004" "" "FreeRADIUS Module"
.SH NAME
rlm_attr_rewrite \- FreeRADIUS Module
.SH DESCRIPTION
The \fIrlm_attr_rewrite\fP module provides functionality to rewrite
data in radius packets on the fly.  This can be useful in
authorization and accounting functions.
.PP
The main configuration items to be aware of are:
.IP attribute
The name of the attribute that you want to be rewritten
.IP searchfor
String to be replaced.
.IP searchin
Where to look for the attribute.  Valid values are:
.BR packet,
.BR reply,
.BR proxy,
.BR proxy_reply,
.BR config
.IP replacewith
String to replace "searchfor".
.IP append
Set to yes or no.  If set to yes then the replace string will be
appended to the original string.
.IP ignore_case
Set to yes or no.  Determines whether search will be case insensitive
or case sensitive.
.IP new_attribute
Set to yes or no.  If set to yes, then new attribute will be created
with values from "searchin" and "replacewith".  Other options will be
ignored.
.IP max_matches
Set the max number of attributes to match against.  This is useful if
you need to rewrite the value in multiple Vendor Specific Attributes.
.PP
.SH SECTIONS
.BR authorization,
.BR authentication,
.BR postauthentication,
.BR preaccounting,
.BR accounting,
.BR preproxy,
.BR postproxy
.PP
.SH FILES
.I /etc/raddb/radiusd.conf
.PP
.SH "SEE ALSO"
.BR radiusd (8),
.BR radiusd.conf (5)
.SH AUTHOR
Chris Parker, cparker@segv.org

