



= The Load Virtual Server

The `load` virtual server does load testing.



Use `listen load { ... }` in any virtual server to do load
testing against that server.


This is a valid Packet-Type for the current `namespace`



For now, only 'step' transport is available.



Do load testing in increasing steps.


Filename with input packet.  This is in the
same format as used by `radclient`.



Where the statistics file goes, in CSV format.



How many packets/s to start with.



How many packet/s to end up at.

When the load generator reaches this rate,
it prints the final statistics, and makes
the server exit.



How long we send packets for (in seconds) at each step.



How big of a packet/s step to jump after running each test.



We don't want to overload the server.  If
the server cannot process packets quickly
enough, we will get a backlog of
unprocessed packets.  If the backlog gets
too high, then the load generator will
temporarily stop sending packets.  Once the
backlog is low enough, it will continue.



How many packets to send immediately in
parallel, without waiting for a response.
When a reply is received, a new request may
be sent.



The rest of the recv/send sections are protocol specific, and are
taken from the `namespace`.






== Default Configuration

```
server load {
	namespace = radius
	listen load {
		type = Access-Request
		transport = step
		step {
			filename = ${confdir}/load.txt
			csv = ${confdir}/stats.csv
			start_pps	= 100
			max_pps		= 2000
			duration	= 10
			step		= 200
			max_backlog	= 1000
			parallel	= 25
		}
	}
}
recv Access-Request {
	accept
}
authenticate pap {
	pap
}
send Access-Accept {
	ok
}
send Access-Reject {
	ok
}
}
```
