= Troubleshooting

Troubleshooting is a step-by-step method used to determine the root cause of a problem and the processes how to resolve and test the fix. The goal of this guide is to enable the users to help user resolve the current issue and get FreeRADIUS server back into production.

Some of the more common troubleshooting issues are covered in the xref:ROOT:faq.adoc[FAQ]. The section is divided into the following areas:

* xref:user.adoc[User Management]
* xref:server.adoc[Server Configuration]
* xref:client.adoc[Client Configuration]
* xref:connect_nas.adoc[Connectivity-NAS]
* xref:datastore.adoc[Datastores]

If your server starts up successfully, *save* a copy of the configuration so you always have a "known working" configuration. When the server doesn’t start up, go back and verify the configuration and read the entire debug output.

Follow these recommended steps to troubleshoot your server:

. Make small, discrete changes to the configuration files.

. Start the server in debugging mode by entering the command radiusd -X

. Verify that the results are what you expect

The debug output show the current configuration and relevant information such as:

* Datastores are connected and operating.

* Test packets are accepted by the server.

* The debug output shows that the packets are being processed as you expect.

* The response packets contain the attributes you expect to see.

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
