= LDAP

FreeRADIUS can integrate with an LDAP server to handle authentication, authorization, and accounting tasks. The tutorials that follow are intended for readers who already understand LDAP concepts and terminology. If you are new to LDAP or unsure about how LDAP directories work, review the https://ldap.com/basic-ldap-concepts/[basic concepts] before proceeding. The FreeRADIUS documentation doesn't cover any foundational LDAP topics.

To use LDAP, an existing LDAP server must be and tested using the ldapsearch tool.

[NOTE]
====
In an Microsoft Active Directory environment you should use `rlm_winbind` for
authentication, and `rlm_ldap` for group membership checks as described in
xref:modules/ldap/authorization/index.adoc[authorization] section. The winbind protocol does not support the full range of group checks that is
possible with LDAP.
====

== Sections in this guide

These sections must be completed in order for the examples later
in the tutorial to operate correctly. For additional features and configuration items see the xref:reference:raddb/mods-available/ldap.adoc[mods-available/ldap] page for more details about rlm_ldap module supports.

=== xref:modules/ldap/bootstrap_openldap/index.adoc[Install and Configure OpenLDAP]

In order to use LDAP, there must be an existing LDAP server provisioned with
users, groups, and possibly clients.  We highly recommend using
https://www.openldap.org/[OpenLDAP] for both its flexibility and performance.

If there is not an existing local LDAP server, then it is possible to provision
one using a xref:modules/ldap/bootstrap_openldap/docker.adoc[docker] image, or
alternatively, if you're using a Debian or RHEL based distribution, using the
OpenLDAP LTB https://www.ltb-project.org/documentation/openldap-rpm.html[RPM] or
https://www.ltb-project.org/documentation/openldap-deb.html[DEB] packages.

[TIP]
====
For testing purposes it's recommended to install the LDAP instances on the same
machine (or inter-container network in the case of docker) as the RADIUS server
to avoid any potential networking issues. This recommendation applies equally to high load production environments, or where a high level of redundancy is required.
====

=== xref:modules/ldap/ldapsearch/index.adoc[Test with Ldapsearch]

Once the LDAP server is provisioned and available, test the server using the command-line xref:modules/ldap/ldapsearch/index.adoc[ldapsearch] tool. If the `ldapsearch` tests fail, any LDAP server configuration issues *must* be fixed before proceeding with the FreeRADIUS integration. This step ensures that authentication and data retrieval function correctly when FreeRADIUS queries the LDAP server.

=== xref:modules/ldap/base_configuration/index.adoc[Base Configuration]

Once the xref:modules/ldap/ldapsearch/index.adoc[ldapsearch] validation tests pass, the next step is to xref:modules/ldap/base_configuration/index.adoc[Configure the LDAP Module]. All basic settings required for all functions of the LDAP module are detailed here.

OpenLDAP configuration examples show how to install appropriate schemas and
populate the server with test data will be provided in each section.

=== xref:modules/ldap/authorization/index.adoc[Configure Authorization]

Covers authorization by group, enabling/disabling accounts using attributes,
LDAP attribute to FreeRADIUS attribute mappings, and LDAP profiles.

=== xref:modules/ldap/authentication.adoc[Configure Authentication]

Examples of configuring different methods of LDAP based authentication
(search, bind, edir).

=== xref:modules/ldap/accounting.adoc[Configure Accounting]

Examples of updating objects in LDAP after authentication completes, or when
accounting data is received.

// Copyright (C) 2025 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
