TARGET      	:= misc_tests$(E)
SOURCES     	:= misc_tests.c

TGT_LDLIBS  	:= $(LIBS) $(GPERFTOOLS_LIBS)
TGT_LDFLAGS 	:= $(LDFLAGS) $(GPERFTOOLS_LDFLAGS)
TGT_PREREQS 	:= $(LIBFREERADIUS_UTIL)

TGT_INSTALLDIR	:=
