/*

acconfig.h - template used by autoheader to create config.h.in
config.h.in - used by autoconf to create config.h
config.h - created by autoconf; contains defines generated by autoconf

*/

@TOP@

/* Do we have the crypt function ? */
#undef HAVE_CRYPT

/* Do we have shadow support? */
#undef HAVE_GETSPNAM

/* Define if you need preceding underscores in dynamic library linking */
#undef MODULE_NEED_USCORE

/* Do we want to compile in DBM support? */
#undef WITH_DBM

/* Do we want to compile in NDBM support? */
#undef WITH_NDBM

/* Include Ascend hacks */
#undef WITH_ASCEND_HACK

/* Set Ascend Channels Per Line to N */
#undef ASCEND_CHANNELS_PER_LINE

/* Include NT Domain hack */
#undef WITH_NTDOMAIN_HACK

/* Include Specialix Jetstream hacks */
#undef WITH_SPECIALIX_JETSTREAM_HACK

/* Make dictionary case-independant */
#undef WITH_DICT_NOCASE

/* Use USR-style vendor specific attributes */
#undef ATTRIB_NMC

/* Include support for Ascend binary filter attributes */
#undef ASCEND_BINARY

/* socklen_t is generally 'int' on systems which don't use it */
#undef socklen_t

/* uint8_t should be the canonical 'octet' for network traffic */
#undef uint8_t

/* uint32_t should be the canonical 'network integer' */
#undef uint32_t

/* Define if prototype for strncasecmp needed */
#undef NEED_DECLARATION_STRNCASECMP

/* Define if prototype for strcasecmp needed */
#undef NEED_DECLARATION_STRCASECMP

/* Define if prototype for inet_aton needed */
#undef NEED_DECLARATION_INET_ATON

/* Define if prototype for gethostname needed */
#undef NEED_DECLARATION_GETHOSTNAME

/* Define if prototype for setlinebuf needed */
#undef NEED_DECLARATION_SETLINEBUF

/* Define if prototype for getusershell needed */
#undef NEED_DECLARATION_GETUSERSHELL

/* Define if prototype for endusershell needed */
#undef NEED_DECLARATION_ENDUSERSHELL

/* use a pool of threads to handle requests, instead of spawning threads? */
#undef WITH_THREAD_POOL

/* Include SNMP subagent */
#undef WITH_SNMP

/* Include user collision code*/
#undef WITH_USERCOLLIDE

/* Define if you have the <snmp.h> header file.  */
#undef HAVE_SNMP_H

/* Define if you have the <ucd_snmp/snmp.h> header file.  */
#undef HAVE_UCD_SNMP_SNMP_H

/* Define if you have the <snmp_impl.h> header file.  */
#undef HAVE_SNMP_IMPL_H

/* Define if you have the <ucd_snmp/snmp_impl.h> header file.  */
#undef HAVE_UCD_SNMP_SNMP_IMPL_H

/* Define if you have the <asn1.h> header file.  */
#undef HAVE_ASN1_H

/* Define if you have the <ucd_snmp/asn1.h> header file.  */
#undef HAVE_UCD_SNMP_ASN1_H

/* define if you have the <libpq_fe.h> header file.  */
#undef HAVE_LIBPQ_FE_H

/* define if you have the <postgres.h> header file.  */
#undef HAVE_POSTGRES_H

/* define this if we have REG_EXTENDED (from <regex.h>) */
#undef HAVE_REG_EXTENDED

/* define this if you have the <mysql.h> header file */
#undef HAVE_MYSQL_H

/* define this if you have the <isql.h> header file */
#undef HAVE_ISQL_H

/* define this if you have the <oci.h> header file */
#undef HAVE_OCI_H


@BOTTOM@

#ifndef HAVE_SNPRINTF
#define HAVE_LOCAL_SNPRINTF
#define snprintf lrad_snprintf
#endif

#ifndef HAVE_VSNPRINTF
#define HAVE_LOCAL_SNPRINTF
#define vsnprintf lrad_vsnprintf
#endif
