/*

acconfig.h - template used by autoheader to create config.h.in
config.h.in - used by autoconf to create config.h
config.h - created by autoconf; contains defines generated by autoconf

*/

@TOP@

/* Do we have the crypt function ? */
#undef HAVE_CRYPT

/* Do we have shadow support? */
#undef HAVE_GETSPNAM

/* Do we have socklen_t? */
#undef HAVE_SOCKLEN_T

/* Define if you have the DLOPEN function.  */
#undef HAVE_DLOPEN

/* Do we want to compile in DBM support? */
#undef WITH_DBM

/* Do we want to compile in NDBM support? */
#undef WITH_NDBM

/* Include Ascend hacks */
#undef WITH_ASCEND_HACK

/* Set Ascend Channels Per Line to N */
#undef ASCEND_CHANNELS_PER_LINE

/* Include NT Domain hack */
#undef WITH_NTDOMAIN_HACK

/* Include Specialix Jetstream hacks */
#undef WITH_SPECIALIX_JETSTREAM_HACK

/* Make dictionary case-independant */
#undef WITH_DICT_NOCASE

/* Make dictionary case-independant */
#undef WITH_DICT_NOCASE
