/*

acconfig.h - template used by autoheader to create config.h.in
config.h.in - used by autoconf to create config.h
config.h - created by autoconf; contains defines generated by autoconf

*/

@TOP@

/* Do we have the crypt function ? */
#undef HAVE_CRYPT

/* Do we have shadow support? */
#undef HAVE_GETSPNAM

/* Do we have socklen_t? */
#undef HAVE_SOCKLEN_T

/* Define if you have the DLOPEN function.  */
#undef HAVE_DLOPEN

/* Define if you need preceding underscores in dynamic library linking */
#undef MODULE_NEED_USCORE

/* Do we want to compile in DBM support? */
#undef WITH_DBM

/* Do we want to compile in NDBM support? */
#undef WITH_NDBM

/* Include Ascend hacks */
#undef WITH_ASCEND_HACK

/* Set Ascend Channels Per Line to N */
#undef ASCEND_CHANNELS_PER_LINE

/* Include NT Domain hack */
#undef WITH_NTDOMAIN_HACK

/* Include Specialix Jetstream hacks */
#undef WITH_SPECIALIX_JETSTREAM_HACK

/* Make dictionary case-independant */
#undef WITH_DICT_NOCASE

/* Use USR-style vendor specific attributes */
#undef ATTRIB_NMC

/* Include support for Ascend binary filter attributes */
#undef ASCEND_BINARY

/* uint8_t should be the canonical 'octet' for network traffic */
#undef uint8_t

/* uint32_t should be the canonical 'network integer' */
#undef uint32_t

@BOTTOM@

/* Define if prototype for strncasecmp needed */
#undef NEED_DECLARATION_STRNCASECMP

/* Define if prototype for strcasecmp needed */
#undef NEED_DECLARATION_STRCASECMP

/* Define if prototype for inet_aton needed */
#undef NEED_DECLARATION_INET_ATON

/* Define if prototype for gethostname needed */
#undef NEED_DECLARATION_GETHOSTNAME

/* Define if prototype for setlinebuf needed */
#undef NEED_DECLARATION_SETLINEBUF

/* Define if prototype for getusershell needed */
#undef NEED_DECLARATION_GETUSERSHELL

/* Define if prototype for endusershell needed */
#undef NEED_DECLARATION_ENDUSERSHELL


