site:
  title: The FreeRADIUS project - Documentation
  url: https://www.freeradius.org/docs
content:
  sources:
  - url: .
    branches: HEAD
    start_path: doc/antora
asciidoc:
  attributes:
    attribute-missing: skip
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
output:
  clean: true
  dir: ./build/docsite
