# Generated automatically from Makefile.in by configure.
TARGET      = rlm_pap
SRCS        = rlm_pap.c
HEADERS     =
RLM_CFLAGS  = 
RLM_LIBS    = 
RLM_INSTALL =

include ../rules.mak

$(STATIC_OBJS): $(HEADERS)

$(DYNAMIC_OBJS): $(HEADERS)
