#! /bin/sh
#
#  This script builds FreeRADIUS in a docker environment
#  using the Dockerfiles in this directory.
#
#  Example usage: ./dockerbuild build-debian9
#

DIR="$1"

[ -z "$DIR" ] && echo "Syntax: $0 <dir>" && exit 1
[ ! -d "$DIR" ] && echo "Directory '$DIR' does not exist" && exit 1

OSNAME=$(echo "$DIR" | sed -e 's/^build-//')

[ ! -r "$DIR/Dockerfile.deps" ] && echo "'$DIR/Dockerfile.deps' does not exist" && exit 1
echo Building $OSNAME source and dependency image
docker build "$DIR" -f "$DIR/Dockerfile.deps" -t freeradius/$OSNAME-deps

if [ -r "$DIR/Dockerfile.jenkins" ]; then
	echo Building $OSNAME jenkins image
	docker build "$DIR" -f "$DIR/Dockerfile.jenkins" -t freeradius/$OSNAME-jenkins
fi

if [ -r "$DIR/Dockerfile" ]; then
	echo Building $OSNAME FreeRADIUS image
	docker build "$DIR" -t freeradius/$OSNAME
fi

