= Startup Text

This page walks through the *startup* text of FreeRADIUS version 4,
the output `radiusd -X` prints while it reads its configuration and
gets ready to accept packets.  It is the first half of a `radiusd -X`
session; the second half is described in
xref:debugging/processing.adoc[Processing Packets].

We start the server with *`-X`*.  This option gives us the best
combination of useful output, and readable output.  Adding more `-x`
gives *more complex output*, not *more useful output*.

----
$ radiusd -X 2>&1 | tee debugfile
----

The server prints out the version number, copyright, and license
information:

----
FreeRADIUS Version 4.0.0
Copyright 1999-2026 The FreeRADIUS server project and contributors
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE
You may redistribute copies of FreeRADIUS under the terms of the
GNU General Public License
For more information about these matters, see the file named COPYRIGHT

FreeRADIUS is developed, maintained, and supported by InkBridge Networks.
For commercial support, please email sales@inkbridgenetworks.com
https://inkbridgenetworks.com/
----

Next, it prints out messages relating to debuggers (e.g. gdb).  These
messages are intended for developers, and can generally be ignored by
everyone else.

----
Getting debug state failed: ptrace capability not set.  If debugger detection is required run as root or: setcap cap_sys_ptrace+ep <path_to_radiusd>
----

== Read the configuration files

The next block of messages is about the configuration files.  The
server prints out the name of each configuration file it loads.

This output lets you check that the server is loading the files which
you think it's loading.  One common issue is that people install
multiple versions of the server, and then edit one file while the
server is loading a different one.  Reading the debug output will let
you verify that you're editing the right file.

----
Starting - reading configuration files ...
----

It then reads the dictionaries.  In v4 the protocol dictionaries are
loaded automatically from `${prefix}/share/freeradius/`, so the local
`raddb/dictionary` no longer needs to `$INCLUDE` them.  The protocol
dictionaries are not printed individually, but the local dictionary is
logged as it is included:

----
Including dictionary file "/etc/raddb/dictionary"
----

Next it loads the main `radiusd.conf` file, and the associated
`clients.conf`.  Note that there is no `proxy.conf` in v4: proxying is
now done by the `radius` module, so there are no `realm`,
`home_server` or `home_server_pool` files to load.

----
including configuration file /etc/raddb/radiusd.conf
including configuration file /etc/raddb/clients.conf
----

It now loads all of the modules.  The module configuration is usually
stored in `mods-enabled/`, with one module configuration per file in
that directory.

Sometimes the module you're using does not seem to be loaded or used.
In that case, you should check this section to see that the file is
loaded.

----
Including files in directory "/etc/raddb/mods-enabled/"
including configuration file /etc/raddb/mods-enabled/always
including configuration file /etc/raddb/mods-enabled/attr_filter
including configuration file /etc/raddb/mods-enabled/cache_eap
including configuration file /etc/raddb/mods-enabled/chap
including configuration file /etc/raddb/mods-enabled/client
including configuration file /etc/raddb/mods-enabled/delay
including configuration file /etc/raddb/mods-enabled/detail
including configuration file /etc/raddb/mods-enabled/detail.log
including configuration file /etc/raddb/mods-enabled/digest
including configuration file /etc/raddb/mods-enabled/eap
including configuration file /etc/raddb/mods-enabled/eap_inner
including configuration file /etc/raddb/mods-enabled/echo
including configuration file /etc/raddb/mods-enabled/escape
including configuration file /etc/raddb/mods-enabled/exec
including configuration file /etc/raddb/mods-enabled/files
including configuration file /etc/raddb/mods-enabled/linelog
including configuration file /etc/raddb/mods-enabled/mschap
including configuration file /etc/raddb/mods-enabled/ntlm_auth
including configuration file /etc/raddb/mods-enabled/pap
including configuration file /etc/raddb/mods-enabled/passwd
including configuration file /etc/raddb/mods-enabled/stats
including configuration file /etc/raddb/mods-enabled/unix
including configuration file /etc/raddb/mods-enabled/unpack
including configuration file /etc/raddb/mods-enabled/utf8
----

Next, some policies are loaded.  These policies are ones which the
server uses (for example) to canonicalize user names, and to do things
like attribute re-writes, sanity checks, etc.  The virtual servers in
`sites-enabled/` are loaded at the same time.

----
Including files in directory "/etc/raddb/policy.d/"
including configuration file /etc/raddb/policy.d/accounting
including configuration file /etc/raddb/policy.d/canonicalisation
including configuration file /etc/raddb/policy.d/control
including configuration file /etc/raddb/policy.d/cui
including configuration file /etc/raddb/policy.d/debug
including configuration file /etc/raddb/policy.d/dhcp
including configuration file /etc/raddb/policy.d/eap
including configuration file /etc/raddb/policy.d/filter
including configuration file /etc/raddb/policy.d/operator-name
including configuration file /etc/raddb/policy.d/time
including configuration file /etc/raddb/policy.d/vendor
Including files in directory "/etc/raddb/sites-enabled/"
including configuration file /etc/raddb/sites-enabled/default
including configuration file /etc/raddb/sites-enabled/inner-tunnel
including configuration file /etc/raddb/sites-enabled/proxy
----

== Server configuration

Once all of the configuration files are loaded, the server prints out
the configuration it is parsing.  Note that it *only prints out what
it is using*.  I.e. you can put `foo = bar` into `radiusd.conf`, and
the server will load it, but will not print it out in the debug
output.

The result is that if you set a configuration item, *it will be
printed out in the debug output*.  You should verify that this is the
case, especially if it looks like the server is not using the setting
you edited.  If the configuration item does not appear in the debug
output, *then the server is not using it.*

This is the "main" server configuration, which shows the name of the
server and the directories it is using:

----
main {
	name = "radiusd"
	prefix = "/usr/local"
	localstatedir = "/usr/local/var"
	sbindir = "/usr/local/sbin"
	logdir = "/usr/local/var/log/radius"
	run_dir = "/usr/local/var/run/radiusd"
	libdir = "/usr/local/lib"
	radacctdir = "/usr/local/var/log/radius/radacct"
----

Next we have some generic configuration settings which don't belong
anywhere else.

----
	hostname_lookups = yes
	max_request_time = 30
	cleanup_delay = 5
	max_requests = 16384
	pidfile = "/usr/local/var/run/radiusd/radiusd.pid"
	debug_level = 0
----

And the logging configuration.  In v4 the `log` section has a
`suppress_secrets` option, which is `yes` by default.  This is why
secret values such as `User-Password` are printed as `<<< secret >>>`
in the packet processing output, so that debug logs can be shared
safely.

----
	log {
		destination = "file"
		file = "/usr/local/var/log/radius/radius.log"
		syslog_facility = "daemon"
		colourise = yes
		suppress_secrets = yes
	}
----

The security settings.

----
	security {
		max_attributes = 200
		allow_vulnerable_openssl = no
		allow_core_dumps = yes
	}
}
----

At this point, the server is well on it's way to running.

== Clients

It now loads the individual clients defined in `clients.conf`:

----
client localhost {
	ipaddr = 127.0.0.1
	require_message_authenticator = auto
	secret = <<< secret >>>
	proto = "*"
	limit {
		max_connections = 16
		lifetime = 0
		idle_timeout = 30
	}
}
client localhost_ipv6 {
	ipv6addr = ::1
	require_message_authenticator = auto
	secret = <<< secret >>>
	limit {
		max_connections = 16
		lifetime = 0
		idle_timeout = 30
	}
}
----

== Modules

When the server read the module configuration files above (from
`mods-enabled`), that meant just reading the contents of the file.  It
is now ready to load the dynamic library which reads that
configuration, and which parses the configuration to determine what to
do with it.

Each module will print out it's configuration, along with any errors
or warnings it sees when it is loading itself.

As the `pap` module's dynamic library is loaded, the server prints the
name of the library:

----
Loaded module rlm_pap
----

It then prints out the configuration that is used by the `pap` module:

----
pap {
	normalise = yes
}
----

When you are editing a module configuration, it is good to check the
debug output for that module, to see:

* Was the module loaded?
* Is it using the file you edited?
* Are the configuration changes you made showing up in the debug
  output?

The `files` module is the one that loads the `users` file:

----
Loaded module rlm_files
files {
	filename = "/etc/raddb/mods-config/files/authorize"
}
----

The server loads a large number of modules, so we will omit the rest
of them here.

Once all of the modules have been loaded and their configuration
parsed, the server instantiates them.  It prints a header for the
module list (the `rlm` list holds the normal modules), followed by one
line per module being instantiated:

----
#### Instantiating rlm modules ####
Instantiating rlm_pap "pap"
Instantiating rlm_files "files"
----

== Virtual Servers

Next, it loads "virtual servers".  In v4, every virtual server starts
with a `namespace` that selects the protocol dictionary (for example
`radius`), and the processing sections are named after the packet
types they handle (`recv Access-Request`, `send Access-Accept`, and so
on).

It prints out the server name, then compiles each processing section.
The `authenticate` sections are named after the `Auth-Type` they
handle, so compiling them is what creates the `Auth-Type` values used
later during packet processing.

----
Compiling policies in server default { ... }
Compiling policies in - recv Access-Request {...}
Compiling policies in - authenticate pap {...}
Compiling policies in - authenticate chap {...}
Compiling policies in - authenticate mschap {...}
Compiling policies in - authenticate digest {...}
Compiling policies in - authenticate eap {...}
Compiling policies in - send Access-Challenge {...}
Compiling policies in - send Access-Accept {...}
Compiling policies in - send Access-Reject {...}
Compiling policies in - recv Accounting-Request {...}
Compiling policies in - send Accounting-Response {...}
----

It then compiles the `inner-tunnel` virtual server, which handles the
"inner" portion of tunnelled EAP methods such as PEAP and TTLS.

----
Compiling policies in server inner-tunnel { ... }
Compiling policies in - recv Access-Request {...}
Compiling policies in - authenticate pap {...}
Compiling policies in - authenticate chap {...}
Compiling policies in - authenticate mschap {...}
Compiling policies in - send Access-Accept {...}
Compiling policies in - send Access-Reject {...}
----

Finally it compiles the `proxy` virtual server.  This is one of the
three sites enabled by default (`default`, `inner-tunnel`, and
`proxy`).  It has no `listen` section of its own; it is used to proxy
requests outbound via the `radius` module, selected by setting
`Auth-Type := proxy`.

----
Compiling policies in server proxy { ... }
Compiling policies in - recv Access-Request {...}
Compiling policies in - authenticate proxy {...}
Compiling policies in - send Access-Accept {...}
Compiling policies in - send Access-Reject {...}
Compiling policies in - send Access-Challenge {...}
Compiling policies in - recv Accounting-Request {...}
Compiling policies in - send Accounting-Response {...}
----

In some situations, it tells you where the configuration can be
simplified.

----
Skipping contents of 'if' as it is always 'false' -- /etc/raddb/sites-enabled/inner-tunnel:335
----

== Listen sections

After loading all of the virtual servers, it then opens the various
network sockets used to read and write packets.  In v4 the `listen`
sections live inside the virtual server, are named after the type of
packet they accept, and put the transport configuration (address,
port) inside a transport subsection such as `udp { ... }`.

The server prints a header for this phase, followed by the
configuration for the listen sections.

----
#### Instantiating listeners ####
listen authentication {
	type = Access-Request
	type = Status-Server
	transport = udp
	udp {
		ipaddr = *
		port = 1812
	}
}
listen accounting {
	type = Accounting-Request
	transport = udp
	udp {
		ipaddr = *
		port = 1813
	}
}
----

After reading all of the configuration, it opens the interfaces, and
prints out a list of IP addresses and ports which it is using.  Note
that each socket is reported as bound to a *virtual server*.

----
#### Opening listener interfaces ####
Listening on auth address * port 1812 bound to virtual server default
Listening on acct address * port 1813 bound to virtual server default
Listening on auth address 127.0.0.1 port 18120 bound to virtual server inner-tunnel
----

And we finally get to this line.

----
Ready to process requests
----

Once this has been printed, the debug output changes to packet
processing, which is described in
xref:debugging/processing.adoc[Processing Packets].

If *nothing* is ever printed after this line, then the server is not
receiving any packets.  No amount of changing the server configuration
will solve that problem.  Instead, you must fix the firewall, SeLinux
configuration, network routing, etc. so that the OS delivers RADIUS
packets to the server.

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
