= DHCP Server

This guide describes how FreeRADIUS can be used in place of ISC DHCP or ISC Kea
to provide a significantly more performant and flexible DHCP server.

The suggested configuration is likely familiar to anyone who’s used DHCP with common features of other DHCP server software.

The modular design of FreeRADIUS means that there is no one "right" way to
implement the DHCP service. FreeRADIUS allows you to put together a "mix and
match" approach.

For example you can manage the leases in an SQL database. You might then hard
code certain DHCP reply parameters within configuration and then look up
additional parameters using a datastore such as:

  * a local file such as a structured text file or an SQLite database
  * an organizational LDAP directory
  * an SQL or "no SQL" database
  * a remote endpoint such as a RESTful HTTP API

The policy language and modular configuration of FreeRADIUS is sufficiently
powerful and that almost any aspect of the server's behaviour can be customized
to implement even the most sophisticated DHCP configurations.

== Sections in this guide

This guide is organized into four sections and we recommend to review each one in the following order:

1. xref:protocols/dhcp/prepare.adoc[Preparation]
2. xref:protocols/dhcp/enable.adoc[Enable the DHCP service]
3. xref:protocols/dhcp/test.adoc[Test the DHCP service]
4. xref:protocols/dhcp/policy.adoc[Define the DHCP policy]

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
