.TH RLM_DBM_CAT 8
.SH NAME
rlm_dbm_cat - list contents of radius database
.SH SYNOPSIS
.B rlm_dbm_cat
.RB [ \-f
.IR file ]
.RB [ \-w ]
.RB [ \-i
.IR number ]
.RB [ \-l
.IR number ]
.RB [ \-v ]
[\fIusername ...\fP]

.SH DESCRIPTION
\fBrlm_dbm_cat\fP simply lists the definition(s) of the username(s)
or group name(s), or the entire database.
.PP

.SH OPTIONS

.IP \-f\ \fIfilename\fP
The file name of the database to list.
.IP \-w
Long lines should be wrapped
.IP \-i\ \fInumber\fP
Set the left margin then wrapped.
.IP \-l\ \fInumber\fP
How long line should be to be wrapped (wrap threshold)
.IP \-v
Print the version number and exit.

.SH SEE ALSO
radiusd(8)
.SH AUTHORS
.TP
Author:
Andrei Koulik <rlm_dbm@agk.nnov.ru>
.TP
Documentation:
Bjørn Nordbø  <bn@nextra.com>
