= The case Statement

.Syntax
[source,unlang]
----
case [ <match> ] {
    [ statements ]
}
----

The `case` statement is used to match data inside of a
xref:unlang/switch.adoc[switch] statement.  The `case` statement cannot be used
outside of a xref:unlang/switch.adoc[switch] statement.

The _<match>_ text *must* be static.  That is, the _<match>_ text
cannot be an attribute expansion, or an `xlat`
xref:xlat/index.adoc[string].

The keyword `default` can be used to specify the default action to
take inside of a xref:unlang/switch.adoc[switch] statement.  The older
syntax of using `case { ... }` is deprecated, and will be removed un a
future release.

It is possible to xref:unlang/break.adoc[break] out of `case`
statement.  Any xref:unlang/break.adoc[break] in a `case` statement
will cause the interpreter to exit both the current `case` statement,
and also the parent xref:unlang/switch.adoc[switch] statement.

.Example
[source,unlang]
----
switch User-Name {
    case "bob" {
        reject
    }

    case Filter-Id {
        reject
    }

    default {
        ok
    }
}
----

The last entry in a `case` section can also be an xref:unlang/actions.adoc[actions] subsection.

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
