= The foreach Statement

.Syntax
[source,unlang]
----
foreach [<data-type>] <key-name> (<attribute-reference>) {
    [ statements ]
}
----

The `foreach` statement loops over a set of attributes as given by
`<attribute-reference>`.  The loop can be exited early by using the
xref:unlang/break.adoc[break] keyword.

There is no limit on how many `foreach` statements can be nested.

<data-type>::

An optional data tye for the `<key-name>` local variable.  When looping over attributes, the data type can be omitted.  The data type of the local variable is then taken from the attribute reference.

<key-name>::

The name of the local variable which is used as the name of key when iterating over the attributes.

The local variable is created automatically when the `foreach` loop is entered, and is deleted automatically when the `foreach` loop exits.

The `<key-name>` can be modified during the course of the `foreach` loop.  Modifications to the variable are copied back to the referenced attribute when the loop is done.  See below for an example.

The only limitation on the `<key-name>` is that it must be unique.

<attribute-reference>::

The xref:unlang/attr.adoc[attribute reference] which will will be looped
over.  The reference can be to one attribute, to an array, a child, or
be a subset of attributes.

== Modifying Loop variables

An attribute which is a "leaf" data type (e.g. `uint32`, and not
`tlv`) will be automatically copied back to the original attribute at
the end of each iteration of the `foreach` loop.  That is, the
original attribute will still exist, and will be unmodified, during
the execution of the loop.

.Example of modifying values
[source,unlang]
----
&Tmp-Integer-0 := { 1, 3, 5, 11 }

foreach self (&Tmp-Integer-0) {
	&self += 19
}
----

Once the loop has finished , the `&Tmp-Integer-0` attribute will have the following set of values.

[source,unlang]
----
&Tmp-Integer-0 := { 20, 22, 24, 30 }
----

.Pseudocode for variable modification
----
loop over each i in attribute[0..n]
    copy attribute[i] to the key variable, or cast the attribute to the destination type

    run loop body

    if data type of attribute matches the data type of the key
        copy the key variable back to attribute[i]
----

=== Structural Data Types

It is possible to loop over the children of a structural data type, as given in the example below.  Since the loop is over the child (i.e. leaf) attributes, the values are copied back.

In this example, we have to explicitly give a data type `string`.  The data type is needed because there may be multiple children of the `TLV-Thing` attribute, and the children may not all have the same data type.

.Example of Looping over children of a structural type.
[source,unlang]
----
foreach string child (&TLV-Thing.[*]) {
	&out += &child
	&out += " "
}
----


When using `foreach` to loop over multiple structural data types, the values can be
examined, but cannot be changed.  This is a limitation of the current interpreter, and may be changed in the future.

.Example of Looping over children of a structural type.
[source,unlang]
----
foreach thing (&Tmp-TLV-0[*]) {
	&out += &thing.c
	&out += " "
}
----

This example can read the child attribute `c`, but cannot modify it.


// Copyright (C) 2024 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
