= The load-balance Statement

.Syntax
[source,unlang]
----
load-balance [ <key> ] {
    [ statements ]
}
----

The `load-balance` section is similar to the `redundant` section
except that only one module in the subsection is ever called.

In general, the
xref:unlang/redundant-load-balance.adoc[redundant-load-balance] statement is
more useful than this one.

<key>:: An attribute reference or expansion which will be hashed in
order to select the statement to execute.
+
The hash will be used to pick a particular statement within the
`load-balance` section.  This "keyed" load-balance can be used to
deterministically shard requests across multiple modules.
+
When the `<key>` field is omitted, the module is chosen randomly, in a
"load balanced" manner.

[ statements ]:: One or more `unlang` commands.  Only one of the
statements is executed.

.Examples

[source,unlang]
----
load-balance &User-Name {
    sql1
    sql2
}
----

// Copyright (C) 2020 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
