= The switch Statement

.Syntax
[source,unlang]
----
switch <expansion> {
    case <match-1> {
        [ statements-1 ]
    }
    case <match-2> {
        [ statements-2 ]
    }
    default {
        [ statements-3 ]
    }
}
----

A `switch` statement causes the server to evaluate _expansion_, which
can be an xref:unlang/attr.adoc[&Attribute-Name] or
xref:condition/operands.adoc[data].  The result is compared against _match-1_
and _match-2_ to find a match. If no string matches, then the server
looks for the default xref:unlang/case.adoc[case] statement, which has no
associated match.

The matching is done via equality.  The `switch` statement is mostly
syntactic sugar and is used to simplify the visual form of the
configuration.  It is mostly equivalent to the following use of
xref:unlang/if.adoc[if] statements:

.Nearly equivalent syntax
[source,unlang]
----
if (<expansion> == <match-1>) {
    [ statements-1 ]
}
elsif (<expansion> == <match-2>) {
    [ statements-2 ]
}
else {
    [ statements-3 ]
}
----

The main difference between the two forms is that for a `switch`
statement, the _expansion_ is evaluated only once.  For the equivalent
xref:unlang/if.adoc[if] statement, the _expansion_ is evaluated again for every
xref:unlang/if.adoc[if].

If a matching xref:unlang/case.adoc[case] is found, the statements within
that xref:unlang/case.adoc[case] are evaluated. If no matching
xref:unlang/case.adoc[case] is found, the `default` section is evaluated. The
`default` section must not have any _match_ text.  If there is no
`default`, then the `switch` statement behaves as if the `default`
section was empty.

== Efficiency and Data Types

The `switch` keyword will automatically choose an efficient
representation for the set of xref:unlang/case.adoc[case] statements,
based on the data type of the _match_ text.  For `string` and `octets`
data, the xref:unlang/case.adoc[case] statements are place in a binary
tree.  This tree permits `O(log(N))` lookups, so that it is possible
to use `switch` statements which contain tens of thousands of
xref:unlang/case.adoc[case] statements with minimal performance
penalty.

For IP address data types (`ipv4addr`, `ipv6addr`, `ipv4prefix`, and
`ipv6prefix`), the xref:unlang/case.adoc[case] statements are placed
in a Patricia Trie.  The Patricia Trie allows for an IP address to
match exactly, or to match a particular network.  Multiple networks
can be given, including nested networks, so long as there are no
duplicates.  The Patricia Trie also allows for efficient lookups,
which in practice are also `O(lg(N))` in the number of entries.

Other data types are placed into a hash table.

== Limitations

The _match_ text for the xref:unlang/case.adoc[case] statement _must_
be of type xref:type/index.adoc[data].  That is, the "thing to match"
cannot be an attribute, an SQL query, or any other dynamic expansion.

Duplicate xref:unlang/case.adoc[case] statements are forbidden.

No statement other than xref:unlang/case.adoc[case] can appear in a
`switch` statement, and the xref:unlang/case.adoc[case] statement
cannot appear outside of a `switch` statement.

For compatibility with version 3, and empty `case` statement can also
be used instead of `default`.  This compatibility will be removed in a
future release.

== Examples

.Switch over a User-Name
[source,unlang]
----
switch &User-Name {
    case "bob" {
        reject
    }

    default {
        ok
    }
}
----

.Switch over IP prefixes
[source,unlang]
----
switch &Framed-IP-Address {
    case 192.168/16 {
        accept
    }

    case 192.168.2.0/24 {
        reject
    }

    default {
        ok
    }
}
----

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
