= The timeout Statement

.Syntax
[source,unlang]
----
timeout <value> {
    [ statements ]
}
----

.Description
The `timeout` statement limits the total time which a section can use
to process a particular request.  If the request takes more than the
given time, it returns `fail`.

The _<value>_ text can be a number, or a dynamic expansion, or an
attribute reference.  The contents of _<value>_ are interpreted as a
`time_delta`, with default scale in seconds.

The time scale can be changed by appending `s`, `us`, `ms`, `ns`, etc. as
with all uses of `time_delta` values.

.Example
[source,unlang]
----
timeout 1ms {
    foo
    bar
}
----

== Timeout with catch

In the following example, the configuration allows the `sql` module to
run for `4` seconds.  If the `sql` module takes more than `4` seconds
to return, _or_ if the `sql` module fails, then the `detail` module is
called.

.Example using catch
[source,unlang]
----
try {
    timeout 4s {
        sql
    }
}
catch timeout {
    detail
}
----

== Timeout with redundant

The `timeout` can also be used inside of a
xref:unlang/redundant.adoc[redundant] block.  This example has
_almost_ the same behaviour as above.  The difference here is that the
`detail` file here is run on when _either_ the `sql` module fails, or
the timeout is reached.

Whether you choose to use a xref:unlang/redundant.adoc[redundant] or a
xref:unlang/catch.adoc[catch] block after the `timeout` depends on
your local requirements.

.Example using redundant
[source,unlang]
----
redundant
    timeout 4s {
        sql
    }

    detail
}
----

// Copyright (C) 2025 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
