= The update Statement

The `update` statement is deprecated.  It may work, but it will be
removed in a future release.  The `update` statement does not support
the data types of `group` and `struct`.

All new configuration should use the new xref:unlang/edit.adoc[edit]
syntax.  It is more flexible and more powerful than `update` sections.

This page exists only document how the old-style `update` sections can
be converted to the new syntax.

The most important conceptual change is that the
xref:unlang/edit.adoc[edit] syntax separates list assignments from
value assignments.  Where the `update` sections always modified a list
by adding or deleting attributes, the new syntax allows for list
updates _or_ updates to an attributes value.  Be careful not to get
the two uses mixed up, otherwise the result will not be what you
expect.

The second conceptual change is that attribute creation is separate
from applying attributes to a list.  For example, the `+=` operator
used to both create an attribute, and then append that attribute to a
list.  The new edit syntax separates attribute creation from list
modification.

== Conversions

There are a larger number of operators using for both the old `update`
section and the xref:unlang/edit.adoc[edit] syntax.  We explain in
detail how the configuration can be converted from one form to another.

=== Appending to a list: +=

The following example creates four attributes, and appends them to the
`request` list.

[source,unlang]
----
update request {
	&User-Name += "foo"
	&Filter-Id += "bar"
	&NAS-IP-Address += 127.0.0.1
	&NAS-Port += 5
}
----

This example should be converted to the following syntax:

[source,unlang]
----
&request += {
	&User-Name = "foo"
	&Filter-Id = "bar"
	&NAS-IP-Address = 127.0.0.1
	&NAS-Por = 5
}
----

This configuration can be interpreted as "edit the `&request` list,
but appending (`+=`) another list to it.  The list being appended
contains four attributes".

Note that the operators on the right-hand side list are all `=`.  The
`=` operator is used here because we are simply _creating_ the
right-hand side list, not _modifying_ it.

=== Over-writing attributes in a list: :=

The following example over-writes the values for two attributes in the
`request` list.

[source,unlang]
----
update request {
	&User-Name := "foo"
	&Filter-Id := "bar"
}
----

The simplest conversion here is to keep the `:=` operator, and to just
assign the attributes in place, with a list qualifier.

[source,unlang]
----
&request.User-Name := "foo"
&request.Filter-Id := "bar"
----

Note that the following conversion is _not_ correct, as it will
overwrite the _entire_ request list.  Once the overwrite has been
done, the `request` list will contain only the two attributes being
assigned to it.

[source,unlang]
----
&request := {
	&User-Name = "foo"
	&Filter-Id = "bar"
}
----
=== Conditionally Over-writing attributes in a list: =

The following example conditionally over-writes the values for two attributes in the
`request` list.

[source,unlang]
----
update request {
	&User-Name = "foo"
	&Filter-Id = "bar"
}
----

The simplest conversion here is to keep the `=` operator, and to just
assign the attributes in place, with a list qualifier.

[source,unlang]
----
&request.User-Name = "foo"
&request.Filter-Id = "bar"
----

=== Removing Attributes from a list: !*

The following example removes all `&User-Name` attributes from the `request` list.

[source,unlang]
----
update request {
	&User-Name !* ANY
}
----

The conversion is to use the `-=` operator:

[source,unlang]
----
&request -= &User-Name
----

== More Complex Conversions

It is extremely difficult to document every possible conversion when
using a mix of operators in an `update` section.  The above examples
should be sufficient for most common cases.

Our recommendation is that if an `update` section contains multiple
different operators, it should be split into multiple assignments.
That is, do not try to convert the entire `update` section as-is.
Instead, separate the `update` section into multiple `update`
sections, one for each operator.  Then, convert each `update` section
individually.

Another option is to write down in plain English what operations you
wish to perform.  Then, look at the new documentation to see how those
operations match to the new syntax.

In most cases, the operations are little more than "add attributes to
list", or "delete attributes from list".  Those operations are simple
to perform in the new syntax.

== Issues with the Old Operators

The operators in the `update` sections were really _list_ operators,
and not _value_ operators.  For example, `+=` was "add attribute to
list", and not "add value to attribute".  This mixup was the source of
a significant amount of confusion when people first tried to use
FreeRADIUS.

In addition, using `+=` to manipulate lists meant that it was
impossible to use that operator for adding values.  The follow-on
effect was that math had to be done using the `%{expr:...}` expansion,
which was confusing and difficult to document.  Changing the syntax
allowed the separation of list assignments from value modifications,
which meant that xref:unlang/expression.adoc[expressions] became
became simpler.

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.



= Update sections in v4

There was a proposal to split the functionality of update sections into
two keywords 'update' and 'filter'.

Update would handle assignment of new values, and filter would handle 
removal of old values.

The primary rationale for this, is that it's confusing for users to
have the filter operators '>=' '<=' '==' '!=' '=~' '!~' '-=' mixed with
the assignment operators '+=', ':=', '='.

As part of the design of update sections for nested attributes we'll
be introducing several new set operators.  These will be used to
calculate the union, intersection and complements between the set
of existing values/pairs at a given nesting level, and a new set of 
values/pairs provided in the update section.

== Syntax and examples of set operators

Set operators will be placed after an attribute reference in an update
section, and after each bracketed level of nesting.

Set operators determine how the set specified by the update section 
will be merged with existing attribute values.

For set operations, the LHS of the expression will be the attribute
reference immediate preceding the operator, and the RHS will be
the set specified within curly braces directly after the operator.

```
update &<LHS> <set operator> {
	<RHS>
}
```

The following initial operators will be allowed:

- += or ⋃ - Union
- -= or \ - Relative complement
- == or ⋂ - Intersection
- :=      - Assignment
- =       - Assignment if LHS is an empty set ({})
- !*	  - Deletion (unary).

The default operator if none was specified, would be ':='

Set operators will function for 'leaf' attributes and for nested attributes.

.Adding values to a leaf attribute
```
update &User-Name += {
	'foo'
	'bar'
	'baz'
}
```

Would create three additional instances of &User-Name 
{ (User-Name, 'foo'), (User-Name, 'bar'), (User-Name, 'baz') }.

.Assigning values to a grouping attribute
```
update &My-Group := {
	&A-Child-Attr = 'foo'
	&B-Child-Attr = 'bar'
}

```

Would set the first instance of My-Group to be:
----
My-Group = {
	(A-Child-Attr, 'foo'),
	(B-Child-Attr, 'bar)
}
----

.Adding values to a grouping attribute
```
update &My-Group += {
	&A-Child-Attr = 'foo'
	&B-Child-Attr = 'bar'
}
```

Would add children { (A-Child-Attr, 'foo'), (B-Child-Attr, 'bar') to the first
instance of &My-Group. Creating it if it did not exist.

```
update &My-Group[*] += {
	&A-Child-Attr = 'foo'
	&B-Child-Attr = 'bar'
}
```

Would add children { (A-Child-Attr, 'foo'), (B-Child-Attr, 'bar') to all
instances of &My-Group.

.Removing values from a leaf attribute
----
update &User-Name -= {
	'foo'
	'bar'
	'baz'
}
----

Would remove the first instance of User-Name if it contained any of
{ 'foo', 'bar', 'baz' }
----
update &User-Name[*] -= {
	'foo'
	'bar'
	'baz'
}
----

Would remove any instances of User-Name containing 'foo', 'bar' or
'baz'.

=== Compatibility with existing update sections

The proposed set operators would be compatible with the current 
update section behaviour, as the lists themselves would be
considered grouping attributes.

```
update request {
	&User-Name := 'foo'
}
```

Would mean overwrite the first instance of (User-Name, 'foo') as it
does today, and is identical to

```
update &request.User-Name := {
	'foo'
}
```

=== Operation with deeply nested attributes

Set operators would be allowed at every level of nesting, and would
exhibit the same behaviour.

```
update request.my-group += {
	a-child-group -= {
		&User-Name = 'foo'
	}
}
```

The first instance of my-group will have a child attribute 'a-child-group' 
added to its children. 'a-child-group' instance being added will be equal 
to the current first instance of 'a-child-group' 
minus the pair (user-name, 'foo').

It makes my head hurt too, but at least its consistent.

For a less painful example:

```
update &request.my-group.a-child-group.User-Name {
	'foo'
}
```

Set the first instance of my-group to be {(a-child-group, { (User-Name, 'foo') })}.

Which is equivalent to:

```
update &request {
	&my-group {
		&a-child-group {
			&User-Name := 'foo'
		}
	}
}
```

== Selectors

With the above examples we can see that using the wildcard selector
'[*]' produces a very different result to using the default selector
'[0]'.

Because of the power of selectors when limiting the scope of
modifications, it would be useful to expand them to operate as full
conditions.

For example, given the reference and selector `&User-Name[~= /bob/]`,
the LHS would be all instances of the User-Name attribute, the 
operator would be '~=' (regex match), and the RHS would be the regex
`/bob/`.  The reference and selector would evaluate to all instances
of &User-Name attribute that contained the character sequence 'bob'.

When selectors are combined with assignment operators in an update
section, they effectively negate the need for a filter keyword,
because they separate selecting the subset of attributes to operate
on, from the operation being performed.

== Attribute filtering

```
update {
	&User-Name[~= /bob/] !* ANY
}
```

Would remove any instances of the `&User-Name` attribute containing 
'bob'.

== Attribute rewriting

```
update {
	&User-Name[~= /^.*@(.*)$/] := "%{1}"
}
```

Would strip the user portion from a User-Name string
leaving only the domain.

== Attribute overwriting

```
update {
	&User-Name[~= /bob/] := 'john'
}
```

All values containing 'bob' would be set to 'john'

== Selective addition

```
update {
	&User-Name[~= /bob/] = 'john'
}
```

John would only be added if no User-Name values contained 'bob'
