#
# Makefile	Radius Makefile for OSF/Unix (Digital)
#
#		Add "-DOSFC2" to CFLAGS and "-lsecurity" to LIBS
#		if you want to compile for OSF with C2 security
#

CC	= gcc
CFLAGS	= -g -Wall -Wno-unused -DNOSHADOW
LDFLAGS	= # -s #tatic
LIBS	= 
LCRYPT	=

DBM     = #-DNDBM
DBMLIB  = #-ldb

#PAM	= -DPAM
#PAMLIB	= -lpam

BINDIR  = /usr/local/bin
SBINDIR = /usr/local/sbin

include Make.inc
