#
# Makefile	Radius Makefile for Solaris 2.5.x
#

CC	= gcc
CFLAGS	= -g # -DNOSHADOW
LDFLAGS	= # -s #tatic
LIBS	= -lsocket -lnsl
LCRYPT	=

DBM     = #-DNDBM
DBMLIB  = #-ldb

#PAM	= -DPAM
#PAMLIB	= -lpam

BINDIR  = /usr/local/bin
SBINDIR = /usr/local/sbin

include Make.inc
