== Installation

These instructions cover installing FreeRADIUS 4.x which, though actively used in multiple high profile client deployments (whom have https://networkradius.com/freeradius-support/[purchased a support contract]), demands otherwise a user whom seeks danger and enjoys deploying a highly volatile evolving codebase in environments where traditionally stability is sought.  If this describes you, then FR4 is for you!

Hopefully it is clear, we recommend 99.9%+ of users use [FreeRADIUS 3.0.x](https://freeradius.org/releases/) and the https://networkradius.com/freeradius-packages/[pre-built packages] available from https://networkradius.com[Network RADIUS]].

Technical reasons to use FreeRADIUS 4.x over 3.0.x:

 * you have a request rate exceeding 15k per requests per second
 * your database(s) is slow; but really, fix your database (or pay Network RADIUS to do so) it will be less work and you gain a lot of other benefits in doing so!
 * ...others reasons we shall not reveal but the reader knows as they went spelunking through the source code

Non-technical reasons to use FreeRADIUS 4.x over 3.0.x:

 * you have a lot of spare time on your hands
 * you love to support non-officially released software in your environment

If anything above applies to you and you are still determined, it is strongly recommended you purchase support directly from https://networkradius.com[Network RADIUS] who may be able to guide you through your journey of madness.

=== Building

FreeRADIUS 4.x does *not* have any pre-built packages available instead you will need to use `git` and compile from source.

The following sub-sections cover meeting the minimal xref:developers:dependencies.adoc[core build dependencies] but not the per-module dependencies that enable support for external services such as LDAP, SQL, etc.  The FreeRADIUS `./configure` step will automatically detect if as each module has its dependencies met and automatically enable support for them, but if what you are looking for is not enabled you should inspect the console output (and `scripts/docker`) to figure out what you need to additionally install as development packages.

==== Debian

Starting with a minimal Debian 'buster' 10 install:

[source,shell]
----
sudo apt-get update
sudo apt-get -y install --no-install-recommends automake build-essential ca-certificates cmake git libtalloc-dev libtool libssl-dev
git clone https://github.com/mheily/libkqueue
cd libkqueue
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib
make -j$(getconf _NPROCESSORS_ONLN) && sudo make install
cd ..
git clone https://github.com/FreeRADIUS/freeradius-server
cd freeradius-server
sh autogen.sh && ./configure && make -j$(getconf _NPROCESSORS_ONLN)
sudo make install && sudo make -C /usr/local/etc/raddb/certs
cd ..
----

If the above does not work for you, sorry, we dropped the ball and you should inspect `scripts/docker/build-debian10` for the wisdom contained within.

==== CentOS

Starting with a minimal CentOS 7 install:

[source,shell]
----
sudo yum -y install centos-release-scl
sudo yum -y install autoconf devtoolset-7 git openssl openssl-devel libtalloc-devel libtool
scl enable devtoolset-7 bash
git clone https://gitlab.kitware.com/cmake/cmake.git
cd cmake
./bootstrap && make -j$(getconf _NPROCESSORS_ONLN) && sudo make install
cd ..
git clone https://github.com/mheily/libkqueue
cd libkqueue
cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib
make -j$(getconf _NPROCESSORS_ONLN) && sudo make install
cd ..
git clone https://github.com/FreeRADIUS/freeradius-server
cd freeradius-server
sh autogen.sh && ./configure && make -j$(getconf _NPROCESSORS_ONLN)
sudo make install && sudo make -C /usr/local/etc/raddb/certs
cd ..
exit
----

If the above does not work for you, sorry, we dropped the ball and you should inspect `scripts/docker/build-centos7` for the wisdom contained within.

===== LDAP

CentOS and RedHat link their LDAP libraries against NSS. FreeRADIUS uses OpenSSL.  NSS and OpenSSL cannot be used in the same application, as they will cause it to crash.  FreeRADIUS therefore must use libldap from the https://ltb-project.org/documentation/openldap-rpm[LDAP Toolbox Project], which uses OpenSSL.

Import RPM public key for the LDAP Toolbox Project:

[source,shell]
----
rpm --import https://ltb-project.org/lib/RPM-GPG-KEY-LTB-project
----

Create a Yum/DNF repository file for the LDAP Toolbox Project:

[source,shell]
----
cat <<'EOF' | sudo tee /etc/yum.repos.d/ltb-project.repo > /dev/null
[ltb-project]
name=LTB project packages
baseurl=https://ltb-project.org/rpm/$releasever/$basearch
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-LTB-project
EOF
----

You should refer to https://networkradius.com/freeradius-packages/[FreeRADIUS Packages on the Network RADIUS website] for more up to date information on this

=== Install

The `make install` stage will install the binaries, the "man" pages, and _may_ install the configuration files.  If you have not installed FreeRADIUS before, then the configuration files for FreeRADIUS will be installed.  If you already have an existing FreeRADIUS server installed, then those files will *not* be overwritten.

The `make install` process will warn you about the files it could not install.  If you see a warning message about files that could not be installed, then you *must* ensure that the new server is using the new configuration files, and not the old configuration files as this may cause undesired behaviour and failure to authenticate.

The initial output from running in debugging mode (`radiusd -X`) will tell you which configuration files are being used.  See <<Upgrading>> for information about upgrading from older versions.  There *may* be changes in the dictionary files which are *required* for a new version of the software.  These files will *not* be installed over your current configuration, so you *must* verify and install any problem files by hand, for example using https://linux.die.net/man/1/diff[`diff(1)`] to check for changes.

When installing from source, it is *extremely* beneficial to read the output of `./configure`, `make`, and `make install`.  If a particular module you expected to be installed was not installed, then the output of the `./configure && make && make install` sequence will tell you why that module was not installed.  Please do *not* post questions to the http://lists.freeradius.org/pipermail/freeradius-users/[FreeRADIUS users] list without first carefully reading the output of this process as it often contains the information needed to resolve a problem.

==== Upgrading To A New Minor Release

The installation process will not over-write your existing configuration files.  It will, however, warn you about the files it did not install. These will require manual integration with the existing files.

It is generally not possible to re-use configurations between different major versions of the server. (For example - version 2 to version 3, or version 3 to version 4.

For details on what has changed between the version, see the xref:upgrade:index.adoc guide.

We *strongly* recommend that new major versions be installed in a different location than any existing installations.  Any local policies can then be migrated gradually to the configuration format of the new major version.  The number of differences in the new configuration mean that is is both simpler and safer to migrate your configurations rather than to try and just get the old configuration to work.

=== Running the server

If the server builds and installs, but doesn't run correctly, then you should first use debugging mode (`radiusd -X`) to figure out the problem.

This is your *best hope* for understanding the problem.  Read *all* of the messages which are printed to the screen, the answer to your problem will often be in a warning or error message.

We really cannot emphasize that last sentence enough.  Configuring a RADIUS server for complex local authentication isn't a trivial task.  Your *best* and *only* method for debugging it is to read the debug messages, where the server will tell you exactly what it's doing, and why.  You should then compare its behaviour to what you intended, and edit the configuration files as appropriate.

If you don't use debugging mode, and ask questions on the mailing list, then the responses will all tell you to use debugging mode.  The server prints out a lot of information in this mode, including suggestions for fixes to common problems.  Look especially for "WARNING" in the output, and read the related messages.

Since the main developers of FreeRADIUS use debugging mode to track down their configuration problems with the server, it's a good idea for you to use it, too.  If you don't, there is little hope for you to solve *any* configuration problem related to the server.

To start the server in debugging mode, do:

[source,shell]
----
radiusd -X
----

You should see a lot of text printed on the screen as it starts up and if the server says "Ready to process requests.", then it is running properly.  From another shell or window, type

[source,shell]
----
radtest test test localhost 0 testing123
----

You should see the server print out more messages as it receives the request, and responds to it.  The 'radtest' program should receive the response within a few seconds.  It doesn't matter if the authentication request is accepted or rejected, what matters is that the server received the request, and responded to it.

You can now edit the configuration files for your local system. You will usually want to start with `sites-enabled/default` for main configurations.  To set which NASes (clients) can communicate with this server, edit `raddb/clients.conf`.  Please read the configuration files carefully, as many configuration options are only documented in comments in the file.

Configuring and running the server *may* be complicated.  Many modules have `man` pages.  See `man rlm_pap`, or `man rlm_*` for information.  Please read the documentation in the `doc/` directory.  The comments in the configuration files also contain a lot of documentation.

If you have any additional issues, the https://wiki.freeradius.org/guide/FAQ[FAQ] is also a good place to start.
