= Testing via `ldapsearch`

Prior to configuring the `ldap` module, the LDAP server must first be
validated using the `ldapsearch` tool.

[source,shell]
----
ldapsearch -H ldaps://ldap.example.com:686 -x -D cn=freeradius,dc=example,dc=com -w mypassword -b ou=people,dc=example,dc=com -z 10 '(objectClass=inetOrgPerson)' '*'
----

Where you replace the following as appropriately:

* `ldaps://ldap.example.com:636`
  * location of the LDAP server and how to connect

  * `ldaps` is LDAP over SSL and defaults to port `636/tcp`

  * `ldap` is non-SSLed LDAP and defaults to port `389/tcp`
    * add `-ZZ` as an argument if you use Start TLS

  * `ldapi` is for UNIX socket connections

* `cn=freeradius,dc=example,dc=com`
  * username used by FreeRADIUS when connecting to LDAP

* `mypassword`
  * password used by FreeRADIUS is to use when connecting to LDAP

* `ou=people,dc=example,dc=com`
  * top branch ('base') of the LDAP tree where users are found

* `(objectClass=inetOrgPerson)`
  http://www.zytrax.com/books/ldap/apa/search.html[search filter]
  which captures the users (this is the LDAP equivalent of the `WHERE`
  clause in SQL)

* the parameter `-z 10` limits the number of results returned to ten,
  which should be informative, but not overwhelming.

If this test works, there should be text returned where each result
returned looks something like the following.  The text will of course
not be identical, as names and domains will be from the local system.

[source,ldif]
----
dn: uid=john,ou=people,dc=example,dc=com
objectClass: inetOrgPerson
uid: john
userPassword: password
----

If no objects are returned, then check that the search filter is
correct.  This checl is best done by removing the filter and use
instead `''` (do not use this in production!).  If it returns results,
then review the original LDAP search filter to select the (usually)
`objectClass` value where the users are stored.

If no users are returned, then verify:

* the user name and password credentials are correct

* that the credentials have read permissions to fetch and query those objects

* 'base' value supplied is correct
  * try amending the base to be the absolute base for the site,
    e.g. `dc=example,dc=com` (do not use this in production!)

* that there are users in the LDAP server.

* that the certificates (if used) pass OpenSSL verification verify:
  *`ldaps`*: `echo -n | openssl s_client -connect ldap.example.com:636`
  *`ldap` with Start TLS: `echo -n | openssl s_client -connect ldap.example.com:389 -starttls ldap`

* that there is no firewall blocking access, some techniques to check this which _may_ work for you:
  * `sudo traceroute -Tn -p 636 ldap.example.com`
     will be successful (and not continue indefinitely) when there is _no firewall blocking
  * `netcat -vz -w3 ldap.example.com 636` will return `succeeded` when there is no firewall blocking access

If the `ldapsearch` program fails to return anything useful, then the
previous steps should be performed until that program succeeds.
Unfortunately, every piece of advice in this section is site-specific,
and is independent of RADIUS.  Therefore you should not configure
FreeRADIUS to use LDAP until such time as `ldapsearch` succeeds.

It is always simpler to debug LDAP issues using an LDAP-specific tool
such as `ldapsearch`.  Adding a RADIUS server to the mix will just
make it more difficult to debug LDAP issues.

Similarly, it is not productive to ask questions about `ldapsearch`
and LDAP on the FreeRADIUS mailing list.  The list members can help
with configuring FreeRADIUS to talk to LDAP, but they are unable to
help with debugging `ldapsearch`.  Where possible, the local LDAP
administrator should be contacted for assistance.
