= LDAP

FreeRADIUS can be configured to use LDAP for both authentication and
authorization but not accounting.

Notes:

 * in an Microsoft Active Directory environment you should use
   `rlm_winbind` for authentication, and `rlm_ldap` for group
   membership as described below.  The WinBind protocol cannot do the
   full range of group checks that is possible with LDAP.

 * not covered here, RADIUS profiles (see `raddb/mods-available/ldap`
   and `src/tests/modules/ldap/example.com.ldif`) that can be used to
   store logic you would normally place in your `users` file in LDAP

 * not covered here, dynamic clients (see
   `raddb/sites-available/dynamic-clients` and
   `src/tests/modules/ldap/example.com.ldif`) can also use and be
   stored in LDAP

== Preparation

In order to use LDAP, there must be an existing LDAP server populated
with users, and possibly groups.  If there is not a local LDAP server,
then it is possible to install one via a
xref:modules/ldap_docker.adoc[docker] image.

Once an LDAP server is available, it is critical that it is tested via
the command-line xref:modules/ldap_search.adoc[ldapsearch] tool.  If
testing via `ldapsearch` fails, then that has to debugged before
configuring FreeRADIUS.

=== Configuring the LDAP module

Once the xref:modules/ldap_search.adoc[ldapsearch] validation tests
pass, the next step is to
xref:modules/ldap_configuration.adoc[configure the LDAP module].

The configuration step should be little more than copying the
parameters used by xref:modules/ldap_search.adoc[ldapsearch] to the
xref:raddb:mods-available/ldap.adoc[ldap module] configuration file.

=== Security Recommendations

The credentials (username *and* password) for FreeRADIUS to use to
connect to your LDAP server(s) should be secure.  We make the
following recommendations for LDAP "best practices" security.

* Create a dedicated account for use by FreeRADIUS

* Ensure that this account does not have administrator access

* Ensure that this account is read-only, and has no write permissions

* Start by using 'simple authentication' instead of
  https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer[SASL].
  The SASL protocol should be attempted only after 'simple
  authentication' has been verified to work.

* Use TLS for connecting between FreeRADIUS and the LDAP server.  See
  the `tls` sub-section of the default `ldap` module for instructions

* When storing RADIUS user profiles (quotas, `Simultaneous-Use` flags,
  access time restrictions, etc) in LDAP, the LDAP schema
  `doc/schemas/ldap/openldap/freeradius.schema` must first be imported
  into the LDAP server.

== Authentication

The LDAP module can be used by FreeRADIUS to read passwords order to
xref:modules/ldap_authentication.adoc[authenticate] users.  Please be
aware the FreeRADIUS is an _authentication server_, and LDAP is a
_database_.  This separation of roles means that FreeRADIUS supports
multiple kinds of authentication protocols such as `PAP`, `CHAP`,
`MS-CHAP`, etc.  An LDAP database supports only one authentication
method: "bind as user".  This authentication method is compatible only
with PAP.

Our recommendation is to use LDAP as a database.  FreeRADIUS should
read the "known good" password from LDAP, and then use that
information to authenticate the user.  It is almost always wrong to
use the LDAP "bind as user" method for authenticating users.

The only caveat to the above recommendation is Active Directory.  For
"security" reasons, Active Directory will not return the "known good"
password to FreeRADIUS over a standard LDAP query.  Therefore when
Active Directory is used, the choices are:

PAP::
Use "bind as user"

MS-CHAP::
Use xref:raddb:mods-available/ntlm_auth.adoc[`ntlm`] or xref:raddb:mods-available/winbind.adoc[`winbind`].

Due to the limitations of Active Directory, There are unfortunately no
other possible choices.

Please see the xref:modules/ldap_authentication.adoc[LDAP
authentication] page for more information on authenticating users with LDAP.

=== Authorization

==== Group Membership

Depending on the LDAP vendor you use, LDAP group membership is either
handled using the LDAP attributes:

 . *`member`:* LDAP object (for example with `objectClass` set to `groupOfNames`) that has LDAP `member` attributes listing the DNs of the user objects that are a member of the group
 . *`memberOf`:* LDAP attribute (for example called `memberOf`) in the user object that lists all the groups the user is a member of

Your LDAP server may utilise both, though you should check if it automatically keeps these two methods in sync server side.

To check for the first method use:

[source,shell]
----
ldapsearch -H ldaps://ldap.example.com:686 -x -D cn=freeradius,dc=example,dc=com -w mypassword -b ou=groups,dc=example,dc=com -z 10 '(objectClass=groupOfNames)' objectClass cn member
----

Where you replace the following as appropriately:

 * *`ou=groups,dc=example,dc=com`:* top branch ('base') of your LDAP tree where users are to be found
 * *`(objectClass=groupOfNames)`:*
    http://www.zytrax.com/books/ldap/apa/search.html[search filter]
    that captures your users (this is the LDAP equivalent of the
    `WHERE` clause in SQL)

If you see no results, then it may be that your LDAP server utilises
the second method, so you can alternatively re-inspect the output of
the authentication user output `ldapsearch` you used initially for
LDAP `memberOf` attributes.

Once you have determined what you need to use, make a note of it for later.


== Testing

=== Authentication

Now in another terminal window run on the FreeRADIUS server to test authentication:

[source,shell]
----
cat <<'EOF' | radclient -x localhost auth testing123
User-Name = "john"
User-Password = "password"
EOF
----

==== `Access-Accept`

If this works you should see `radclient` report `Access-Accept` almostly immediately without delay:

[source,log]
----
Sent Access-Request Id 39 from 0.0.0.0:47493 to 127.0.0.1:1812 length 44
  User-Name = john
  User-Password = password
Received Access-Accept Id 39 from 127.0.0.1:1812 to 0.0.0.0:47493 via lo length 26
  User-Name = "john"
----

On the FreeRADIUS debug terminal side, you should see something like:

[source,log]
----
...
(0)    ldap - Reserved connection (0)
(0)    ldap - EXPAND (uid=%{%{Stripped-User-Name}:-%{User-Name}})
(0)    ldap - --> (uid=john)
(0)    ldap - Performing search in "dc=example,dc=com" with filter "(uid=john)", scope "sub"
(0)    ldap - Waiting for search result...
(0)    ldap - User object found at DN "uid=john,ou=people,dc=example,dc=com"
(0)    ldap - Processing user attributes
(0)    ldap -   &control:Password-With-Header += password
(0)    ldap - Released connection (0)
(0)    ldap (updated)
...
(0)    pap - No {...} in &Password-With-Header, re-writing to Cleartext-Password
(0)    pap - Normalized &control:Password-With-Header -> &control:Cleartext-Password
(0)    pap - Removing &control:Password-With-Header
(0)    pap - Setting &control:Auth-Type = pap
(0)    pap (updated)
(0)  } # recv Access-Request (updated)
(0)  Running 'authenticate pap' from file /usr/local/etc/raddb/sites-enabled/default
(0)  authenticate pap {
(0)    pap - Login attempt with password
(0)    pap - Comparing with "known-good" Cleartext-Password (8)
(0)    pap - User authenticated successfully
(0)    pap (ok)
(0)  } # authenticate pap (ok)
(0)  Running 'send Access-Accept' from file /usr/local/etc/raddb/sites-enabled/default
...
----

Here FreeRADIUS is describing what it did:

 . used the `ldap` module
 ** searched for `(uid=john)` in `dc=example,dc=com`
 *** this is doing the same as the following that you could run on the CLI
+
[source,shell]
----
ldapsearch -LL -H ldap://localhost -x -D cn=freeradius,dc=example,dc=com -w mypassword -b dc=example,dc=com '(uid=john)'
----
 ** found `uid=john,ou=people,dc=example,dc=com`
 *** if for you no user is found, but you know the user is in your directory, recheck the `user { ... }` section in `raddb/mods-available/ldap` as you may have a filter or attribute configuration set incorrectly
 ** found some useful attributes associated with that user
 *** the password which it placed into `control:Password-With-Header`
 *** as RADIUS attributes were changed, it returns `updated` as a result code to unlang
 . the modules `expiration` and `logintime` were used, but both had no effect (`noop`)
 . the module `pap` was used
 ** it found a suitable password to use in `&Password-With-Header`
 *** populates `&control:Cleartext-Password`
 *** the module decides it has everything it needs to do authentication so sets `&control:Auth-Type = pap`
 *** as RADIUS attributes were changed, it returns `updated` as a result code to unlang
 . the authenticate section runs and hands off to `pap` as `&control:Auth-Type = pap` was set earlier
 ** `&control:Cleartext-Password` is compared to `&request:User-Password`
 ** matches so `ok` is returned
 . we return `Access-Accept` as `ok` was returned to unlang

This worked as the LDAP credentials used by FreeRADIUS to connect to the LDAP server is able to extract a the `userPassword` attribute; as could been seen from the example `ldapsearch` command provided earlier.

==== `Access-Reject`

If this fails, the response will be delayed by one second and `Access-Reject` will be returned:

[source,shell]
----
Debug : Sent Access-Request Id 130 from 0.0.0.0:49353 to 127.0.0.1:1812 length 44
Debug : Received Access-Reject Id 130 from 127.0.0.1:1812 to 0.0.0.0:49353 via lo length 20
(0) -: Expected Access-Accept got Access-Reject
----

You should now look to the output of the debugging from the FreeRADIUS terminal window which may show something like:

[source,log]
----
(0)    ldap - Reserved connection (0)
(0)    ldap - EXPAND (uid=%{%{Stripped-User-Name}:-%{User-Name}})
(0)    ldap - --> (uid=john)
(0)    ldap - Performing search in "dc=example,dc=com" with filter "(uid=john)", scope "sub"
(0)    ldap - Waiting for search result...
(0)    ldap - User object found at DN "uid=john,ou=people,dc=example,dc=com"
(0)    ldap - Processing user attributes
(0)    ldap - Released connection (0)
(0)    ldap (ok)
(0)    expiration (noop)
(0)    logintime (noop)
(0)    pap - WARNING: No "known good" password found for the user.  Not setting Auth-Type
(0)    pap - WARNING: Authentication will fail unless a "known good" password is available
(0)    pap (noop)
(0)  } # recv Access-Request (ok)
(0)  ERROR: No Auth-Type available: rejecting the user.
(0)  Running 'send Access-Reject' from file /usr/local/etc/raddb/sites-enabled/default
----

Here FreeRADIUS describes it:

 . used the `ldap` module
 ** searched for `(uid=john)` in `dc=example,dc=com`
 ** found `uid=john,ou=people,dc=example,dc=com`
 ** did *not* find any useful attributes associated with that user
 ** module was successful in operation, but changed no RADIUS attributes so returns `ok`
 . the modules `expiration` and `logintime` were used, but both had no effect (`noop`)
 . the module `pap` was used
 ** it finds no suitable password RADIUS attributes to use
 ** as it makes no changes, the module returns `noop`
 . no `Auth-Type` is set, so FreeRADIUS rejects the request (no even attempting to authenticate)
 . returns `Access-Reject`

This occurs as the LDAP credentials used by FreeRADIUS to connect to the LDAP server is *unable* to extract a the `userPassword` attribute; as could been seen from the example `ldapsearch` command provided earlier.

You have two options avaliable to you here (`Ctrl-C` the running FreeRADIUS server, make the change and restart):

 . change the permissions of the LDAP credentials used so that FreeRADIUS can read the LDAP `userPassword` attribute
 ** this is the recommended option
 ** fixing this, means you should see `Access-Accept` as described above
 . configure FreeRADIUS to attempt to 'bind' (LDAP language for 'login') as the user in the RADIUS request
 ** do this by editing `/usr/local/etc/raddb/sites-available/default`
 ** amend by adding after the call to `ldap` in `recv Access-Request { ... }` section, so that it looks like:
+
[source,unlang]
----
-ldap
if ((ok || updated) && &User-Password) {
    update {
        &control:Auth-Type := ldap
    }
}
----
 ** FreeRADIUS is now configured to attempt to LDAP bind if the `ldap` module finds a user and the RADIUS request contains a `User-Password` RADIUS attribute

If you use LDAP bind'ing to perform user authentication, then when `radclient` receives `Accept-Accept', the FreeRADIUS debug terminal will look like:

[source,log]
----
(0)    ldap - Reserved connection (0)
(0)    ldap - EXPAND (uid=%{%{Stripped-User-Name}:-%{User-Name}})
(0)    ldap - --> (uid=john)
(0)    ldap - Performing search in "dc=example,dc=com" with filter "(uid=john)", scope "sub"
(0)    ldap - Waiting for search result...
(0)    ldap - User object found at DN "uid=john,ou=people,dc=example,dc=com"
(0)    ldap - Processing user attributes
(0)    ldap - Released connection (0)
(0)    ldap (ok)
(0)    if ((ok || updated) && &User-Password) {
(0)      update {
(0)        &control:Auth-Type := ldap
(0)      } # update (noop)
(0)    } # if ((ok || updated) && &User-Password) (noop)
(0)    expiration (noop)
(0)    logintime (noop)
(0)    pap - WARNING: No "known good" password found for the user.  Not setting Auth-Type
(0)    pap - WARNING: Authentication will fail unless a "known good" password is available
(0)    pap (noop)
(0)  } # recv Access-Request (ok)
(0)  Running 'authenticate ldap' from file /usr/local/etc/raddb/sites-enabled/default
(0)  authenticate ldap {
(0)    ldap - Login attempt with password
(0)    ldap - Reserved connection (1)
(0)    ldap - Login attempt by "john"
(0)    ldap - Using user DN from request "uid=john,ou=people,dc=example,dc=com"
(0)    ldap - Waiting for bind result...
(0)    ldap - Bind successful
(0)    ldap - Bind as user "uid=john,ou=people,dc=example,dc=com" was successful
(0)    ldap - Released connection (1)
(0)    ldap (ok)
(0)  } # authenticate ldap (ok)
(0)  Running 'send Access-Accept' from file /usr/local/etc/raddb/sites-enabled/default
----

Here FreeRADIUS is describes it:

 . used the `ldap` module
 ** searched for `(uid=john)` in `dc=example,dc=com`
 ** found `uid=john,ou=people,dc=example,dc=com`
 ** did *not* find any useful attributes associated with that user
 ** module was successful in operation, but changed no RADIUS attributes so returns `ok`
 . `&control:Auth-Type := ldap` was set as the `ldap` module was successful in finding a user
 . the modules `expiration` and `logintime` were used, but both had no effect (`noop`)
 . the module `pap` was used
 ** it finds no suitable password RADIUS attributes to use
 ** as it makes no changes, the module returns `noop`
 . the authenticate section runs and hands off to `ldap` as `&control:Auth-Type = ldap` was set earlier
 ** attemps to LDAP bind as `uid=john,ou=people,dc=example,dc=com`
 ** successful so `ok` is returned
 . we return `Access-Accept` as `ok` was returned to unlang

=== Authorization

If you wish to restrict the user so that they can only authenticate depending on an LDAP group membership, edit `/usr/local/etc/raddb/sites-available/default` so that under `recv Access-Request { ... }` the call out to the `ldap` module looks like:

[source,unlang]
----
-ldap
if (ok || updated) {
    if (!(ldap-Group == 'foo')) {
        update {
            &Reply-Message := "Not a member of the foo LDAP group"
        }
        reject
    }

# uncomment if you use LDAP bind's for authentication
#    if (&User-Password) {
#        update {
#            &control:Auth-Type := ldap
#        }
#    }
}
----

This restricts only LDAP users that are members of the LDAP `foo` group to connect.

If this fails to work recheck the `group { ... }` section in `raddb/mods-available/ldap` as you may have a filter or attribute configuration set incorrectly.
