= Getting Started

To begin with FreeRADIUS, install it on your system and configure a basic setup with a test user and client. Next, test the server's functionality in debug mode (`radiusd -X`). This process includes editing the client and users files to add a test user and client.

== Get the source

FreeRADIUS can be installed using the pre-built packages available from
https://packages.inkbridgenetworks.com[InkBridge Networks]. This site
contains packages for all common OS platforms and has the most current
packages for the latest release.

FreeRADIUS can also be installed from the source code. Please see the
xref:howto:installation/index.adoc[installation guide] for
instructions.

[NOTE]
====
Debian-based systems call the server daemon *freeradius* instead of
radiusd and the configuration files are located in
`/etc/freeradius/` instead of `/etc/raddb/`.
====

== Start the server

Once the server has been downloaded and installed, start the server in
debugging mode (as user `root`) by issuing the command:

```
radiusd -X
```

If the message on your screen says *Ready to process requests*, the
server is installed and configured properly.  For help decoding the
the output from `radiusd -X`, refer to the
xref:debugging/radiusd_X.adoc[debugging] page for more details.

== Initial tests

Test basic authentication by editing the
xref:reference:raddb/mods-config/files/users.adoc[users] file and add the
following line at the top of the file:

```
testing Password.Cleartext := "password"
```

Save the file and restart the server in xref:debugging/radiusd_X.adoc[debugging mode] (`radiusd -X`).
Open a second terminal window and run radtest by issuing the command:

```
radtest testing password 127.0.0.1 0 testing123
```

The expected result is that the server responds with an `Access-Accept`. If it doesn't, the debug log will show why.

If you do see an `Access-Accept`, then congratulations, the following
authentication methods now work for the testing user:

PAP, CHAP, MS-CHAPv1, MS-CHAPv2, PEAP, EAP-TTLS, EAP-GTC, EAP-MD5.

Your next step is to add more users.

== Add a client

Devices that communicate directly with the RADIUS server are the
clients that we need to configure next. These clients can be a
wireless access point (WAP) or network access switch (NAS). or other
form of NAS. The network clients or end-users such as laptops,
tablets, etc. do not talk directly to the RADIUS server.

The above test runs `radtest` from localhost. It is useful to add a new
client, which can be done by editing the clients.conf file. Add the
following content:

```
client new {
    ipaddr = 192.0.2.1
    secret = testing123
}
```

You should change the IP address from `192.0.2.1` to be the address of
the client which will be sending `Access-Request` packets.

The client should also be configured to talk to the RADIUS server, by
using the IP address of the machine running the RADIUS server. The
client must use the same secret as configured above in the client
section.

Then restart the server in debugging mode, and run a simple test using
the testing user. You should see an `Access-Accept` in the server output

The following steps outline the best known method for configuring the
server. Following them lets you create complex configurations with a
minimum of effort. Failure to follow them leads to days of frustration
and wasted effort.

## Configure the server

To create complex configurations with a minimum of effort, follow the
steps to configure the server *ONE* change at a time:

* Start with a "known working" configuration, such as supplied by the default installation.
* Make one small change to the configuration file.
* Start the server in debugging mode (`radiusd -X`).
* Verify that the results are what you expect.

Your next step is to configure more server components.

## More information

For specific problem solving, we recommend the xref:howto:index.adoc[Howto] guide. For configuring and testing individual modules, refer to
xref:howto:modules/configuring_modules.adoc[Modules].

All of the xref:reference:raddb/index.adoc[Configuration Files] are
available in hypertext format.

A detailed xref:reference:unlang/index.adoc[Unlang] reference guide
that describes the syntax and functionality of the keywords, data
types, etc. used in the `unlang` policy language.

There is also xref:developers:index.adoc[Developers] documentation
that includes the APIs references.

// Copyright (C) 2025 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
