= Locating objects

Once the correct xref:modules/ldap/ldapsearch/connection_parameters.adoc[connection parameters]
 have been determined, the next step in building your configuration
is to locate where user and group objects are stored in the directory.

== How to locate user objects
Users are represented by a fairly limited subset of ObjectClasses.  The
following filters are usually sufficient to identify users in different
directory types.

- OpenLDAP - `(|(ObjectClass=organizationalPerson)(ObjectClass=posixAccount)(ObjectClass=Person))`
- ActiveDirectory - `(|(ObjectClass=User)(ObjectClass=posixAccount))`
- Novell eDir - `(ObjectClass=User)`

.Performing a search with a user object filter
====
```
ldapsearch -z 10 -x -H ldap://ldap.example.com:389 -b "dc=example,dc=com" "(|(ObjectClass=organizationalPerson)(ObjectClass=PosixAccount)(ObjectClass=Person))"

# extended LDIF
#
# LDAPv3
# base <dc=example,dc=com> with scope subtree
# filter: (|(ObjectClass=organizationalPerson)(ObjectClass=PosixAccount)(ObjectClass=Person))
# requesting: ALL
#

...

# doctopus, octopuses, example.com
dn: uid=doctopus,ou=octopuses,dc=example,dc=com
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
cn: Doctopus McTentacles
sn: McTentacles
uid: dpus
givenName: Doctopus
userPassword:: MGN0MHB1NTNzUnVsMw==

# search result
search: 3
result: 0 Success

# numResponses: 18
# numEntries: 17
```
====

There's a lot of useful information in this result:

- We know where the user objects are likely to be located, as it's fairly
obvious from the DN (`...,ou=octopuses,dc=example,dc=com`). _Note: In the
majority of non-FreeRADIUS themed LDAP directories the user object container
will be `ou=people`_.
- The result shows a `uid` attribute.  This will almost always be the correct
attribute for identifying a user.
- The result shows a base64 encoded `userPassword` attribute.  This
means users can be authenticated without rebinding the connection (more
efficient).
- There's no `memberOf` attributes. This means user to group mappings
are likely stored in group objects instead of the user objects themselves.

=== What to record

- `user_object_base_dn`        - The DN higher in the tree than relevant users
objects.
- `user_object_class_filter`   - The filter which matches the objectClass(es) of
user objects.
- `uid_attribute`              - The attribute used to identify the user
(usually `uid`, but can vary considerably between instances).
- `user_password_attribute`    - The attribute used to hold password data (if
present).
- `account_disabled_attribute` - Any attributes used to indicate whether an
account is disabled. To determine if this attribute exists, repeat the user
search (above) with a filter for a user account known to be disabled e.g.
`(uid=a-disabled-user)`.
- `account_enabled_attribute`  - Any attributes used to indicate whether an
account is enabled.  Should be present in the search results already obtained.

.Locating users in "mature" LDAP directories
****
The above result represents an ideal scenario.  In reality, LDAP directories
often accumulate a lot of cruft.  Users objects may be located in
multiple container objects, and at multiple levels within a directory.

If you believe this to be the case with your directory, remove the `-z` argument
limiting the number of result, and pipe the output of `ldapsearch` through a
command chain _such as_: `grep dn: | sed -e 's/dn: [^,]*,//' | sort | uniq -c`.

This operation will return a list of objects which _contain_ user objects,
and how many user objects they contain.

.Determining which objects contain users
====
```
ldapsearch -x -H ldap://ldap.example.com:389 -b "dc=example,dc=com" "(|(ObjectClass=organizationalPerson)(ObjectClass=PosixAccount)(ObjectClass=Person))" | grep dn: | sed -e 's/dn: [^,]*,//' | sort | uniq -c`
2 ou=octopuses,dc=example,dc=com
10 ou=people,dc=example,dc=com
1 ou=people,dc=created-by-someone-who-didnt-know-what-dc-meant,dc=example,dc=com
2 ou=people,ou=remnant-of-an-ancient-edir-instance,dc=example,dc=com
2 ou=giraffes,dc=example,dc=com
```
====

The user object base DN selected for your rlm_ldap configuration must be higher
in the object tree than the objects containing users.  In the above example the
user object base DN would be `dc=example,dc=com`.

If an error message is returned similar to `Size limit exceeded (4)`, it means
that the LDAP server is refusing to provide the complete set of results. If the
LDAP directory supports result paging, adding a paging request such as `-E
'pr=100'` may negate the per-search result limit.

For large result sets you should also specify a list of attributes to retrieve
after the search filter.  Limiting the attributes returned reduces load on the
LDAP server, and generally results in a quicker response.

```
ldapsearch ... -E 'pr=100' "(|(ObjectClass=...))" "dn" | ...
```
****

== How to locate group objects

Groups are represented by a fairly limited subset of ObjectClasses.  The
following filters are usually sufficient to identify groups in different
directory types.

- OpenLDAP - `(objectClass=groupOfNames)`
- ActiveDirectory - `(objectClass=group)`
- Novell eDir - `(objectClass=group)`

.Performing a search with a group object filter
====
```
ldapsearch -z 10 -x -H ldap://ldap.example.com:389 -b "dc=example,dc=com" "(objectClass=posixGroup)"

# extended LDIF
#
# LDAPv3
# base <ou=people,dc=example,dc=com> with scope subtree
# filter: (ObjectClass=posixGroup)
# requesting: ALL
#

...

dn: cn=mariner-alert,ou=groups,dc=example,dc=com
cn: mariner-alert
description: Heads up to all delicious denizens of the directory
member: uid=doctopus,ou=octopuses,dc=example,dc=com
member: uid=rocktopus,ou=octopuses,dc=example,dc=com
objectClass: groupOfNames
objectClass: fdGroupMail
mail: mariner-alert@example.com

# search result
search: 3
result: 0 Success

# numResponses: 10
# numEntries: 9
```
====

.Locating groups in "mature" directories
****
As with users, groups may be located in multiple areas of the directory.

.Determining which objects contain groups
====
```
ldapsearch -x -H ldap://ldap.example.com:389 -b "dc=example,dc=com" -E 'pr=100' "(ObjectClass=posixGroup)" dn | grep dn: | sed -e 's/dn: [^,]*,//' | sort | uniq -c`
3 ou=groups,dc=example,dc=com
1 ou=groups,o=long-defunct-org-that-was-merged-with-example-com,dc=example,dc=com
3 ou=groups,ou=interns-summer-project,dc=example,dc=com
2 ou=groups,ou=backup-restored-in-the-wrong-place,dc=example,dc=com
```
====
****

=== Group membership scheme variants
Groups memberships can be represented in multiple ways.  There are four main
variants:

1. User objects which reference groups by DN, _usually_ with multiple
instances of the `memberOf` attribute.
2. User objects which reference groups by name, again, _usually_
with multiple instances of the `memberOf` attribute.
3. Group objects which reference their members by DN, _usually_ with multiple
instances of the `member` attribute.
4. Group objects which reference their members by name, _usually_ with
multiple instances of the `memberUid` attribute.

In order to perform efficient group lookups which group membership scheme the
LDAP server uses must be determined.

Repeat the search for user objects using a filter that matches a user known
to be members of one or more groups e.g.
`(&(objectClass=posixUser)(uid=doctopus))`.

- If the result shows a attribute containing the DN of known group, the LDAP
server implements _variant 1_.

- If the result shows a attribute containing the name of known group, the LDAP
server implements _variant 2_.

Repeat the the search for group objects using a filter that matches a group
the user is known to be a member of e.g. `(&(objectClass=groupOfNames)(cn=mariner-alert))`.

- If the result shows an attribute containing the DN of a user, the ldap server
implements _variant 3_.

- If the result shows an attribute containing the name of a user, the ldap server
implements _variant 4_.

=== If the variant can't be determined

- There's a typographical error in the search filter or `ldapsearch` arguments.
- The bound user doesn't have sufficient permission to view user or group
objects. Contact your LDAP administrator.
- The LDAP directory uses a special scheme to represent groups which requires
querying a special OID, or providing additional search controls (outside of the
scope of this howto).
- Group memberships are represented with 'operational' attributes.  Repeat the
user object search with '+' set as the second positional argument.

.Searching for a user object and returning operational attributes
```
ldapsearch -z 10 -x -H ldap://ldap.example.com:389 -b "dc=example,dc=com" "(ObjectClass=posixUser)" +
```

=== What to record

* `group_object_base_dn`             - The DN higher in the tree than all
relevant group objects.
* `group_name_attribute`             - The attribute used to identify the group
(usually `cn`).
* _variant 1_
** `membership_attribute`            - User object attribute containing group
membership information.
* _variant 2_
** `membership_attribute`            - User object attribute containing group
membership information.
* _variant 3_
** `membership_user_dn_filter`       - A filter matching users by DN.
* _vairant 4_
** `membership_user_name_filter`     - A filter matching users by user name.
