ALIAS	ASN-IP-Pool-Name                        	26.23782.1
ALIAS	ASN-Kbps-Down                           	26.23782.100
ALIAS	ASN-Kbps-Up                             	26.23782.101
ALIAS	ASN-Pps-Down                            	26.23782.102
ALIAS	ASN-Pps-Up                              	26.23782.103
ALIAS	ASN-TCP-Connlimit                       	26.23782.104
ALIAS	ASN-Firewall-State                      	26.23782.105
ALIAS	ASN-Firewall-Open                       	26.23782.106
ALIAS	ASN-Firewall-Block-Ping                 	26.23782.107
ALIAS	ASN-QoS-State                           	26.23782.108
ALIAS	ASN-IP-Redirect                         	26.23782.109
ALIAS	ASN-Firewall-Available                  	26.23782.110
ALIAS	ASN-QoS-Available                       	26.23782.111
ALIAS	ASN-Kbps-Down-Localmedia                	26.23782.112
ALIAS	ASN-Webfilter-Mode                      	26.23782.113
ALIAS	ASN-Webfilter-Redirect                  	26.23782.114
ALIAS	ASN-Webfilter-Destination               	26.23782.115
ALIAS	ASN-Webfilter-Domain                    	26.23782.116
