name: Feature Request
description: Used to report a request a new feature, updated documentation, etc.
title: "[feature]: "
labels: [feature enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request.
  - type: dropdown
    id: defect_type
    attributes:
      label: What type of feature is needed?
      options:
        - More documentation
        - Small feature, a tweak to existing behavior
        - Changed behavior to existing functionality
        - Proposal for new functionality
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What is the feature?
      description: A clear and concise description of what the feature should do.
      placeholder: 
    validations:
      required: true
