name: Any other questions about FreeRADIUS
description: Questions not relating to server configuration or development.
title: READ THE MESSAGE BELOW BEFORE SUBMITTING AN ISSUE
labels: [close]
body:
  - type: markdown
    attributes:
      value: |
        # STOP!
        - Are you _sure_ this isn't a configuration issue? **Questions about the server or its usage MUST be posted to the [users mailing list](https://freeradius.org/support/).**
        - Are you _sure_ this isn't a development issue? **Programming questions should be asked on the [developer's list](https://freeradius.org/support/).**
        - Are you _sure_ this isn't a question regarding protocol operation? **Questions on how protocols should operate should be answered by reading the relevant standards documents**.
        - Are you _sure_ this isn't a security exploit? **Remote security exploits MUST be sent to security@freeradius.org as part of [responsible disclosure](https://en.wikipedia.org/wiki/Responsible_disclosure)**.
        
        GitHub Issues are for **confirmed BUG REPORTS only** (e.g. software crashes). Use the [BUG REPORT](https://github.com/FreeRADIUS/freeradius-server/issues/new?assignees=&labels=&template=bug.yml) template. Do not submit **any** other general questions such as "how do I configure this" here.
        
        It is **NOT** a bug report if your configuration simply does not work. Ask for help on the [users mailing list](https://freeradius.org/support/).
        
        If you post those issues here that fall into the above categories, they will be closed and locked. Repeat offenders will be BANNED.
        
        If you are _sure_ that the question you have does not fall into any of the above categories and would not be better answered by posting to the [mailing lists](https://freeradius.org/support/), remove the "close" label, and add content in the text field below.  If you do not, your issue will be automatically closed.
  - type: textarea
    id: other
    attributes:
      label: Message
      description: Information you'd like to communicate to the FreeRADIUS development team
    validations:
      required: false
      
