TARGET		:= trunk_tests$(E)
SOURCES		:= trunk_tests.c

TGT_LDLIBS	:= $(LIBS) $(GPERFTOOLS_LIBS)
TGT_LDFLAGS	:= $(LDFLAGS) $(GPERFTOOLS_LDFLAGS)

TGT_PREREQS	+= libfreeradius-util$(L) $(LIBFREERADIUS_SERVER)
SRC_CFLAGS	+= -DTESTING_TRUNK

TGT_INSTALLDIR	:=
