.TH RADRELAY 8 "19 July 2005" "" "FreeRADIUS Daemon"
.SH NAME
radrelay -- Deprecated command.
.SH DESCRIPTION
The functions of \fIradrelay\fP have been added to \fIradiusd\fP.  One
benefit is that one instance of \fIradiusd\fP can read multiple detail
files, among others.
.PP
The \fIrlm_sql_log\fP module does something similar, but for SQL
queries.  See it's man page for details.
.SH SEE ALSO
.BR radiusd(8),
.BR radrelay.conf(5),
.BR rlm_sql_log(5)
.SH AUTHOR
The FreeRADIUS Server Project
