.TH RADWATCH 8 "24 February 2001" "" "FreeRADIUS Daemon"
.SH NAME
radwatch - wrapper for radiusd
.SH SYNOPSIS
.B radwatch
.IR [ options ]
.SH DESCRIPTION
This is a wrapper for \fIradiusd\fP. It starts the radius server, then
waits for it to terminate, which should never happen. If it does
happen, \fBradwatch\fP sends a notification email to \fIroot\fP about
the event, waits 10 seconds, then restarts the server.
.PP
This script \fBSHOULD NOT BE USED\fP!  It's only here for historical
purposes, and WILL be deleted in a future version of the
the server.
.PP
Please see '\fIdoc/supervise-radiusd.txt\fP' for info on methods of
supervising your radius installation.
.SH OPTIONS
Passed directly to the radius server - see the manpage of \fBradiusd\fP.
.SH SEE ALSO
radiusd(8).
.SH AUTHOR
Miquel van Smoorenburg, miquels@cistron.nl.
