= Contributing

== Submitting patches or diff's to the FreeRADIUS project

For a person or company wishing to submit a change to the FreeRADIUS
project the process can sometimes be daunting if you're not familiar
with "the system." This text is a collection of suggestions which can
greatly increase the chances of your change being accepted.

Note: Only trivial patches will be accepted via email. Large patches, or
patches that modify a number of files MUST be submitted as a
https://github.com/FreeRADIUS/freeradius-server/pulls[pull-request via GitHub].

== Hints and tips

=== 1. Describe your changes

Describe the technical detail of the change(s) your patch or commit
includes.

Be as specific as possible. The WORST descriptions possible include
things like "update file X", "bug fix for file X", or "this patch
includes updates for subsystem X. Please apply."

If your description starts to get long, that's a sign that you probably
need to split up your commit. See the next point.

=== 2. Separate your changes

Separate each logical change into its own commit.

For example, if your changes include both bug fixes and performance
enhancements for a single module, separate those changes into two or
more patches.

On the other hand, if you make a single change to numerous files, group
those changes into a single commit. Thus a single LOGICAL change is
contained within a single commit.

If one commit depends on another commit in order for a change to be
complete, that is OK. Simply note "this commit depends on commit X" in
the extended commit description.

If your commit includes significant whitespace changes these should also
be broken out into another, separate, commit.

== Submitting patches via GitHub

See the xref:github.adoc[GitHub] page for how to contibute patches via
GitHub.

Some additional documentation specific to Github is at https://help.github.com/articles/fork-a-repo

== Submitting patches via email

See the xref:email.adoc[Email] page for how to contibute patches via
email.  In short: don't.

// Copyright (C) 2025 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
