= FreeRADIUS Development

List with some usual howtos for FreeRADIUS.

Programming reference documentation can be found at the
https://doc.freeradius.org/[Doxygen] site.

## Instructions for Developers

As the name suggests, FreeRADIUS is developed under the GNU
General Public License, Version 2 (GPLv2).
We invite anyone to use and contribute code to the project. The
following information should prove useful for potential
contributors.

## Patches and contributions

Development of FreeRADIUS is done using
Github. Please
submit issues, bugs, patches, etc. there. Additional instructions are on
the wiki.

## Development mailing list

We encourage everyone who might contribute code to join the FreeRADIUS
development list(http://www.freeradius.org/list/devel.html). This
list is highly technical and isn't for most users of the server.
For normal discussion of the server and how to use it, subscribe to the
https://lists.freeradius.org/mailman/listinfo/freeradius-users[FreeRADIUS user-list].
*Only* subscribe to the development list if you are
interested in writing software for the new server.


## Miscellaneous links

RADIUS RFC's and drafts: The two
most important are
RFC2865(http://www.freeradius.org/rfc/rfc2865.html) and
RFC2866.(http://www.freeradius.org/rfc/rfc2866.html). These are
the new RFCs, which replace the old ones,
RFC2138(http://www.freeradius.org/rfc/rfc2138.txt) and
RFC2139(http://www.freeradius.org/rfc/rfc2139.txt)

== Topics

* xref:bugs.adoc[Bugs]
* xref:coding-methods.adoc[Coding Methods]
* xref:coverage.adoc[Code Coverage]
* xref:profile.adoc[Profiling]
* xref:coccinelle.adoc[Semantic Patches]
* xref:contributing.adoc[Contributing]
* xref:module_interface.adoc[Module Interface]
* xref:release-method.adoc[Release Method]
* Buffer handling
** xref:dbuff.adoc[Data buffers] (`dbuff` s)
** xref:sbuff.adoc[String buffers] (`sbuff` s)
** xref:sbuff-parsing.adoc[Parsing with string buffers]
** xref:sbuff-ng.adoc[Sbuff issues]

Also see the  xref:howto:installation/dependencies.adoc[build
dependencies] page.
