TARGET		= rlm_chap
SRCS		= rlm_chap.c
HEADERS		= 
RLM_CFLAGS	=

# over-ride the previous assignment if we're not building anything
include ../rules.mak

$(STATIC_OBJS): $(HEADERS)

$(DYNAMIC_OBJS): $(HEADERS)
