= Accounting

Accounting refers to the tracking of resources a user consumes during the time they are on the network. The information gathered can include the amount of system time used, the amount of data sent, or the quantity of data received by the user during a session.

During a network session, the NAS periodically sends an accounting of user activity to the RADIUS server. This accounting is a summary, and the collected data is used for billing purposes.

ISPs are a large consumer of accounting data, because each user is billed for every minute of network access. However, corporations have not, historically, relied on network accounting information gathered by RADIUS because employees were not traditionally billed for network access. As their need for ongoing
network monitoring increases, though, so does the need to store and process accounting information.

The accounting summary sent by the NAS to the RADIUS server does not include detailed information such as web sites visited or even how many bytes were transferred using a particular protocol (e.g., SMTP, HTTP). That type of detailed information is only available to the NAS, and it does not send that data to the RADIUS server.

If detailed information about user activity is required, network administrators obtain it through other protocols such as sFlow or NetFlow. Network administrators may find it difficult to tie the pieces together to get a more comprehensive understanding of user activity.

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
