= Testing with ldapsearch

Prior to configuring the `ldap` module, the connectivity and connection
parameters should be verified using the `ldapsearch` utility.

`ldapsearch` is provided as part of the OpenLDAP suite of tools.  These tools
should be installed on the machine used for testing the LDAP server.

We _strongly_ recommend running these checks on the same machine that will be
used to host the RADIUS server.  A common cause of connectivity issues is that a
firewall is preventing network access from the RADIUS server to the LDAP server.
Running `ldapsearch` on a third machine may not reveal these firewall issues.

== Before you start

Try to determine answers to the following questions:

* What's the IP address of the LDAP server being tested?
** If using an FQDN does the FQDN resolve to this IP address?
* Does the LDAP server requires encrypted connections?
** If yes:
*** Does the LDAP server use the StartTLS extension to transition to
encrypted communication, or is communication encrypted from the start (LDAPS)?
*** What are the necessary root certificates and intermediary certificates
needed to validate the identity of the LDAP server?
* What port is used to connect to the LDAP server?  Usually this will be `389`
(unencrypted or StartTLS) or `636` (LDAPS).

****
If using LDAP over TLS `openssl s_client` can display information about the
certificates presented by the LDAP server. The information returned
(particularly the certificate issuer(s)) in useful to determine what
certificates need to be available to the LDAP client.

The `openssl` invocation is different depending on whether StartTLS or LDAPS
is used.

.LDAPS - Retrieving the certificate chain of the fictitious ldap.internal.freeradius.org server
====
```
openssl s_client -host ldap.internal.freeradius.org -port 636 -prexit -showcerts
CONNECTED(00000003)
depth=1 C = OT, ST = Tentacle Cove, O = FreeRADIUS, OU = Services, CN = freeradius.org, emailAddress = support@freeradius.org
verify return:0
---
Certificate chain
 0 s:/C=OT/ST=Tentacle Cove/L=Grenoble/O=FreeRADIUS/OU=Services/CN=ldap.internal.freeradius.org/emailAddress=support@freeradius.org
   i:/C=OT/ST=Tentacle Cove/O=FreeRADIUS/OU=Services/CN=freeradius.org/emailAddress=support@freeradius.org
-----BEGIN CERTIFICATE-----
MIIHDjCCBPagAwIBAgIJANAO5znieeLNMA0GCSqGSIb3DQEBCwUAMIGSMQswCQYD
...
```
====

.StartTLS - Retrieving the certificate chain of the fictitious ldap.internal.freeradius.org server
====
```
openssl s_client -host ldap.internal.freeradius.org -port 389 -prexit -showcerts -starttls ldap
CONNECTED(00000003)
depth=1 C = OT, ST = Tentacle Cove, O = FreeRADIUS, OU = Services, CN = freeradius.org, emailAddress = support@freeradius.org
verify return:0
---
Certificate chain
 0 s:/C=OT/ST=Tentacle Cove/L=Grenoble/O=FreeRADIUS/OU=Services/CN=ldap.internal.freeradius.org/emailAddress=support@freeradius.org
   i:/C=OT/ST=Tentacle Cove/O=FreeRADIUS/OU=Services/CN=freeradius.org/emailAddress=support@freeradius.org
-----BEGIN CERTIFICATE-----
MIIHDjCCBPagAwIBAgIJANAO5znieeLNMA0GCSqGSIb3DQEBCwUAMIGSMQswCQYD
...
```
[NOTE]
.Availability of `-starttls ldap`
Not all builds of `openssl s_client` support `-starttls ldap`.  As of OpenSSL
1.1.1 this feature is still only available in the OpenSSL master branch. See
this GitHub Pull Request for details:
https://github.com/openssl/openssl/pull/2293.
====
****

* Do connections need to be bound to perform searches on the LDAP directory?
** If yes:
*** Determine what credentials are needed for binding, and whether a client
certificate is required.
* Determine the Base DN, the object deepest in the tree that contains the object
representing users, groups, clients etc...

== Determining the correct ldap search arguments

`ldapsearch` accepts a large number of different arguments, and allow relatively
complex commands to be sent to the LDAP server.

It will likely take a number of attempts to find the correct `ldapsearch` invocation.
If you have no prior information about the LDAP server follow the examples below,
adding progressively more connection parameters until ldapsearch returns one or more
results.

---
=== Search without bind (anonymous)
At a minimum, unless you have defaults set in your local `ldap.conf` file,
you will need to provide the following arguments:

- `-x` - Use simple authentication instead of SASL (correct for the majority of servers).
- `-H <ldap uri>` - The LDAP server to connect to.
- `-b <dn>` - A point in the LDAP tree to start the search from.

.Performing an anonymous search
====
```
ldapsearch -x -H ldap://ldap.example.com:389 -D "cn=freeradius,dc=example,dc=com"
```
====

---
=== Search with bind
```
ldap_bind: Server is unwilling to perform (53)
	additional info: unauthenticated bind (DN with no password) disallowed
```

The majority of LDAP servers will also require the LDAP client to identify itself,
this is done with a bind operation.

If you see a message similar to the one above, it means a bind operation must be
performed before attempting any operations on the LDAP server.

The following arguments should be added to identify the LDAP client to the LDAP
server:

- `-D` - The bind DN.  A unique identifier for the user being bound.
- `-w` - The bind password.

.Performing a search with a bound user
====
```
ldapsearch -x -H ldap://ldap.example.com:389 -D "cn=freeradius,dc=example,dc=com" -w mypassword -b "ou=people,dc=example,dc=com"
```
====
---

=== Search with bind over TLS
```
ldap_bind: Confidentiality required (13)
        additional info: TLS confidentiality required
```

Unless the LDAP server is on a secure local network, it will likely have been
configured to require TLS before allowing sensitive credentials to be submitted.

If you see a message similar to the one above, it means that TLS must be used
when connecting to the LDAP server.

==== Common arguments

- `LDAPTLS_CACERT=<ca_cert_and_intermediaries.pem>` - An environmental variable
specifying a PEM file containing CA and chain of trusted certificates, that
joins with the chain presented by the LDAP server.  These certificates must be
provided in order to validate the LDAP server's certificate.

- `LDAPTLS_REQCERT=hard` - An environmental variable requiring the LDAP server
provide a certificate.

==== LDAPS

LDAPS is configured by changing the URI scheme passed as the value to `-H`.

Where an unencrypted or StartTLS connection uses `ldap://`, LDAPS requires
`ldaps://`.

The port for LDAPS is different than for unencrypted communication. Where an
unencrypted or StartTLS connection normally uses `TCP/389`, LDAPS normally uses
`TCP/636`.

For LDAPS an unencrypted or StartTLS URI is changed from:
```
-H ldap://<fqdn>:389
```

to

```
-H ldaps://<fqdn>:636
```

==== StartTLS

StartTLS usually runs on the same port as unencrypted LDAP.

- `-ZZ` - Transition to encrypted communication using the StartTLS extension,
and fail if we can't.

.Performing a search with a bound user over TLS
====
```
ldapsearch -x -H ldap://ldap.example.com:389 -D "cn=freeradius,dc=example,dc=com" -w mypassword -b "ou=people,dc=example,dc=com"
```
====

The following changes to your `ldapsearch` command should be made to enable.
Note that the arguments are different dependent on the type of TLS connection
in use.





==== Start TLS



Where you replace the following as appropriately:

* `ldaps://ldap.example.com:636`
** location of the LDAP server and how to connect

** `ldaps` is LDAP over SSL and defaults to port `636/tcp`

** `ldap` is non-SSLed LDAP and defaults to port `389/tcp`
**** add `-ZZ` as an argument if you use Start TLS

** `ldapi` is for UNIX socket connections

* `cn=freeradius,dc=example,dc=com`
** username used by FreeRADIUS when connecting to LDAP

* `mypassword`
** password used by FreeRADIUS is to use when connecting to LDAP

* `ou=people,dc=example,dc=com`
** top branch ('base') of the LDAP tree where users are found

* `(objectClass=inetOrgPerson)`
  http://www.zytrax.com/books/ldap/apa/search.html[search filter]
  which captures the users (this is the LDAP equivalent of the `WHERE`
  clause in SQL)

* the parameter `-z 10` limits the number of results returned to ten,
  which should be informative, but not overwhelming.

If this test works, there should be text returned where each result
returned looks something like the following.  The text will of course
not be identical, as names and domains will be from the local system.

[source,ldif]
----
dn: uid=john,ou=people,dc=example,dc=com
objectClass: inetOrgPerson
uid: john
userPassword: password
----

If no objects are returned, then check that the search filter is
correct.  This checl is best done by removing the filter and use
instead `''` (do not use this in production!).  If it returns results,
then review the original LDAP search filter to select the (usually)
`objectClass` value where the users are stored.

If no users are returned, then verify:

* the user name and password credentials are correct

* that the credentials have read permissions to fetch and query those objects

* 'base' value supplied is correct
  * try amending the base to be the absolute base for the site,
    e.g. `dc=example,dc=com` (do not use this in production!)

* that there are users in the LDAP server.

* that the certificates (if used) pass OpenSSL verification verify:
  *`ldaps`*: `echo -n | openssl s_client -connect ldap.example.com:636`
  *`ldap` with Start TLS: `echo -n | openssl s_client -connect ldap.example.com:389 -starttls ldap`

* that there is no firewall blocking access, some techniques to check this which _may_ work for you:
  * `sudo traceroute -Tn -p 636 ldap.example.com`
     will be successful (and not continue indefinitely) when there is _no firewall blocking
  * `netcat -vz -w3 ldap.example.com 636` will return `succeeded` when there is no firewall blocking access

If the `ldapsearch` program fails to return anything useful, then the
previous steps should be performed until that program succeeds.
Unfortunately, every piece of advice in this section is site-specific,
and is independent of RADIUS.  Therefore you should not configure
FreeRADIUS to use LDAP until such time as `ldapsearch` succeeds.

It is always simpler to debug LDAP issues using an LDAP-specific tool
such as `ldapsearch`.  Adding a RADIUS server to the mix will just
make it more difficult to debug LDAP issues.

Similarly, it is not productive to ask questions about `ldapsearch`
and LDAP on the FreeRADIUS mailing list.  The list members can help
with configuring FreeRADIUS to talk to LDAP, but they are unable to
help with debugging `ldapsearch`.  Where possible, the local LDAP
administrator should be contacted for assistance.
