#!/bin/sh

set -e

case "$1" in
  remove)
        for file in /etc/freeradius/radiusd.conf /etc/freeradius/dictionary; do
          if dpkg-statoverride --list $file >/dev/null; then
            dpkg-statoverride --remove $file
          fi
        done

        if dpkg-statoverride --list /etc/freeradius >/dev/null; then
          dpkg-statoverride --remove /etc/freeradius
        fi
        ;;
esac

#DEBHELPER#
