#! /bin/sh -e

case "$1" in
  configure)
	update-rc.d freeradius defaults 50 >/dev/null
	if [ ! -d /var/log/freeradius ]
	then
		mkdir -p /var/log/freeradius
	fi
	if [ ! -f /var/log/freeradius/radius.log ]
	then
		touch /var/log/freeradius/radius.log
		chmod 640 /var/log/freeradius/radius.log
		chown root:adm /var/log/freeradius/radius.log
	fi
	if [ ! -f /var/log/freeradius/radwtmp ]
	then
		touch /var/log/freeradius/radwtmp
		chmod 644 /var/log/freeradius/radwtmp
		chown root:adm /var/log/freeradius/radius.log
	fi
	ldconfig
	/etc/init.d/freeradius start
	;;
  abort-upgrade)
	;;
  abort-remove)
	;;
  abort-deconfigure)
	;;
esac

#DEBHELPER#

exit 0
