#! /bin/sh -e

if [ "$1" = "remove" -o  "$1" = "purge" ]
then
	rm -f /etc/init.d/freeradius
	update-rc.d -f freeradius remove >/dev/null
fi

case "$1" in
	remove)
		;;
	purge)
		if [ -d /var/log/freeradius ] 
		then
			cd /var/log/freeradius
			rm -f radius.log radius.log.0 radius.log.*.gz
			rm -f radwtmp radwtmp.0 radwtmp.*.gz
			rm -f radutmp radwatch.log
			[ -d radacct ] && rm -rf radacct

			cd /var/log
			rm -rf /var/log/freeradius
		fi
		rm -rf /etc/raddb
		;;
	*)
		;;
esac

#DEBHELPER#

exit 0
