TGT_PREREQS := libfreeradius-radius.a
SRC_CFLAGS	+= -DRADIUSD_VERSION=\"${RADIUSD_VERSION}\"
SRC_CFLAGS	+= -DRADIUSD_VERSION_STRING=\"${RADIUSD_VERSION_STRING}\"
ifdef RADIUSD_VERSION_COMMIT
CFLAGS		+= -DRADIUSD_VERSION_COMMIT=\"${RADIUSD_VERSION_COMMIT}\"
endif
TGT_LDLIBS := $(LIBS) $(LIBREADLINE)

SOURCES	:= radmin.c

ifneq ($(LIBREADLINE),)
TARGET	:= radmin
else
TARGET  :=
endif
