#!/bin/sh
#
#  A tool which generates strong shared secrets.
#
openssl rand -base64 12 2>/dev/null && exit 0

(dd if=/dev/random bs=1 count=12 | base64 2>/dev/null) && exit 0

(dd if=/dev/random bs=1 count=12 | base32 2>/dev/null) && exit 0

echo "Failed finding 'openssl', 'base64', or 'base32' tools".
exit 1
