= Expiration

Policy to expire user accounts.

This policy can be used to expire user accounts. Expired users receive
an `Access-Reject` on every authentication attempt. Expiration is based on
the Expiration attribute which should be present in the check item list
for the user we wish to perform expiration checks.

== Topics

Expiration attribute is of type `date`:

You can use `Expiration := 23 Sep 2004` and the user will no longer be
able to connect at 00:00 (midnight) on September 23rd, 2004. If you want
a certain time (other than midnight) you can do use `Expiration := 23
Sep 2004 12:00`. The nas will receive a `Session-Timeout` attribute
calculated to kick the user off when the Expiration time occurs.

Example entry (users files):

`user1   Expiration := "23 Sep 2004"`

## Processing Sections

### authorize

When listed in the authorize section, the expiration module enforces the Expiration attribute. When the user’s account has a limited range of validity, the Session-Timeout attribute is updated to reflect this limited range.

If the Session-Timeout attribute already exists, the expiration module may decrease the value, but will never increase the value, of this attribute.

The format of the Expiration attribute is a date, as printed out by the date utility.

Example date
`$ date
Thu  3 Apr 2014 13:19:52 EDT`

_**Return codes**_

`userlock` The user’s account has expired.

`noop` No `control:Expiration` attribute was found.

`ok` A `control:Expiration` attribute was found, and the user’s account is still active.

== Location

The `expiration` policy is located in `policy.d/time`
