= &Attribute References

.Syntax
[source,unlang]
----
&Attribute-Name
----

The `&Attribute-Name` operator returns a reference to the named
attribute.

When used as an existence check in a condition, the condition
evaluates to `true` if the attribute exists.  Otherwise, the condition
evaluates to `false`.

When used elsewhere, such as in xref:switch.adoc[switch], it returns
the value of the named attribute.

Older versions of the server did not use the `&` character to
distinguish attribute names from other strings.  Version 4 requires
the user of the `&` before attribute names.

Without the `&`, the server could interpret a string as `hello-there`
either as a literal string "hello-there", or as a reference to an
attribute named `hello-there`.  This ambiguity made it difficult to
parse the configuration files correctly in all cases.

Adding the leading `&` character means that attribute references are
now easily distinguishable from literal strings.

The attribute reference can also be qualified with a
xref:list.adoc[list] reference.  When no list is given, the
server looks in the input packet list for the named attribute.

.Examples

`&User-Name` +
`&NAS-IP-Address` +
`&reply.Reply-Message`

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
