= Regular Expressions

.Example
[source,unlang]
----
(data =~ /regex/)
(data =~ /regex/i)

(data !~ /regex/)
(data !~ /regex/i)
----

The regular expression operators perform regular expression matching
on the data. The `data` field can be an attribute reference or data,
as with the other xref:condition/cmp.adoc[comparison] operators.  The `/regex/`
field must be a valid regular expression.

The `=~` operator evaluates to `true` when `data` matches the
`/regex/` expression.  Otherwise, it evaluates to `false`.

The `!~` operator evaluates to `true` when `data` does not match the
`/regex/` expression.  Otherwise, it evaluates to `true`.

The regular expression comparison is performed on the _string
representation_ of the left side of the comparison.  That is, if the
left side is an xref:type/numb.adoc[integer], the regular
expression will behave is if the value `0` was the literal string
`"0"`.  Similarly, if the left side is an
xref:attr.adoc[&Attribute-Name], then the regular expression will
behave is if the attribute was printed to a string, and the match was
performed on the resulting string.

The syntax of the regular expression is defined by the regular
expression library available on the local system.
FreeRADIUS currently supports:

* link:https://www.pcre.org/original/doc/html/[libpcre] and
link:https://www.pcre.org/current/doc/html/[libpcre2] both of which
provide
link:https://en.wikipedia.org/wiki/Perl_Compatible_Regular_Expressions[Perl
Compatible Regular expressions].
* link:http://en.wikipedia.org/wiki/Regular_expression#POSIX_basic_and_extended[
Posix regular expressions].

The regular expression may be followed by a single `i` character.  The
`i` indicates that the regular expression match should be done in a
case-insensitive fashion.

When the `=~` operator is used, then parentheses in the regular
expression will define variables that contain the matching text.

The special variable `%\{0\}` contains a copy of the result of
evaluating the data field.  The variables `%\{1\}` and following refer
to the subsequent matched substring in the regular expression.

Please see the xref:xlat/predefined.adoc#_0[xlat documentation] for
more information on regular expression matching.

.Example
[source,unlang]
----
if (User-Name =~ /@example\.com$$/) {
    ...
}
----

// Copyright (C) 2019 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// Development of this documentation was sponsored by Network RADIUS SAS.
