= SQL Module

The SQL module has two parts: a generic SQL front-end
(rlm_sql), and a series of database-dependent back-end drivers,
(rlm_sql_mysql, rlm_sql_postgresql, etc.)

To build the drivers, you MUST ALSO install the development
versions of the database. This means you need the header
files and client libraries for the database, such as MySQL.

The rlm_sql_mysql driver is NOT a complete MySQL client. Instead, it is a small
"shim" between the FreeRADIUS rlm_sql module and the MySQL client
libraries.

The SQL schemas mirror the layout of the "users" file. To configure check items and reply items, see `man 5 users`, and the
examples in this file.

== Schema and usage

The schemas are available in `sql/*`, where is the name of the
database (mysql, postgresql, etc.)

The SQL module uses two sets of check and reply item tables for
processing in the authorization stage: One set (radcheck and
radreply) are specific to a single user. The other set
(radgroupcheck and radgroupreply) applies check and reply items
to users that are members of a certain SQL group. The usergroup table
lists the groups each user is a member of, along with a
priority field to control the order of group processing.

When the SQL module processes a request, it first performs user attribute processing:

. It searches the radcheck table any "check" attributes specific to the
user
. If check attributes are found and they match the request:
.. "Control" attributes from the radcheck table for this user are added to the control list, then
.. "Reply" attributes from the radreply table for this user are added to the reply list.

Next, it performs group attribute processing if any of the following
conditions are met:

- The user IS NOT found in radcheck.
- The user IS found in radcheck, but the check items DO NOT match.
- The user IS found in radcheck, the check items DO match AND
Fall-Through is set in the radreply table.
- The user IS found in radcheck, the check items DO match AND the
read_groups configuration item for the sql module is set to `yes`.

If groups are processed for the user, it pulls the list of groups the user is a member of from the radusergroup table, ordered by priority.
The priority field of the radusergroup table controls the order in which groups are processed, emulating the ordering in the layout of the users file.

Considering the groups in order of priority:

. The radgroupcheck table is searched for any check attributes specific to the group
. If check attributes are found for the group, and they match the request:
.. The control attributes from the radgroupcheck table for this group are added to the control list
.. The reply attributes from the radgroupreply table for this group are
added to the reply

Processing continues to the next group if any of the following conditions are met:

- There was not a match for the last group's check items OR
- Fall-Through was set in the last group's reply items

The above is exactly the same as in the `users` file.

=== Example with groups

For any complex setup, it is likely that most of the actual
processing will be done using groups. In these cases, the user entries
in radcheck and radreply will be of limited use except for things like
setting user-specific attributes such as the user's password. So, one
might have the following setup:

.radcheck table
|===
|UserName | Attribute          | Op | Value

|joeuser  | Password.Cleartext | := | somepassword
|===

.radreply table
|===
|UserName | Attribute          | Op | Value

|joeuser  | Fall-Through       | =  | Yes
|===

.radusergroup table
|===
|UserName | GroupName    | Priority

|joeuser  | WLANgroup    | 1   (Applied first)
|joeuser  | MeteredGroup | 2
|===

.radgroupcheck table
|===
|GroupName    | Attribute          | Op | Value

|Check items for various connection scenarios... | | |
|MeteredGroup | Simultaneous-Use   | := | 1
|===

.radgroupreply table
|===
|GroupName    | Attribute          | Op | Value

|Reply items for the groups... | | |
|WLANgroup    | Tunnel-Type             | := | VLAN
|WLANgroup    | Tunnel-Medium-Type      | := | IEEE-802
|WLANgroup    | Tunnel-Private-Group-ID | := | 20
|MeteredGroup | Filter-Id          | := | 123
|===


== The `op` field

One of the fields of the SQL schema is named "op". This is for the "operator"
used when evaluating the attributes, e.g.

[source,config]
----
Framed-IP-Address     :=      1.2.3.4
^ ATTRIBUTE ^       ^ OP ^   ^ VALUE ^
----

_Why doesn't my SQL configuration work when I leave the `op` field
empty?

If leave the `op' field blank, the server is misconfigured, and unpreditable behaviour occurs. Read this documentation thoroughly before you post questions on the mailing list.

If the op field is empty, the server does not know what you want it to do with the attribute.

  * Is it a check item that should be compared against the request?
  * Should it be added to the control or reply list?

Without the operator, the server simply doesn't know, so always put a
value in the field. The value is the string form of the operator: "=",
">=", etc. See below for more details.

== Operators

The list of operators is given below.  Each row shows the operator, an
example of its use, and its meaning when used as a check item and as a
reply item.

[options="header",cols="1,2,4,4"]
|=====
| Operator | Example | As a check item | As a reply item

| `=`
| `Attribute = Value`
| Not allowed for RADIUS protocol attributes.  Allowed for server configuration attributes (`Auth-Type`, etc.); sets the value of an attribute only if there is no other item of the same attribute.
| Adds the item to the reply list, but only if there is no other item of the same attribute.

| `:=`
| `Attribute := Value`
| Always matches.  Replaces any configuration item of the same name; if no attribute of that name appears in the request, the attribute is added.
| Identical meaning, but applied to the reply items instead of the request items.

| `==`
| `Attribute == Value`
| Matches if the named attribute is present in the request, AND has the given value.
| Not allowed.

| `+=`
| `Attribute += Value`
| Always matches.  Adds the current attribute with value to the list of configuration items.
| Identical meaning, but the attribute is added to the reply items.

| `!=`
| `Attribute != Value`
| Matches if the given attribute is in the request, AND does not have the given value.
| Not allowed.

| `>`
| `Attribute > Value`
| Matches if the request contains an attribute with a value greater than the one given.
| Not allowed.

| `>=`
| `Attribute >= Value`
| Matches if the request contains an attribute with a value greater than, or equal to, the one given.
| Not allowed.

| `<`
| `Attribute < Value`
| Matches if the request contains an attribute with a value less than the one given.
| Not allowed.

| `\<=`
| `Attribute \<= Value`
| Matches if the request contains an attribute with a value less than, or equal to, the one given.
| Not allowed.

| `=~`
| `Attribute =~ Expression`
| Matches if the request contains an attribute which matches the given regular expression.  May only be applied to string attributes.
| Not allowed.

| `!~`
| `Attribute !~ Expression`
| Matches if the request contains an attribute which does not match the given regular expression.  May only be applied to string attributes.
| Not allowed.

| `=*`
| `Attribute =* ANY`
| Matches if the request contains the named attribute.  The right-hand side must be the word `ANY`.
| Not allowed.

| `!*`
| `Attribute !* ANY`
| Matches if the request does not contain the named attribute.  The right-hand side must be the word `ANY`.
| Not allowed.
|=====


== Module instances

As with other modules, multiple instances of the rlm_sql module can
be defined and used wherever you like.

The default module configuration files for the different database types,
contain one instance without a name like so:

[source,config]
----
sql {
    ...
}
----

You can create multiple named instances like so:

[source,config]
----
sql sql_instance1 {
    ...
}

sql sql_instance2 {
    ...
}
----

And then you can use a specific instance in radiusd.conf, like so:

[source,config]
----
recv Access-Request {
    ...
    sql_instance1
    ...
}

process Accounting-Request {
    ...
    sql_instance1
    sql_instance2
    ...
}
----

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
