.TH RLM_REDIS_IPPOOL_TOOL 8
.SH NAME
rlm_redis_ippool_tool - Manage the contents of the FreeRadius ippool in redis
.SH SYNOPSIS
.P
This tool allows administrators to add, delete, or release IP
addresses in an IP address pool that is located in a Redis database.

.B rlm_redis_ippool_tool
.RB [ \-a\ \fIprefix\fP ]
.RB [ \-d\ \fIprefix\fP ]
.RB [ \-r\ \fIprefix\fP ]
.RB [ \-s\ \fIprefix\fP ]
[options] <server[:port]> <pool> [<range>]

.SH DESCRIPTION
\fBrlm_redis_ippool_tool\fP manages the contents of the FreeRADIUS
ippool that is located in a Redis database.
.P

.SH OPTIONS

.IP \-a\ \fIprefix\fP 
Add addresses or prefixes to the pool.
.IP \-d\ \fIprefix\fP 
Delete addresses or prefixes from the pool.
.IP \-r\ \fIprefix\fP 
Release addresses or prefixes from the pool.  They will remain in the pool, but will be marked as "unused".
.IP \-s\ \fIprefix\fP 
Show addresses or prefixes which are in the pool.

.IP \-f\ \fIfile\fP
Load the redis server connection parameters from a FreeRADIUS format configuration file.
.IP \-l
List available pools.
.IP \-p\ \fIprefix_len\fP 
The length of the prefix allocate.  It defaults to 32 for Ipv4, and
128 for IPv6.  This is used primarily for IPv6 where a prefix is
allocated to an intermediary router, which in turn allocates
sub-prefixes to the devices it serves
.IP \-x
Increase verbosity level
.IP \S
Print pool statistics.

.SH SEE ALSO
radiusd(8)
.SH AUTHORS
Currently part of the FreeRADIUS Project (http://www.freeradius.org)

Mailing list details are at http://www.freeradius.org/
