#!/bin/sh
#
# $Id$
#
#  Sample script to run when a 'user' file entry is like:
#
#bob	Password == "bob"
#	Exec-Program-Wait = "/path/to/program/exec-program-wait"
#
#  For 'acct_users':
#
#DEFAULT Acct-Status-Type == Start
#	Exec-Program = "/path/to/exec/acct/start"
#
#DEFAULT Acct-Status-Type == Stop
#	Exec-Program = "/path/to/exec/acct/stop"
#
#
#
#  The 
#
echo "Reply-Message += \"Hello, %u\","
echo "Reply-Message += \"PATH=$PATH\","
echo Framed-IP-Address = 255.255.255.255
exit 0
