



= Detail Module (Sample)

Please see the `detail` module for full documentation.

Detail file writer, used in the following examples:

  * xref:reference:raddb/sites-available/robust-proxy-accounting.adoc[sites-available/robust-proxy-accounting]
  * xref:reference:raddb/sites-available/decoupled-accounting.adoc[sites-available/decoupled-accounting]

NOTE: This module can write detail files that are read by
only ONE `listen { ... }` section. If you use BOTH of the examples
above, you will need to define TWO "detail" modules.

e.g. `detail1.example.com` && `detail2.example.com`

We write *multiple* detail files here. They will be processed
by the detail `listen { ... }` section in the order that they were
created. The directory containing these files should NOT be
used for any other purposes, i.e. it should have NO other
files in it.

TIP: Writing multiple detail enables the server to process the
pieces in smaller chunks. This helps in certain catastrophic
corner cases.


## Configuration Settings


== Default Configuration

```
detail detail.example.com {
	filename = "${radacctdir}/detail.example.com/detail-%Y-%m-%dT%H:%G:00"
}
```

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
