



= Detail Module (Log Sample)

More examples of doing detail logs.

NOTE: For a full explanation of the configuration options,
please see the `detail` module.



## Configuration Settings


### Access-Request

Many people want to log authentication requests. Different
instances of the `detail` module can be used to log the
authentication requests to one or more files.

NOTE: You will also need to un-comment the `auth_log` line in the
`recv Access-Request` section of `sites-enabled/default`.




suppress { ... }:: This will stop passwords being written to the log.



### Access-Accept

This module logs authentication reply packets sent to a NAS.
Both `link:https://freeradius.org/rfc/rfc2865.html#Access-Accept[Access-Accept]` and `link:https://freeradius.org/rfc/rfc2865.html#Access-Reject[Access-Reject]` packets are logged.

NOTE: You will also need to un-comment the 'reply_log' line in the
`send Access-Accept` section of `sites-enabled/default`.



== Default Configuration

```
detail auth_log {
	filename = "${radacctdir}/%{Net.Src.IP}/auth-detail-%Y-%m-%d"
	permissions = 0600
	suppress {
		User-Password
	}
}
detail reply_log {
	filename = "${radacctdir}/%{Net.Src.IP}/reply-detail-%Y-%m-%d"
	permissions = 0600
}
```

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
