



= Files Module

The `users` file as located in `raddb/mods-config/files/authorize`. (Livingston-style format).

See the xref:reference:raddb/mods-config/files/users.adoc[users] file for information
on the format of the input file, and how it operates.



## Configuration Settings


moddir:: Search for files in a subdirectory of mods-config which
matches this instance of the files module.



key:: The default key attribute to use for matches.

The content of this attribute is used to match the `name` of the entry.

Note that unlike v4, the key does not have to be a string, but could instead
be an IP address or netmask!  For more information, see

xref:reference:raddb/mods-config/files/users.adoc[users]



filename:: The old `users` style file is now located here.



match_attr:: List and attribute to populate with the `name` of the matched entry.

Note: the attriubte type should be capable of holding data of the type
used as key values.
Particularly useful if matching IP addresses to subnets, since the populated
value will be the subnet.  In that case it is best to use `0.0.0.0/0` in place
of `DEFAULT` for any catch-all entries.



v3_compat:: Version 3 compatibility flag.

When this flag is set, any enumeration names (e.g. Service-Type := Framed-User)
do not need to have the v4 "::" prefix.  This flag helps with migrating v3
configurations to v4.

Default value "false".  Allowed vaues, `true` and `false`.



## An instance of the `files` module for use in processing accounting packets


== Default Configuration

```
files {
	moddir = ${modconfdir}/${.:instance}
#	key = "%{Stripped-User-Name || User-Name}"
	filename = ${moddir}/authorize
#	match_attr = control.User-Category
#	v3_compat = false
}
files files_accounting {
#	key = "%{Stripped-User-Name || User-Name}"
	filename = ${modconfdir}/files/accounting
}
```

// Copyright (C) 2025 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
