= Modules

The server includes a number of "plug-in" modules which perform a
variety of actions.  Each module has a small set of functionality,
such as "connect to SQL database", or "check passwords".  This
structure means that most of the complexity of the server is hidden
behind (or encapsulated into) simple modular blocks.

For example, a simple policy which says "get password from SQL, and
then check it" is little more than two lines of text in a
configuration file:

[source,text]
----
sql
pap
----

Each of the above modules has a complex configuration file, but the
above policy does not contain the full configuration of SQL server
address, admin login, queries, etc.  Instead, the policy focusses on
the functional aspects of the requirements, which means that it is
easier to create and understand.  A simple policy also means that (for
example) the underlying SQL module can be reconfigured for a different
SQL server or even a different SQL database, and the policy does not
need to change.

The full syntax for using modules in policies can be found in the
`unlang` xref:reference:unlang/module.adoc[module] page.

The full and annotated
xref:raddb/mods-available/all_modules.adoc[module list] is large, and
is therefore available on a separate page.



== Categories

Modules are divided up into a few categories:

Authentication xref:raddb/mods-available/all_modules.adoc#_authentication_modules[list]::
Modules which implement authentication protocols such as PAP, CHAP, MS-CHAP, EAP, etc.

Datastore xref:raddb/mods-available/all_modules.adoc#_datastore_modules[list]::
Modules which connect to external data stores such as SQL, LDAP, etc.

IO xref:raddb/mods-available/all_modules.adoc#_io_modules[list]::
Modules which write to disk, external log systems, etc.

Language xref:raddb/mods-available/all_modules.adoc#_language_modules[list]::
Modules which encapsulate a scripting language into the server such as
Perl, Python, Lua, etc.

Miscelleanous xref:raddb/mods-available/all_modules.adoc#_miscellaneous_modules[list]::
Modules which do not belong elsewhere.

Policy xref:raddb/mods-available/all_modules.adoc#_policy_modules[list]::
Modules which implement policies to filter or enforce packets.

[#enabling]
== Enabling a Module

Modules are enabled by creating a file in the `mods-enabled/` directory.
You can also create a soft-link from one directory to another:

[source,shell]
----
$ cd mods-enabled/
$ ln -s ../mods-available/foo
----

This will enable module `foo`. Be sure that you have configured the
module correctly before enabling it, otherwise the server will not
start. You can verify the server configuration by running
`radiusd -XC`.

A large number of modules are enabled by default. This allows the server
to work with the largest number of authentication protocols. Please be
careful when disabling modules. You will likely need to edit the
`sites-enabled/` files to remove references to any disabled modules.

== Conditional Modules

FreeRADIUS allows modules to be conditionally loaded. This is useful
when you want to have a virtual server which references a module, but
does not require it. Instead of editing the virtual server file, you can
just conditionally enable the module.

Modules are conditionally enabled by adding a `-` before their name in
a virtual server. For example, you can do:

[source,unlang]
----
server {
    ...
    recv Access-Request {
        ...
        ldap
        -sql
        ...
    }
}
----

This configuration means that the server will _require the LDAP
module, but use the SQL module only if it is configured._

This feature is not very useful for production configurations. It is,
however, very useful for the default examples that ship with the
server.

=== Ignoring A Module

If you see this message:

----
Ignoring "sql" as it is commented out.
----

then it signifies that the module is commented out as desceribed
above.  Most of the time this message can be ignored. The message can
be fixed by find the references to `-module` in the virtual server,
and deleting them.

Another way to fix it is to configure the module, as described above.

== Simplification

Allowing conditional modules simplifies the default virtual servers that
are shipped with FreeRADIUS. This means that if you want to enable LDAP
(for example), you no longer need to edit the files in
`sites-available/` in order to enable it.

Instead, you should edit the `mods-available/ldap` file to point to
your local LDAP server. Then, enable the module via the soft-link method
described above.

Once the module is enabled, it will automatically be used in the default
configuration.

== Module-Specific Configuration Files

Some modules require the use of additional configuration files.  These
additional files are located in the
xref:raddb/mods-config/index.adoc[mods-config/] directory.  The meaning and
interpretation of those files is documented there.  These files are
often in a custom, module-specific format, instead of using the
standard configuration file format.

== Module-Specific Overrides

Most modules have section-specific functionality.  For example, the
`sql` module does different things when it is doing authentication
versus accounting.  The xref:unlang/module_method.adoc[method
override] functionality lets you call a particular "method" of a
module when running a different section.

== Policy Overrides

The server can also replace a module call with a policy.  For example,
a virtual server can contain a reference to the `radius` module.  In
most cases, this reference will (of course) call the `radius` module.

In some cases, it is necessary to have module-specific policies.  The
xref:raddb/policy.d/method.adoc[policy override] syntax allows
for policies to be added around a module, or to override a module
method.

In addition, the xref:raddb/policy.d/at_reference.adoc[@policy] references
allow for policies to be placed in the module configuration file,
which helps to better organize module-specific configurations and
policies.

// Copyright (C) 2025 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
