



= Lua Module

The `lua` module processes attributes through a Lua interpreter.

  * Please see the `src/modules/rlm_lua/example.lua` for a sample Lua script.
  * Please see https://www.lua.org/ for more information about the Lua language.

The Lua function names called when the `lua` module is called are
automatically derived from the section in which they are called.

If `lua` is called in `recv Access-Request`, firstly a function
`recv_access_request` will be looked for.  If that does not exist, then
a function `recv` will be looked for.

This can be overridden by setting `func_recv_access_request` or `func_recv`
to point to a different function name.



== Configuration Settings


filename:: Module to load functions from.



func_instantiate:: Called on module instantiation.



func_detach:: Called on module unload.


== Default Configuration

```
lua {
	filename = ${modconfdir}/${.:instance}/example.lua
#	func_instantiate = instantiate
#	func_detach = detach
}
```

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
