
= REDISWho Module

The `rediswho` module tracks the last set of login sessions for a
user.

== Configuration Settings

trim_count:: How many sessions to keep track of per user.

If there are more than this number, older sessions are deleted.

expire_time:: Expiry time in seconds.

Any sessions which have not received an update in this time will be
automatically expired.

== Queries by Acct-Status-Type

Each subsection contains insert / trim / expire queries.

The subsections are named after the contents of the
`link:https://freeradius.org/rfc/rfc2866.html#Acct-Status-Type[Acct-Status-Type]`
attribute.

See `dictionary.rfc2866` for the names of the various Acct-Status-Type
values, or look at the output of debug mode.

This module supports *any*
`link:https://freeradius.org/rfc/rfc2866.html#Acct-Status-Type[Acct-Status-Type]`.
Just add a subsection of the appropriate name, along with insert /
trim / expire queries.

=== Start

=== Interim-Update

=== Stop

=== Accounting-On

=== Accounting-Off

=== Failed

redis { ... }:: Redis connection settings.

Identical to all other Redis based modules.

NOTE: See the `redis` module for more information.

== Default Configuration

----
rediswho {
	trim_count = 15
	expire_time = 86400
	Start {
		insert = "LPUSH %{User-Name} %l,%{Acct-Session-Id},%{NAS-IP-Address || NAS-IPv6-Address},%{Acct-Session-Time},%{Framed-IP-Address},%{Acct-Input-Gigawords || 0},%{Acct-Output-Gigawords || 0},%{Acct-Input-Octets || 0},%{Acct-Output-Octets || 0}"
		trim =   "LTRIM %{User-Name} 0 ${..trim_count}"
		expire = "EXPIRE %{User-Name} ${..expire_time}"
	}
	Interim-Update {
		insert = "LPUSH %{User-Name} %l,%{Acct-Session-Id},%{NAS-IP-Address || NAS-IPv6-Address},%{Acct-Session-Time},%{Framed-IP-Address},%{Acct-Input-Gigawords || 0},%{Acct-Output-Gigawords || 0},%{Acct-Input-Octets || 0},%{Acct-Output-Octets || 0}"
		trim =   "LTRIM %{User-Name} 0 ${..trim_count}"
		expire = "EXPIRE %{User-Name} ${..expire_time}"
	}
	Stop {
		insert = "LPUSH %{User-Name} %l,%{Acct-Session-Id},%{NAS-IP-Address || NAS-IPv6-Address},%{Acct-Session-Time},%{Framed-IP-Address},%{Acct-Input-Gigawords || 0},%{Acct-Output-Gigawords || 0},%{Acct-Input-Octets || 0},%{Acct-Output-Octets || 0}"
		trim =   "LTRIM %{User-Name} 0 ${..trim_count}"
		expire = "EXPIRE %{User-Name} ${..expire_time}"
	}
##	Accounting-On {
##		insert = ""
##		trim =   ""
##		expire = ""
##	}
##	Accounting-Off {
##		insert = ""
##		trim =   ""
##		expire = ""
##	}
##	Failed {
##		insert = ""
##		trim =   ""
##		expire = ""
##	}
	redis {
		server = 127.0.0.1
		virtual_server = redis
		port = 6379
##		password = thisisreallysecretandhardtoguess
		pool {
			start = 0
			min = 1
			max = 10
			connecting = 2
##			open_delay = 0.2
##			close_delay = 10
##			manage_interval = 0.2
			connection {
				connect_timeout = 3.0
				reconnect_delay = 5
			}
			request {
				per_connection_max = 2000
				per_connection_target = 1000
				free_delay = 10
			}
		}
	}
}
----

// Copyright (C) 2026 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
