



= etc_group Module

The `etc_group` module provides group names from the `/etc/group` file.

NOTE: Please see the `passwd` module for full documentation on the
configuration items used here.



## Configuration Settings

The `passwd` module configuration, for the /etc/group file. Adds a
`Etc-Group-Name` attribute for every group that the user is a member
of.

You will have to define the `Etc-Group-Name` in the `dictionary` file
as a 'string' type.

The `Group` and `Group-Name` attributes are automatically created by
the Unix module and check against `/etc/group` automatically.

[WARNING]
====
  * This means that you *CANNOT* use `Group` or `Group-Name` to do any other
  kind of grouping in the server. You *MUST* define a new group attribute.
  * This module should *NOT* be used as-is, but should be edited to
  point to a different group file.
====



== Default Configuration

```
passwd etc_group {
	filename = /etc/group
	format = "=Etc-Group-Name:::*,User-Name"
	hash_size = 50
	ignore_nislike = yes
	allow_multiple_keys = yes
	delimiter = ":"
}
```
