



= Files Module

The `users` file as located in `raddb/mods-config/files/authorize`. (Livingston-style format).

See the xref:raddb:mods-config/files/users.adoc[users] file documention for information
on the format of the input file, and how it operates.



## Configuration Settings


moddir:: Search for files in a subdirectory of mods-config which
matches this instance of the files module.



key:: The default key attribute to use for matches.

The content of this attribute is used to match the `name` of the entry.



filename:: The old `users` style file is now located here.

If no other filenames are specified, the module uses this file.



Optional files

The following filenames are optional.


recv_filename:: The file to run in any "recv" section

send_filename:: The file to run in any "send" section

auth_filename:: The file to run in any "authenticate" section

acct_filename:: The file to run in any "recv Accounting-Request" section

== Default Configuration

```
files {
	moddir = ${modconfdir}/${.:instance}
#	key = "%{&Stripped-User-Name || &User-Name}"
	filename = ${moddir}/authorize
#	recv_filename =  ${moddir}/recv
#	send_filename =  ${moddir}/send
#	auth_filename =  ${moddir}/authenticate
#	acct_filename =  ${moddir}/accounting
}
```
