



= ICMP Module

The module `icmp` is used for sending ICMP Echo Request messages.

This module is useful only for `xlat`.  Use it via the following expansion:


The module will "ping" the given IP address.  If that IP address responds
with an ICMP Echo Reply, then the result of the expansion will be `yes`.
If that IP address does not respond within the timeout, then the result
of the expansion will be `no`.

The IP address does not have to be a fixed string.  It can be another
expansion, such as:





## Configuration Settings


interface:: Which interface to use for sending ICMP packets.

By default, packets are sent via the normal routing table.

Specifying an interface forces the packets to be sent via
that particular interface.



timeout:: How long to wait for the reply.

Default is `1` seconds, which should be plenty for nearly
anything. Range is `0.1s` to `10s`.

WARNING: You are strongly encouraged to NOT increase this
value.  In fact, you are much better off decreasing it to a
lower value.  Doing so will improve network stability and
responsiveness.


== Default Configuration

```
#	`%{icmp:192.0.2.1}`
#	`%{icmp:%{NAS-IP-Address}}`
icmp {
#	interface = eth0
	timeout = 1s
}
```
