# Generated automatically from Makefile.in by configure.
TARGET      = rlm_eap_leap
SRCS        = rlm_eap_leap.c eap_leap.c
RLM_CFLAGS  = $(INCLTDL) -I../..
HEADERS     = eap_leap.h  ../../eap.h ../../rlm_eap.h
RLM_INSTALL = 

$(STATIC_OBJS): $(HEADERS)

$(DYNAMIC_OBJS): $(HEADERS)

RLM_DIR=../../
include ${RLM_DIR}../rules.mak
