= LDAP Databases

Please be aware the FreeRADIUS is an _authentication server_, and LDAP
is a _database_.  This separation of roles means that FreeRADIUS
supports multiple kinds of authentication protocols such as `PAP`,
`CHAP`, `MS-CHAP`, etc.  An LDAP database supports only one
authentication method: "bind as user".  This authentication method is
compatible only with PAP.

Our recommendation is to use LDAP as a database.  FreeRADIUS should
read the "known good" password from LDAP, and then use that
information to authenticate the user.  It is almost always wrong to
use the LDAP "bind as user" method for authenticating users.

The only caveat to the above recommendation is Active Directory.  For
"security" reasons, Active Directory will not return the "known good"
password to FreeRADIUS over a standard LDAP query.  Therefore when
Active Directory is used, the choices are:

PAP::
Use "bind as user"

MS-CHAP::
Use xref:raddb:mods-available/ntlm_auth.adoc[`ntlm`] or xref:raddb:mods-available/winbind.adoc[`winbind`].

Due to the limitations of Active Directory, There are unfortunately no
other possible choices.

Please see the xref:modules/ldap_authentication.adoc[LDAP
authentication] concepts page for more information on the limitations
related to authenticating users with LDAP.

== LDAP Security Recommendations

The credentials (username *and* password) for FreeRADIUS to use to
connect to your LDAP server(s) should be secure.  We make the
following recommendations for LDAP "best practices" security.

* Create a dedicated account for use by FreeRADIUS

* Ensure that this account does not have administrator access

* Ensure that this account is read-only, and has no write permissions

* Start by using 'simple authentication' instead of
  https://en.wikipedia.org/wiki/Simple_Authentication_and_Security_Layer[SASL].
  The SASL protocol should be attempted only after 'simple
  authentication' has been verified to work.

* Use TLS for connecting between FreeRADIUS and the LDAP server.  See
  the `tls` sub-section of the default `ldap` module for instructions

* When storing RADIUS user profiles (quotas, `Simultaneous-Use` flags,
  access time restrictions, etc) in LDAP, the LDAP schema
  `doc/schemas/ldap/openldap/freeradius.schema` must first be imported
  into the LDAP server.

== LDAP Module

The `ldap` module supports LDAP queries on to an LDAP database.

NOTE: Fill in how the LDAP module works.
