== Enabling RadSec with FreeRADIUS

Our first task is to set up a RadSec server by configuring an instance of
FreeRADIUS to accept RADIUS over TLS requests.

The following steps should be performed on the `radsecsvr` host.

Install FreeRADIUS using the NetworkRADIUS packages by following the
instructions provided here:

<https://networkradius.com/packages/>

Stop the radiusd service:

[source,shell]
----
 service radiusd stop
----

Enable the `tls` virtual server:

[source,shell]
----
cd /etc/raddb/sites-enabled
ln -s ../sites-available/tls
----

The FreeRADIUS distribution contains an example Certificate Authority that will
have generated the necessary CA, server and client certificates and keys during
package installation.

[TIP]
====
If the example certificates are not present (for example of FreeRADIUS was
installed from source) then FreeRADIUS will fail to start up. They can be
regenerated by running `make` in the `/etc/raddb/certs` directory.
====

Edit the `tls` virtual server configuration to add definitions for the possible
clients by extending the `clients radsec {}` section:

.Example radsec client definitions in `/etc/raddb/sites-available/tls`
====

 clients radsec {
    ...
        # Direct connections from the test client
        client radseccli {
                ipaddr = 172.23.0.2
                proto = tls
                virtual_server = default
        }
        # Connections via HAproxy
        client haproxy {
                ipaddr = 172.23.0.4
                proto = tls
                virtual_server = default
        }
        # Connections via Traefik
        client traefik {
                ipaddr = 172.23.0.5
                proto = tls
                virtual_server = default
        }
 }

====

The client `ipaddr` configuration item is used to match the source IP address
of incoming connections. You must therefore add client definitions for each
of the proxy servers for the case where clients are connected via proxy.

When a proxy server is used FreeRADIUS will treat the proxy server as the
client and its corresponding configuration items will be in effect for all
clients connecting via the proxy. This is the case until PROXY Protocol is
enabled, after which the proxy server's configuration will only be used to
accept the connection. After receiving the original connection data via PROXY
Protocol the indicated client's definition will be used, allowing you to
configure distinct `virtual_servers` to handle requests for each end client.

In the case that a client using a proxy with PROXY Protocol enabled is unknown,
the connection will be immediately closed.


[NOTE]
====
The RadSec protocol always uses the shared secret "radsec" which does not need
to be provided since it is the default.
====

For testing purposes, we want to amend the `default` virtual server so that it
unconditionally accepts authenticaiton reqeusts and immediately responds to
accounting requests.

Amending the `/etc/raddb/sites-enabled/default` file such that the beginning of
the `authorize` and `preacct` sections is as follows:

.Example default virtual server modification to unconditionally accept Access-Requests
====

 authorize {
     accept
     ...
 }
 ...
 preacct {
     handled
     ...
 }

====

Start the FreeRADIUS service in the foreground with debugging enabled:

[source,shell]
----
radiusd -fxxl /dev/stdout
----

Examine the output from FreeRADIUS to ensure that it is now listening for
RadSec connection on TCP/2083:

.Example output from running `radiusd -fxxl /dev/stdout`
====

 FreeRADIUS Version 3.0.24
 Copyright (C) 1999-2021 The FreeRADIUS server project and contributors
 ...
 ... : Debug: Listening on auth+acct proto tcp address * port 2083 (TLS) bound to server default
 ... : Debug: Listening on auth address * port 1812 bound to server default
 ... : Debug: Listening on acct address * port 1813 bound to server default
 ... : Debug: Listening on auth address :: port 1812 bound to server default
 ... : Debug: Listening on acct address :: port 1813 bound to server default
 ...
 ... : Info: Ready to process requests

====

FreeRADIUS is now ready to process RadSec traffic, but PROXY Protocol is not
yet enabled.

Our strategy is to first test basic RADIUS over UDP functionality, then
exercise the RadSec connection using a test client, then introduce a proxy
server, and finally enable PROXY Protocol.


=== Testing the RADIUS policy

Before moving on, verify that the FreeRADIUS policy is able to authenticate a
local test RADIUS Access-Request over UDP:

[source,shell]
----
echo "User-Name = terry" | radclient 127.0.0.1 auth testing123
----

Due to the test policy modification made above the expected output should
indicate that an Access-Accept is received:

.Expected output from radclient
===============================

 Sent Access-Request Id 157 from 0.0.0.0:36850 to 127.0.0.1:1812 length 27
 Received Access-Accept Id 157 from 127.0.0.1:1812 to 127.0.0.1:36850 length 20

===============================

Any other output indicates that there is a problem with the FreeRADIUS
configuration which must be solved before testing RadSec. Carefully verify that
you have carried out each of the above steps correctly and examine the debug
output from FreeRADIUS which will usually tell you what is wrong.

Now we must xref:protocols/proxy/radsec_client.adoc[configure FreeRADIUS as a
RadSec test client] so that we can verify that our RadSec server is working
properly.
