== Configuring FreeRADIUS as a RadSec test client

The FreeRADIUS client utilities do not directly support making RadSec
connections. We must therefore configure an instance FreeRADIUS as a transport
converter that proxies UDP-based RADIUS requests to a RadSec destination of our
choice.

The following steps should be performed on the `radseccli` host.

Install FreeRADIUS using the NetworkRADIUS packages by following the
instructions provided here:

<https://networkradius.com/packages/>

Stop the radiusd service:

[source,shell]
----
 service radiusd stop
----

Add a new `tls` homeserver definition that we will initially point directly to
our FreeRADIUS RadSec server by creating a file
`/etc/raddb/sites-enabled/radsec-homeserver` with the following contents:

.Example homeserver, pool and realm definitions for the RadSec service
====

 home_server tls {
         ipaddr = 172.23.0.3    # Initially directly to our RadSec server
         port = 2083
         type = auth+acct
         proto = tcp
         tls {
             private_key_password = whatever
             private_key_file = ${certdir}/client.pem
             certificate_file = ${certdir}/client.pem
             ca_file = ${cadir}/ca.pem
          }
 }
 home_server_pool tls {
         type = fail-over
         home_server = tls
 }
 realm tls {
         auth_pool = tls
         acct_pool = tls
 }

====

[TIP]
====
Descriptions of each of the above configuration items can be found in the
`[raddb]/sites-available/tls` example site, however for testing purposes the
above will suffice.
====

To use this `tls` homeserver we modify the `default` virtual server to proxy
all authentication and accounting requests by amending the
`/etc/raddb/sites-enabled/default` file such that the beginning of the
`authorize` and `preacct` sections is as follows:

.Example default virtual server modification to proxy requests to a RadSec proxy server
====

 authorize {
     update control {
         &Proxy-To-Realm := tls
     }
     handled
     ...
 }
 ...
 preacct {
     update control {
         &Proxy-To-Realm := tls
     }
     handled
     ...
 }

====

We must now copy the example CA certificate as well as the client certificate
and key files that were generated automatically during the installation of
FreeRADIUS on the `radsecsrv` host to this test client.

Replace the following files on `radseccli` with the equivalent files from
`radsecsrv`:

[cols="1,1,1"]
|===
|File|Corresponding configuration item|Purpose

|/etc/raddb/certs/ca.pem
|`ca_file`
|CA certificate that is used to authenticate the server certificate presented to the client by the RadSec server

|/etc/raddb/certs/client.pem
|`certificate_file`
|Client certificate (signed by the CA certificate) that is presented by the test client to the RadSec server

|/etc/raddb/certs/client.pem
|`private_key_file` and `private_key_password`
|Private key corresponding to the client certificate
|===

Note that the client certificate and key are bundled into a single file.

[CAUTION]
====
If you do not correctly replace the CA and client certificate and key material
on the test client then the RadSec client and RadSec server will fail to
mutually authenticate each other since they will not be operating under the
same CA.
====

Start the FreeRADIUS service in debug mode:

[source,shell]
----
radiusd -X
----


=== Testing RadSec connectivity

At this stage you should be able to cause the test client to send RadSec
requests directly to the RadSec server.

Run the following to send a RADUS (UDP) Access-Request to the local FreeRADIUS
instance which should proxy the request by making a RadSec connection to
the remote RadSec server:

[source,shell]
----
 echo "User-Name = bob" | radclient 127.0.0.1 auth testing123
----

If the test client is able to successfully establish the RadSec connection and
the RadSec server replies with an Access-Accept response then the output will
be as follows:

.Expected output from radclient
===============================

 Sent Access-Request Id 252 from 0.0.0.0:50118 to 127.0.0.1:1812 length 27
 Received Access-Accept Id 252 from 127.0.0.1:1812 to 127.0.0.1:50118 length 39

===============================

Lack of response or an Access-Reject response indicates that the RadSec
connection is not being established successfully.

There may be serveral reasons for broken connectivity including:

  * The client not accepting the certificate presented by the server.
  * The server not accepting the certificate presented by the client.

Look at the debug output generated by both the test client and the RadSec
server. In many cases it will tell you exactly what the problem is.

Do not proceed with any further steps until direct connections between the
RadSec client and FreeRADIUS are working properly.

Once things are working we are ready to
xref:protocols/proxy/radsec_with_haproxy.adoc[configure HAproxy to proxy RadSec
connections] or to xref:protocols/proxy/radsec_with_traefik.adoc[configure
Traefik to proxy RadSec connections].

