= Accounting Requests


*Goal*: To send the server accounting requests and to have the server
log the accounting requests.

*Time:* 20-30 minutes

In addition to authorization and authentication, one of the primary roles of a
RADIUS server is to record accounting information supplied by an NAS. In this
exercise, you should create accounting requests to send to the server and see what
the server does with those requests. This process simulates the actions taken by
an NAS when a user logs in.

Use the entry in the file from the exercise in
xref:new_user.adoc[New User] for user "bob".


== Authenticate the user

Before sending accounting packets, the user must first be authenticated. This step ensures that the server recognizes the user and permits them to access the network. We will use the `radclient` command to simulate a Network Access Server (NAS) sending an `Access-Request`.

You can choose between two common authentication methods: PAP or CHAP. If you are a beginner, we recommend starting with PAP.

**Option A – Using PAP (Recommended)**

[source]
----
echo 'User-Name = "bob"
User-Password = "hello"
NAS-IP-Address = 127.0.0.1
NAS-Port = 501
Service-Type = Framed-User
Framed-Protocol = PPP' | radclient -x 127.0.0.1:1812 auth testing123
----

**Option B – Using CHAP**

[source]
----
echo 'User-Name = "bob"
CHAP-Password = "RPWZI373P"
NAS-IP-Address = 127.0.0.1
NAS-Port = 501
Service-Type = Framed-User
Framed-Protocol = PPP' | radclient -x 127.0.0.1:1812 auth testing123
----

Run the command for the method you prefer. If successful, you should see the following in your terminal and server logs.

=== Server debug output

When the server receives the packet, it will look up the user in its configuration files. You should see output similar to this:

----
(0)          files - | --> bob
(0)      files - files - Looking for key "bob"
...
(0)      pap - User authenticated successfully
(0)      pap (ok)
----

=== Radclient output

On the client side, `radclient` will display the response from the server:

----
Received Access-Accept Id 96 from 127.0.0.1:1812 ...
        Reply-Message = "Hello, bob! Basic access granted."
        Framed-Protocol = ::PPP
        Service-Type = ::Framed-User
        Framed-IP-Address = 192.168.10.12
        User-Name = "bob"
----

The `Access-Accept` message confirms that the user "bob" is now authenticated.

Observe that both programs do not report user "bob" as being logged in.

Now run the `bob-acct-start.sh` script, and observe the response of the server.
You should see output containing lines similar to the following:

-----------------------------------------------------------------------------------
(0) Received Accounting-Request packet from host 127.0.0.1 port 57470, id=35, length=53
(0) 	User-Name = 'bob'
(0) 	Acct-Status-Type = Start
(0) 	Acct-Session-Id = '01020304'
(0) 	NAS-IP-Address = 127.0.0.1
(0) 	NAS-Port = 501
(0) # Executing section preacct from file /etc/raddb/sites-enabled/default
(0)   preacct {
(0)   [preprocess] = ok
-----------------------------------------------------------------------------------

Other modules that should be referenced for "accounting" are the
"preprocess", "suffix", "detail", and "sql" modules. We
will work through the operation of these modules in a moment.

Now, run the `radwho` and `radlast` programs again:

[source]
---------
$ radwho
$ radlast
---------

Observe that both programs now see "bob" as being logged in.

To tell the server that user "bob" has logged out, run the `bob-acct-stop.sh`
script. Observe the server output, and then run `radwho` and `radlast` again.

The `radwho` program should not display any logged-in users. The `radlast`
program should now display both the last login time and the last logout time for
user "bob".

Now run the `bob-acct-stop.sh` program again. Observe how the server's output
differs from the previous accounting stop packet.

You should now read the `man` pages for the rlm_unix, rlm_radutmp, and
rlm_unix modules, along with their configuration entries in
`raddb/mods-available/radutmp` and `raddb/mods-available/unix`.

In short, the "unix" module manages the database used by the `radlast`
command. The "radutmp" module manages a separate database, which is used by
the `radwho` command.

The "detail" module simply logs every accounting request to a file in a simple
textual format.

== Questions

1.  Why do accounting messages require less configuration of the server
than authentication methods?
2.  Why is the "detail" module useful?
3.  Where is the "detail" file located? Why is the "detail" file in this location? Where is it configured?
4.  What parts of the servers manage user session information?
5.  What module other than "radutmp" can manage user session
information?
6.  Why is it useful to record which users are currently logged in?
7.  What attributes that are found in the accounting request are not found in the
authentication request? Why?
8.  Which attributes are required to be in an accounting request?
9.  What error message is produced on the second accounting stop, and
why is it produced?

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
