= Matching entries in the users file

*Goal:* To configure multiple entries for a user in the "users" file
and to validate the server's configuration by sending test packets to
exercise the new entries.

*Time:* 30-45 minutes.

Now that we have verified that we can add a simple entry to the file, we
will try more complex configurations.

In this exercise, we will add three configuration entries for a user
named "bob" with clear-text password "hello". The three entries are
related as follows:


== Exercise 1: Basic Configuration (Entry 1)

The first step is to configure user "bob" with password "hello". It will configure a reply message in an appropriate attribute. This configuration entry will cause the server to continue processing the file.

Add the following configuration to `raddb/mods-config/files/authorize`:

[source,text]
----
# Entry 1: Basic "bob" with password and reply message, continue processing
bob     Password.Cleartext := "hello"
        Reply-Message = "Hello, bob! Basic access granted.",
        Fall-Through = Yes
----

Execute the following command to test this configuration:

[source,bash]
----
echo -e 'User-Name = "bob"\nUser-Password = "hello"' | ./scripts/bin/radclient -x 127.0.0.1 auth testing123
----

The debug log should show the server matching the entry and preparing the reply attributes:

[source,text]
----
(0)      files - files - Preparing attribute updates:
(0)        files - Password.Cleartext := hello
(0)        files - Reply-Message = Hello, bob! Basic access granted.
(0)      files (ok)
----

The client should receive an `Access-Accept` packet with the expected `Reply-Message`:

[source,text]
----
Sent Access-Request Id 50 from 0.0.0.0:55490 to 127.0.0.1:1812 length 61
	Message-Authenticator = 0x
        User-Name = "bob"
        User-Password = "hello"
Received Access-Accept Id 50 from 127.0.0.1:1812 to 0.0.0.0:55490 via lo length 78
        Message-Authenticator = 0xeb6112615d97252ff1dae0d4f6eaa437
        Reply-Message = "Hello, bob! Basic access granted."
        User-Name = "bob"
----

== Questions

1.  What is the difference between the Framed-Route and Framed-Routing
Attributes?
2.  What is the Framed-IP-Netmask attribute used for?
3.  What are potential pitfalls with the entry 2? That is, the entry
meets the requirements, but do the requirements fit the needs of the
network?
4.  How does this kind of simple configuration scale to many users?

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
