= Configuring a server to send and receive proxy requests

**Goal:** Configure the server to handle local authentication and proxy requests to different remote RADIUS servers based on realm suffix.

**Time:** 20-30 minutes

*Files to create / edit:*

- `mods-available/proxy-realm1`
- `mods-available/proxy-realm2`
- `mods-enabled/proxy-realm1` (symlink)
- `mods-enabled/proxy-realm2` (symlink)
- `clients.conf`
- `sites-enabled/default`

== Overview

This guide shows how to:

* Authenticate `bob` locally using the `files` module
* Proxy `bob@realm1.com` to remote server 1
* Proxy `bob@realm2.com` to remote server 2

For this exercise, the users will be divided into groups of two using `realm` they use. One
realms will be named "realm1" and the other will be named "realm2".

We assume two remote servers exist with IP addresses you will replace in the `clients.conf` configuration.

== Step-by-step Configuration

=== 1. Create proxy modules.

Create file `mods-available/proxy-realm1`

[source,unlang]
----
# Proxies requests for @realm1.com to remote server 1

radius proxy-realm1 {
    mode = proxy
    transport = udp

    udp {
        # replace with real IP of realm1 server
        ipaddr = 192.168.100.51
        port   = 1812
        secret = testing123
    }

    type = Access-Request
    type = Accounting-Request

    status_check = none

    connect_timeout  = 3.0
    response_timeout = 3.0
    zombie_period    = 40
}
----

Create file `mods-available/proxy-realm2`

[source,unlang]
----
# Proxies requests for @realm2.com to remote server 2

radius proxy-realm2 {
    mode = proxy
    transport = udp

    udp {
        # replace with real IP of realm2 server
        ipaddr = 192.168.100.52
        port   = 1812
        secret = testing123
    }

    type = Access-Request
    type = Accounting-Request

    status_check = none

    connect_timeout  = 3.0
    response_timeout = 3.0
    zombie_period    = 40
}
----

Enable both modules:

[source,bash]
----
$ cd ../mods-enabled
$ ln -s ../mods-available/proxy-realm1 .
$ ln -s ../mods-available/proxy-realm2 .
----

=== 2. Register remote servers as clients

Edit `clients.conf` and add:

[source]
----
client realm1_remote {
    # same IP as proxy-realm1
    ipaddr = 192.168.100.51
    secret = testing123
    shortname = realm1-server
    nas_type = other
}

client realm2_remote {
    # same IP as proxy-realm2
    ipaddr = 192.168.100.52
    secret = testing123
    shortname = realm2-server
    nas_type = other
}
----

=== 3. Update virtual server logic

Edit `sites-enabled/default`

Update the `recv Access-Request { … }` section:

[source,unlang]
----
recv Access-Request {
    if (&User-Name =~ /@realm1\.com$/) {
        proxy-realm1

        if (ok) {
            accept
        }
    }
    elsif (&User-Name =~ /@realm2\.com$/) {
        proxy-realm2

        if (ok) {
            accept
        }
    }
    else {
        files
        pap        
    }
}
----

Update (or add) the `authenticate` section:

[source,unlang]
----
authenticate PAP {
        pap
    }

authenticate proxy-realm1 {
        proxy-realm1
    }

authenticate proxy-realm2 {
        proxy-realm2
    }

----

=== 4. Ensure local user exists

In `mods-config/files/authorize` (or your users file):

[source,text]
----
bob     Cleartext-Password := "hello"
----


== Questions

1.  Why is it necessary for each server to mark some realms as local?
2.  What would happen if each user did not configure the other RADIUS
server in the `clients.conf` file?
3.  What would happen if each user did not configure the realms to
"strip" the realm from the proxied requests?

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
