= Configuring a server to proxy requests

*Goal:* To configure the server to proxy packets to a remote (home)
RADIUS server and to perform test authentications against both the
proxy server and the home server.

*Time:* 15–25 minutes

*Files:*

- `mods-enabled/proxy-realm1`
- `sites-enabled/default`

*Diagram:*

image::access-request-proxy.svg[Fig. Proxy]

We assume:

- You already have a working *second FreeRADIUS server* (the "home" server) running on another machine / IP.
- It accepts authentication on port 1812 with a known shared secret.
- It can authenticate users like `bob` with password `hello`.

Configure your (proxy) server to:

- Handle local users itself (e.g. `bob`)
- Proxy users in `@realm1` (e.g. `bob@realm1.com`) to the remote home server. The home server should be configured to authenticate the user with the full `User-Name` (e.g., `bob@realm1.com`) and the provided password.

For this exercise, you will configure a RADIUS server to proxy requests to a home RADIUS server that is run by another user.

You will configure a realm, called "realm1", by creating a new module instance in `mods-available/proxy-realm1`. This module will point to the RADIUS server administered by another user (the "uber user"), who will supply the IP address, port, and shared secret.

The entry for the user "bob" from the xref:new_user.adoc[New User] exercise, typically located in `mods-config/files/authorize`, will be used here.

You can use the `radclient` commands shown in the testing section to simulate the authentication requests.

First, you should verify that authentication requests for user "bob" are handled locally and result in an `Access-Accept` without being forwarded. Then, you should attempt an authentication request for `bob@realm1.com`, which should be proxied to the home server.

Once proxying is verified, the home server will be halted. You should then re-attempt the `bob@realm1.com` request and observe how the proxy server behaves when the home server does not respond.


== Step 1. Create the proxy module instance (pointing to your home server)

Create this file: `mods-available/proxy-realm1`

[source,text]
----
radius proxy-realm1 {
    mode = proxy

    transport = udp

    udp {
        ipaddr = 192.168.50.200
        port   = 1812
        secret = testing123secret
    }

    # What packets to proxy
    type = Access-Request
    type = Accounting-Request

    # Remove @realm1 before sending to home server
    replicate = no

    # What to do if home server does not reply
    status_check = none

    # Optional timeouts (seconds)
    connect_timeout = 3.0
    response_timeout = 3.0
    zombie_period = 40
}
----

Change the `mods-enabled/proxy-realm1` file permission accordingly.

[source,text]
----
$ cd mods-enabled
$ ln -s ../mods-available/proxy-realm1 proxy-realm1
----

== Step 2. Modify the virtual server to decide when to proxy

Edit `sites-enabled/default`

Find the `recv Access-Request { … }` block.

[source,unlang]
----
recv Access-Request {
    if (User-Name =~ /@realm1\.com$/) {
        proxy-realm1

        # Accept the proxied result and stop processing
        if (ok) {
            accept
        }
    }
    else {
        files
        pap
    }
}
----

Then, near the bottom of the file, in the `authenticate { … }` section, add:

[source,unlang]
----
authenticate  proxy-realm1 {
        proxy-realm1
    }
----
