= Editing Attributes

*Goal:* To explore uses of update blocks in the policy language

*Time:* 10-25 minutes

*File:*

- `raddb/sites-available/default`

*Documentation pages:*

- xref:reference:unlang/condition/index.adoc[Conditions]
- xref:reference:unlang/index.adoc[Unlang Policy Language]

Since the files are not used please comment the files inside raddb/sites-enabled/default

[text]
----
recv Access-Request {
#   files
}
----

For this tutorial, you should start with an empty authorization section (`recv Access-Request { ... }`) in the virtual server you're using to process requests.

Attributes in the control list can control the behaviour of the server. Common control attributes:

For example:

* Reply.Framed-IP-Address
* Control.Password.Cleartext

Please refer to xref:reference:unlang/list.adoc[attribute lists] for more information

Unlang `update` blocks are used to update one or attributes in one
of the server's xref:reference:unlang/list.adoc[attribute lists].

In previous tutorials, we've used the `files` module, and the authorize
methods of authentication modules such as `pap` and `chap` to alter how
the server processes requests by setting an `Auth-Type` value.
Here, we will emulate that behaviour using the policy language.

* Create a condition (_condition 1_) to execute policy code if
the `User-Name` in the request is 'bob'.
* Within that condition block, set the control attribute `Password.Cleartext`
to be 'hello', and instruct the server to run the `authenticate { ... }`
subsection for `pap`.

== Condition 1

For testing purposes, edit the following file:

[source,shell]
----
$ vi raddb/sites-enabled/default
----

[text]
----
server default {
    recv Access-Request {
        # Condition 1
        if (User-Name == "bob") {
        Control.Password.Cleartext := "hello"
        }
    }
}
----
We have defined the cleartext password for the user `bob` here, instead of defining it in `raddb/mods-config/files/authorize`, as usual.

Execute the following command to test this configuration:
[source,text]
----
echo -e 'User-Name = "bob",
User-Password = "hello"' | radclient -x 127.0.0.1 auth testing123
----

After executing, verify that you see an Access-Accept returned despite the files module not being called.

=== Debug Log Response

[text]
----
(0)    Running 'recv Access-Request' from file ./scripts/bin/../../raddb/sites-enabled/default
(0)    recv Access-Request {
(0)      if ( User-Name == "bob" )  {
(0)        | ==
(0)            | User-Name
(0)              | %{User-Name}
(0)              | --> bob
(0)        | ({bob} == {bob})
(0)        | --> true
(0)        Control.Password.Cleartext := "hello"
(0)      }
----

=== Server Response

[text]
----
Sent Access-Request Id 84 from 0.0.0.0:54238 to 127.0.0.1:1812 length 61
	Message-Authenticator = 0x
        User-Name = "bob"
        User-Password = "hello"
Received Access-Accept Id 84 from 127.0.0.1:1812 to 0.0.0.0:54238 via lo length 43
        Message-Authenticator = 0x6bdd99181d25a5c61b7577815379d877
        User-Name = "bob"
----

Using additional conditions and update blocks, emulate the logic implemented using the files module in the xref:matching_users.adoc[Matching Users] exercise.

* If an incoming request contains a `User-Name` attribute with the value
  'bob', and contains an attribute `Framed-Protocol` with value `PPP`
  (_condition 2_), reply with a `Framed-IP-Address` attribute with the value
  `192.168.10.12`.

== Condition 2
For testing purposes, edit the following file:
[source,shell]
----
$ vi raddb/sites-enabled/default
----

[text]
----
server default {
    recv Access-Request {
        # Condition 1
        if ( User-Name == "bob" ) {
            Control.Password.Cleartext := "hello"
        # Condition 2
        if  (Framed-Protocol == "PPP" ){
                Reply.Framed-IP-Address := "192.168.10.12"
            }
        }
        }
    }
----

Execute the following command to test this configuration:

[source,text]
----
echo -e 'User-Name = "bob",
User-Password = "hello",
Framed-Protocol = "PPP"' | radclient -x 127.0.0.1 auth testing123
----

After executing, verify that you see an Access-Accept returned despite the files module not being called.

=== Debug Log Response

[text]
----
(0)    Running 'recv Access-Request' from file ./scripts/bin/../../raddb/sites-enabled/default
(0)    recv Access-Request {
(0)      if ( User-Name == "bob" )  {
(0)        | ==
(0)            | User-Name
(0)              | %{User-Name}
(0)              | --> bob
(0)        | ({bob} == {bob})
(0)        | --> true
(0)        Control.Password.Cleartext := "hello"
(0)        if (Framed-Protocol == "PPP" ) {
(0)          | ==
(0)              | Framed-Protocol
(0)                | %{Framed-Protocol}
(0)                | --> PPP
(0)          | ({PPP} == {PPP})
(0)          | --> true
(0)          Reply.Framed-IP-Address := 192.168.10.12
(0)        }
----

=== Server Response

[text]
----
Sent Access-Request Id 237 from 0.0.0.0:53537 to 127.0.0.1:1812 length 67
	Message-Authenticator = 0x
        User-Name = "bob"
        User-Password = "hello"
        Framed-Protocol = ::PPP
Received Access-Accept Id 237 from 127.0.0.1:1812 to 0.0.0.0:53537 via lo length 49
        Message-Authenticator = 0xcaf8041bd61de3debf77bb7d1fbcddd9
        Framed-IP-Address = 192.168.10.12
        User-Name = "bob"
----
