= Policies

*Goal:* Create and use policies to abstract and reuse business logic in FreeRADIUS.

*Time:* 10-20 minutes

*Files / Directories:*

- `etc/raddb/policy.d/*`   (policy.d where we create and define policies)
- `etc/raddb/sites-available/default`  (virtual server where we call the policy)

*Related man page:* `man unlang`

== Preparation

Look through the existing files in `etc/raddb/policy.d/` and review other documentation sections (especially the unlang reference, conditions, and regular expressions) to become familiar with:

- Policy syntax
- Attribute references (`request.`, `control.`, `reply.`, etc.)
- Regular expression matching in `if` conditions
- Common update operators (`:=`, `+=`, etc.)

Policies are named blocks of unlang code that can be called almost anywhere a module can be called.

Basic structure of a policy:

------------------------------------------------
a_policy {
	if (User-Name =~ /@([\w.+])/) {
		reply.Reply-Message := "Hello remote %{User-Name}"
	}
}
------------------------------------------------

Policies defined within `etc/raddb/policy.d/*` can be called from
anywhere in the server where modules can be called.

------------------------------------------------
authorize {
	...
	a_policy
	...
}
------------------------------------------------

Create a policy `proxy_to_realm` that forwards the incoming request
to to a remote realm if the `User-Name` attribute ends in `@<remote realm>`.

The contents of this policy should be identical to the the 'unlang'
code written for the xref:unlang_splitting_strings.adoc[Splitting Strings]
tutorial.

Call this policy at the start of the `authorize {}` section of the
`etc/raddb/sites-available/default` virtual server.

All the information you need to create this policy is contained within
documentation pages and the examples in this exercise.

== Questions

1.  What are the advantages of using the policy language over interpreted
    language modules?
2.  What are the main differences between a policy and a function in other
    languages?

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
