= Editing Attributes

*Goal:* To explore uses of update blocks in the policy language

*Time:* 10-25 minutes

*File:*

- `raddb/sites-available/default`

*Documentation pages:*

- xref:reference:unlang/condition/index.adoc[Conditions]
- xref:reference:unlang/index.adoc[Unlang Policy Language]

Since the files are not used please comment the files inside raddb/sites-enabled/default

[text]
----
recv Access-Request {
#   files
}
----

For this tutorial, you should start with an empty authorization section (`recv Access-Request { ... }`) in the virtual server you're using to process requests.

Attributes in the control list can control the behaviour of the server. Common control attributes:

For example:

* Reply.Framed-IP-Address
* Control.Password.Cleartext

Please refer to xref:reference:unlang/list.adoc[attribute lists] for more information

Unlang `update` blocks are used to update one or attributes in one
of the server's xref:reference:unlang/list.adoc[attribute lists].

In previous tutorials, we've used the `files` module, and the authorize
methods of authentication modules such as `pap` and `chap` to alter how
the server processes requests by setting an `Auth-Type` value.
Here, we will emulate that behaviour using the policy language.

* Create a condition (_condition 1_) to execute policy code if
the `User-Name` in the request is 'bob'.
* Within that condition block, set the control attribute `Password.Cleartext`
to be 'hello', and instruct the server to run the `authenticate { ... }`
subsection for `pap`.
