= Virtual Servers

*Goal:* To understand how to create and use a new virtual server.

*Time:* 20-30 minutes

*File:*

- `sites-enabled/virtual`
- `sites-available/virtual`


A `virtual server` is a configuration file that contains sections which process packets. They can also include listen sections, along with a few others.

- *listen* Defines a new socket.
- *recv Access-Request* - Run policies when receiving an `Access-Request` packet
- *authenticate <name>* - Run an authentication method
- *send Access-Accept* - Run policies when sending an `Access-Request`
- *send Access-Reject* - Run policies when sending an `Access-Reject`
- *send Access-Challenge* - Run policies when sending an `Access-Challenge`
- *recv Accounting-Request* - Run policies when receiving an `Accounting-Request` packet
- *accounting <type>* - Run policies for a particular value of `Acct-Status-Type`
- *send Accounting-Response* - Run policies when receiving an `Accounting-Response` packet

**Default behavior:**  All site configurations are stored in the sites-available directory, while only the active (running) sites are present in sites-enabled. To activate a site, a symbolic link must be created in sites-enabled that points to the corresponding configuration in sites-available.

**Best practice:**  Always create or modify site configurations in sites-available, and then enable them by creating a symbolic link in sites-enabled.


Create a new file `raddb/sites-enabled/virtual`. Put the following text
into it:

-----------------------------------------------
listen {
    ipaddr = 127.0.0.1
    port = 18273   # some random 5 digit number
    type = auth
}

authorize {
    control.Clearext-Password := "hello"
    pap
}

authenticate {
    pap
}
-----------------------------------------------

Start the server in debugging mode, and use `radtest` to send a PAP
authentication request to the server at the port defined above.

== Questions

1.  What happens when you try to use CHAP or MS-CHAP? Why does this result occur?
2.  How can you make that virtual server use CHAP or MS-CHAP?
3.  What happens when you try different User-Names? Why does this result occur?
4.  How can you make the above configuration authenticate different
users via different passwords?

// Copyright (C) 2021 Network RADIUS SAS.  Licenced under CC-by-NC 4.0.
// This documentation was developed by Network RADIUS SAS.
