.TH RADUSE 1 "24 February 2001" "" "FreeRADIUS Daemon"
.SH NAME
raduse -- Shows the usage of the modem lines on a terminal server.
.SH SYNOPSIS
.B raduse
.RB [ \-w ]
.RB [ \-o
.IR offset ]
.I terminal-server
.SH DESCRIPTION
\fBraduse\fP shows the usage of the modem lines on a terminal server.
This program gets its info from the radwtmp file, which
can be very slow on larger servers, and the data from the
radwtmp file can't be trusted 100% either.
.PP
It is deprecated and not documented very well. Don't use it.
.SH OPTIONS
.IP \-w
Wide output format
.IP "\-o \fIoffset\fP"
Start showing nas-port from this offset.
.IP terminal-server
The NAS to show.
.SH SEE ALSO
radiusd(8),
wtmp(5),
last(1).
.SH AUTHOR
Miquel van Smoorenburg, miquels@cistron.nl.
