.TH RADWHO 1 "23 February 2001" "" "FreeRADIUS Daemon"
.SH NAME
radwho - show online users
.SH SYNOPSIS
.B radwho
.RB [ \-c ]
.RB [ \-d
.IR raddb_directory ]
.RB [ \-f ]
.RB [ \-i ]
.RB [ \-n ]
.RB [ \-p ]
.RB [ \-r ]
.RB [ \-s ]
.RB [ \-S ]
.SH DESCRIPTION
The FreeRADIUS server can be configured to maintain an active session
database in a file called \fIradutmp\fP. This utility shows the
content of that session database.
.SH OPTIONS
.IP \-c
Shows caller ID (if available) instead of the full name.
.IP \-d\ \fIraddb_directory\fP
The directory that contains the RADIUS configuration files. Defaults to
\fI/etc/raddb\fP.
.IP \-f
Behave as the 'fingerd' daemon - waits for one line of input, then
prints the output with lines \\r\\n terminated.
.IP \-i
Shows the session ID instead of the full name.
.IP \-n
Normally radwho looks up the username in the systems password file,
and shows the full username as well. The \fB-n\fP flags prevents this.
.IP \-p
Adds an extra column for the port type - I for ISDN, A for Analog.
.IP \-r
Outputs all data in \fIraw\fP format - no headers, no formatting,
fields are comma-seperated.
.IP \-s
Show full name.
.IP \-S
Hide shell users. Doesn't show the entries for users that do not
have a SLIP or PPP session.

.SH SEE ALSO
radiusd(8).
.SH AUTHOR
Miquel van Smoorenburg, miquels@cistron.nl.

.SH SEE ALSO
radiusd(8),
radiusd.conf(5),
wtmp(5),
last(1).
.SH AUTHOR
Miquel van Smoorenburg, miquels@cistron.nl.
