After configuring the module, the server should be tested again
via the following command:

[source,shell]
----
radiusd -XC
----

When the configuration is correct, then the server will print the
following message:

[source,log]
----
Configuration appears to be OK
----

Note that this test checks only that the configuration files can be
parsed.  It does not check that the module works correctly when
packets are received.

When the configuration is correct, FreeRADIUS can then be started in debugging mode:

[source,shell]
----
radiusd -X
----

If the module has been configured correctly, the final (or almost
final) message will be

[source,log]
----
Ready to process requests
----

This message should be in bold on the console.  Depending on which
other modules are enabled, there may be a small number messages after
this one.

If the server starts, then the next step is then to perform
run-time tests.

=== Errors

If the `Ready to process requests` message does not appear, then the
debug output will contain error messages clearly describing what went
wrong.  These error message *must* be read in order to gain insight as
to the source of the problem.

Otherwise, look for messages containing `ERROR` or `WARNING`, or
the module name.  While the server can produce a large volume of
messages, most of those can be ignored when debugging a particular
problem.  Simply search for a few key strings based on the files you
changed, and the solution to the problem should be clear.

We recommend running the `radiusd -XC` test was performed before
making any module changes for other reasons.  If previous
configuration worked, and the only change was to a particular module,
then the source of the error is simple.  There is no need to go
searching through other configuration files or third-party web sites.
Instead, change and test the module configuration until the server
works.
