#!/usr/bin/env perl
#
#  $Id$
#
#  Convert conf files to Asciidoc
#
#
use File::Basename;

$was_raw = 0;
$raw = 0;
$blank = 0;

$script_dir = dirname(__FILE__);
$filename = "$script_dir/links.txt";

%links = {};

#
#  Read the links file.
#
#  @todo - have this script take multiple inputs, so that we don't
#  have to read the links file on every file we convert.
#
open FILE, "<$filename" or die "Failed to open $filename: $!\n";
while (<FILE>) {
    chop;
    ($name, $link) = split;
    
    $links{$name} = $link;
}
close FILE;

while (<>) {
    #
    #  Skip editor commands
    #
    if (/^# -\*- text -\*-/) {
	next;
    }

    if (/\$Id: /) {
	next;
    }

    # Skip ###### banners
    if (/^##+$/) {
	next;
    }

    # Print one line of blank text, but suppress multiple blank lines.
    if (/^\s*$/) {
	print "\n" if (!$blank);
	$blank = 1;
	next;
    }

    $blank = 0;

    undef $prefix;

    #
    #  Commented-out config blocks get converted to commented out raw text.
    #
    if (/^#[\t]/ || /^#[^\s]/) {
	$raw = 1;
#	print "R";

    #
    #  Comments in the configuration files get converted to plain
    #  text.
    #
    } elsif (/^\s*#/) {
	s/^\s*#[\t ]{0,2}//;

#	print "T";

	#
	#  Ensure that lists get formatted correctly
	#
	if (/^\s*\*/) {
	    $prefix = "  ";
	}

	$raw = 0;

    } else {
	$raw = 1;

#	print "C";
    }

    if ($raw != $was_raw) {
	print "```\n";
	$was_raw = $raw;
    }

    print $prefix if defined $prefix;

    $line = $_;

    my @words = split;

    #
    #  See if we can automagically make cross-links
    #
    foreach $word (@words) {
	next if ($word eq '\`\`\`');

	next if ($word !~ /^`(.*)`$/);

	#
	#  @todo - automatically add cross-links for:
	#
	#	mods-available/
	#	sites-available/
	#
	#  etc.
	#
	
	next if (!$links{$1});

	$link = "`link:" . $links{$1} . "[" . $1 . "]`";

	#
	#  Yes, this is terrible.  We should really just print each
	#  word individually, but that would also mess up (mildly)
	#  whitespace.
	#
	$line =~ s/$1/$link/g;
    }

    #
    #  And print out the raw text.
    #
    print $line;
}

