= rlm_python

Python module for freeradius Copyright 2002 Miguel A Paraz
mailto:mparaz@mparaz.com[mparaz@mparaz.com] Copyright 2002
Imperium Technology, Inc.

== Topics

PURPOSE: To allow module writers to write modules in a high-level
language, for implementation or for prototyping.

REQUIRES: Python - tested with 2.2

BUILDING: ./configure –with-experimental-modules

USAGE: Make your module available to the Python interpreter by either
putting it in a standard location, or `EXPORT PYTHONPATH=$location'.

BUGS: 1. Can’t compile statically (./configure –enable-shared=no) -
causes SIGSEGV on the first malloc() in main().

Design: 1. Support for all module functions. 2. One module per function
allowed, for example, from experimental.conf:

```
python {
    mod_instantiate = radiusd_test
    func_instantiate = instantiate

    mod_authorize = radiusd_test
    func_authorize = authorize

    mod_accounting = radiusd_test
    func_accounting = accounting

    mod_preacct = radiusd_test
    func_preacct = preacct

    mod_detach = radiusd_test
    func_detach = detach

}
```

* Different functions are wrappers around the same core.
* `func_detach` is passed no parameters, returns module return value.
* If functions returns None (plain `return' no return), default to
RLM_OK
* Python instantiation function can return -1 to signal failure and abort
startup.

Available to module:

```
import radiusd
radiusd.rad_log(radiusd.L_XXX, message_string)
radiusd.RLM_XXX
```

## Example

We will be writing a script that allows every user to login with the password "hello", and add a reply message to show the user he has been authenticated using python

### Setup

Starting with a completely clean config, first enable `rlm_python` by creating a symlink to `mods-available/python` from `mods-enabled/`. Edit this file, make sure it has the following config:

    python {
      module = example
    
      python_path = ${modconfdir}/${.:name}
    
      mod_authorize = ${.module}
      func_authorize = authorize
    }

(At the moment, every function that you want to used has to be enabled manually, this might change in future version).

Next, enable python in `sites-enabled/default` in the section `authorize`. Added a line with just `python` between `auth_log` and `chap`. And last, ensure the file `example.py` is available in `mods-config/python`. When starting the server in debug mode and trying to authenticate using bob/hello, we'll get a failed password, but we should some lines like this in the debug logging

    *** authorize ***
    
    *** radlog call in authorize ***
    
    (('User-Name', '"bob"'), ('User-Password', '"hello"'), ...many more attributes...)

This is the equivalent of "Hello, world" in `rlm_python`. The next step is making the authentication really work

#### Writing the code

Just a quick sidestep. To make the user authenticate with password 'Hello', we need to add the attribute `Cleartext-Password` with value 'Hello' to the config list. The give the user some feedback, we can add the `Reply-Message` attribute to the reply list.

Let's construct the reply tuples first. In the method `authorize`, below the line `print p`, add the following two lines:

    reply = ( ('Reply-Message', 'Hello from rlm_python'), )
    config = ( ('Cleartext-Password', 'hello'), )

If you're not used to Python: make sure you don't mess up indenting tabs and spaces in your source file, and don't omit the trailing commas (otherwise python decides to flatten the tuples).

Now we have to return these tuples to FreeRADIUS. To do that, replace the line with `return radiusd.RLM_MODULE_OK` with the following line:

    return (radiusd.RLM_MODULE_OK, reply, config)

As discussed before: we return the status, the reply updates and the config updates. Trying again in debug mode should now add the following lines:

    rlm_python:authorize: 'reply:Reply-Message' = 'Hello from rlm_python'
    rlm_python:authorize: 'config:Cleartext-Password' = 'hello'

(FreeRADIUS older than version 3.0.11 shows less debug output, don't worry too much about that)

And your authentication should now be successful, with an added attribute that says hello from python.

From version 3.0.11, you can also add operators to the return tuples. To do this, use a tuple with 3 items:

    reply = ( ('Tmp-String-0', ':=', 'Another hello from rlm_python'), )

== TODO

1. Do we need to support other pair operations beyond set (:=) ?
2. Should we pass the value pair info as a dict and not a tuple? Faster?
3. Give access to more radiusd variables like the dictionary. 3. Give
access to other C functions. Let the Python module deal with the
structures directly, instead of letting our C code do it afterwards.
What’s a good way to represent this?
