CREATE TABLE RADIPPOOL (
        ID                      INT PRIMARY KEY,
        POOL_NAME               VARCHAR(30) NOT NULL,
        FRAMEDIPADDRESS         VARCHAR(30) NOT NULL,
        NASIPADDRESS            VARCHAR(30) NOT NULL,
        POOL_KEY                VARCHAR(64) NOT NULL,
        CALLEDSTATIONID         VARCHAR(64),
        CALLINGSTATIONID        VARCHAR(64) NOT NULL,
        EXPIRY_TIME             TIMESTAMP(0) NOT NULL,
        USERNAME                VARCHAR(100)
);
 
CREATE INDEX RADIPPOOL_POOLNAME_IPADDR ON RADIPPOOL (POOL_NAME, FRAMEDIPADDRESS);
CREATE INDEX RADIPPOOL_POOLNAME_EXPIRE ON RADIPPOOL (POOL_NAME, EXPIRY_TIME);
CREATE INDEX RADIPPOOL_NASIPADDR_KEY ON RADIPPOOL (NASIPADDRESS, POOL_KEY);
CREATE INDEX RADIPPOOL_NASIPADDR_CALLING ON RADIPPOOL (NASIPADDRESS, CALLINGSTATIONID);
 
CREATE SEQUENCE RADIPPOOL_SEQ START WITH 1 INCREMENT BY 1;
 
CREATE OR REPLACE TRIGGER RADIPPOOL_SERIALNUMBER
        BEFORE INSERT OR UPDATE OF ID ON RADIPPOOL
        FOR EACH ROW
        BEGIN
                IF ( :NEW.ID = 0 OR :NEW.ID IS NULL ) THEN
                        SELECT RADIPPOOL_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
                END IF;
        END;
/
