#
#	$Id$
#

TARGET		= rlm_attr_filter
SRCS		= rlm_attr_filter.c
HEADERS		=
RLM_CFLAGS	=
RLM_LIBS	=

# over-ride the previous assignment if we're not building anything
include ../rules.mak

$(STATIC_OBJS): $(HEADERS)

$(DYNAMIC_OBJS): $(HEADERS)

